### ISSUE TITLE
Child processes are orphaned when main locker process dies

### ISSUE THREAD

**Issue by jamii** [LockerProject/Locker#10]
eg https://github.com/quartzjer/Locker/issues#issue/8

Surely there is some standard solution for this kind of thing? 

Potential solution - child processes and their parents should regularly ping each other over pipes. If the child fails to respond, the parent kills and restarts it. If the parent fails to respond, the child kills itself.

**Comment by temas** [comment]
I sure wish there as, but pings is the only thing I'm pulling up in my head as well.

**Comment by jamii** [comment]
More radical proposal - use couchdb, attach locker processes as os_daemons (or even just as couchapps) and place each processes webserver under the couchdb reverse proxy. This gives you:
- Process management (restart failed processes, kill everything when couchdb is stopped)
- Unified HTTP namespace (don't have to remember which port each process ends up on)
- JSON databases (with versioning and limited transaction support)
- Database update notifications
- Automatically updated views, written in any language (javascript is the default)
- Syncing/replication between nodes
- Centralized configuration and logging

It seems like this solves a lot of problems for free. 

[New externals API](http://davispj.com/2010/09/26/new-couchdb-externals-api.html)

[CouchDB docs](http://couchdb.apache.org/docs/overview.html)

**Comment by tilgovi** [comment]
There's this: http://stackoverflow.com/questions/5541288/node-js-detect-when-parent-process-exits

Though I think the cleaner option is for node to provide the very standard getppid() call and the child can monitor with setInterval() to see if the parent pid has changed.

**Comment by tilgovi** [comment]
What I said doesn't apply when locker doesn't own the code of the child process. Sorry.

**Comment by tilgovi** [comment]
Perhaps the best solution is to fork immediately on startup, leaving the parent as a watchdog that is unlikely to terminate. If it catches a SIGCHLD for the main process it can send a SIGHUP/SIGKILL to its process group with `process.kill(-process.getgid())`. Of course, this requires the child processes not to daemonize.

**Comment by quartzjer** [comment]
I think this might help a ton here, thanks for raising this again :)

https://github.com/LockerProject/Locker/commit/612da751b45836ddd95bda378d00fec76f35470c
