### ISSUE TITLE
getLinks is dying 

### ISSUE THREAD

**Issue by nym** [LockerProject/Locker#102]
1. Start locker
2. Goto:
   http://localhost:8042/query/getLink?offset=0&limit=1
3. Watch terminal output do this:

/Users/tomlong/code/l/Locker/Ops/webservice.js:105
            var collection = mongo.collections[provider.mongoCollections[0]];
                                                                        ^
TypeError: Cannot read property '0' of undefined
    at /Users/tomlong/code/l/Locker/Ops/webservice.js:105:73
    at /Users/tomlong/code/l/Locker/Common/node/lmongoclient.js:37:13
    at /Users/tomlong/code/l/Locker/Common/node/lmongoclient.js:29:13
    at /Users/tomlong/code/l/Locker/node_modules/mongodb/lib/mongodb/db.js:54:14
    at /Users/tomlong/code/l/Locker/node_modules/mongodb/lib/mongodb/connections/server.js:57:11
    at /Users/tomlong/code/l/Locker/node_modules/mongodb/lib/mongodb/admin.js:14:12
    at [object Object].<anonymous> (/Users/tomlong/code/l/Locker/node_modules/mongodb/lib/mongodb/admin.js:84:12)
    at [object Object].emit (events.js:67:17)
    at [object Object].<anonymous> (/Users/tomlong/code/l/Locker/node_modules/mongodb/lib/mongodb/connections/server.js:78:12)
    at [object Object].emit (events.js:64:17)

**Comment by nym** [comment]
HelloLinks is in the repo now if you want to reproduce without typing anything into the browser bar.

**Comment by ctide** [comment]
If anyone is still seeing this problem, just delete the links directory under the Me folder and restart locker.  It will work moving forward, and we'll come up with a better solution to that part of the problem shortly.
