### ISSUE TITLE
fix package-deps

### ISSUE THREAD

**Issue by Finkregh** [LockerProject/Locker#104]
some packages are not available at some specific (old) version; please change deps from "=version" to ">=version"

available versions would be:
- api-easy 0.2.3
- http-proxy 0.5.10

also remove duplicate entrys (http-proxy)

**Comment by smurthas** [comment]
Looks like we are already using those versions, maybe your local copy is a few days behind?

**Comment by Finkregh** [comment]
you might be right there....

i used github.com/quartzjer/Locker as written in the howto at http://lockerproject.org/
So you might want to change that git:// link :)

**Comment by smurthas** [comment]
Yes, we changed it in the README.md here, but forgot about the website. Thanks for pointing that out!
