### ISSUE TITLE
Problems installing applications in current master

### ISSUE THREAD

**Issue by ctide** [LockerProject/Locker#106]
03:08 < irace> Hello - just got my Locker up and running. Whenever I try to install something, it just loads the whole UI inside the frame :(
03:10 < ctide> can you take a screenshot of what you're seeing?
03:11 < irace> Sure, here it is: http://cl.ly/7mgr

I was able to reproduce this is I use the config.json that's in the repo (none of the externalX options set) every time.  Refreshing the page will let you use installed apps OK, just installing them will cause this behavior.  Links are also looking a bit funny, like it's not using the handle anymore or something.

**Comment by smurthas** [comment]
I am also seeing this. It's almost certainly my fault, as I've been making changes to the dashboard UI but am highly under-qualified to being doing so. :).I'll get this fixed tonight.

**Comment by smurthas** [comment]
this is fixed by: https://github.com/LockerProject/Locker/commit/9c1045530fb1ec420a537ab487667d6631b06b8b
