### ISSUE TITLE
Authentication flows don't work inside of iframes

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#107]
Several of the connectors marked "stable" have auth flows that don't work inside of the iframe. Definitely an issue with:

Facebook
Google Contacts
Twitter

**Comment by nym** [comment]
I'll take this on.

Cheers,

## Tom Longson (nym)

http://tomlongson.com

On Tue, Jun 21, 2011 at 12:58 AM, smurthas
reply@reply.github.com
wrote:
