### ISSUE TITLE
future issues with stdin

### ISSUE THREAD

**Issue by frank06** [LockerProject/Locker#108]
I'm seeing this in various places:

```
var stdin = process.openStdin();
stdin.setEncoding('utf8');
stdin.on('data', function (chunk) {
    var processInfo = JSON.parse(chunk);
    lockerBase = processInfo.lockerUrl;
    locker.initClient(processInfo);
    process.chdir(processInfo.workingDirectory);
    app.listen(processInfo.port,function() {
        var returnedInfo = {};
        console.log(JSON.stringify(returnedInfo));
    });
});
```
- The `data` event may be called multiple times. Listen to `end` as well
- This bit of code be put in a utils module and reused

**Comment by smurthas** [comment]
The only problem is stdin doesn't emit the end event until the process ends. :).

But yes, it could/should be in the utils module.

**Comment by frank06** [comment]
True. Let's just hope the JSON will never ever come in more than one chunk. :)

**Comment by smurthas** [comment]
FYI, this issue (config) is going to be addressed on a larger scale in next few weeks (discussion will happen in IRC).

**Comment by ctide** [comment]
All of the 'stable' components have been changed to address this concern.
