### ISSUE TITLE
Simplify the locker core proxying

### ISSUE THREAD

**Issue by temas** [LockerProject/Locker#11]
The proxy functions are mostly mirrored in the GET and POST handlers as well as the proxied() and proxiedPost().  Merge this up.  Clean this up.  Win.

**Comment by smurthas** [comment]
Unicode chars get mashed in the process, this should also be fixed. This can become a second issue if needed.

**Comment by smurthas** [comment]
The proxy should also respond to and propagate redirects.

**Comment by smurthas** [comment]
This is resolved as of the referenced commit. Closing.
