### ISSUE TITLE
Twitter mention sync finds a new (duplicate) mention every time

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#125]
Every 2 minutes, I see in my log "Twitter Account: synced mentions with 1 new entries". This happened all night long when I left it running.

Checking Me/twitter/mentions.json, a single entry is being duplicated every time. It looks like this:

{"timeStamp":1311351861277,"data":{"in_reply_to_status_id":93934648765325310,"user":{"default_profile":false,"follow_request_sent":false,"time_zone":"Sydney","protected":false,"location":"","show_all_inline_media":false,"following":true,"geo_enabled":true,"profile_use_background_image":false,"name":"Lindsay Holmwood","profile_background_color":"040a46","url":"http://holmwood.id.au/~lindsay","verified":false,"profile_background_image_url":"http://a1.twimg.com/images/themes/theme13/bg.gif","utc_offset":36000,"listed_count":118,"statuses_count":6827,"profile_background_image_url_https":"https://si0.twimg.com/images/themes/theme13/bg.gif","favourites_count":82,"created_at":"Mon Apr 14 03:46:38 +0000 2008","profile_text_color":"040a46","profile_image_url_https":"https://si0.twimg.com/profile_images/1210884135/architecture_normal.jpg","profile_image_url":"http://a2.twimg.com/profile_images/1210884135/architecture_normal.jpg","profile_sidebar_fill_color":"ffffff","description":"sysadmin/developer, toolsmith, from Sydney, Australia","contributors_enabled":false,"lang":"en","profile_background_tile":false,"followers_count":998,"screen_name":"auxesis","default_profile_image":false,"id_str":"14380900","friends_count":539,"profile_link_color":"91028f","id":14380900,"is_translator":false,"notifications":false,"profile_sidebar_border_color":"01f7ff"},"created_at":"Thu Jul 21 07:26:00 +0000 2011","geo":null,"in_reply_to_user_id":35592163,"favorited":false,"text":"@mdzimm you said it!","in_reply_to_status_id_str":"93934648765325312","entities":{"hashtags":[],"user_mentions":[{"name":"Matt Zimmerman","indices":[0,7],"screen_name":"mdzimm","id_str":"35592163","id":35592163}],"urls":[]},"in_reply_to_screen_name":"mdzimm","in_reply_to_user_id_str":"35592163","place":null,"coordinates":null,"truncated":false,"source":"<a href=\"http://twitter.com/#!/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>","id_str":"93944801195589632","contributors":null,"retweeted":false,"retweet_count":0,"id":93944801195589630}}

{"timeStamp":1311351861277,"data":{"in_reply_to_status_id":93934648765325310,"user":{"default_profile":false,"follow_request_sent":false,"time_zone":"Sydney","protected":false,"location":"","show_all_inline_media":false,"following":true,"geo_enabled":true,"profile_use_background_image":false,"name":"Lindsay Holmwood","profile_background_color":"040a46","url":"http://holmwood.id.au/~lindsay","verified":false,"profile_background_image_url":"http://a1.twimg.com/images/themes/theme13/bg.gif","utc_offset":36000,"listed_count":118,"statuses_count":6827,"profile_background_image_url_https":"https://si0.twimg.com/images/themes/theme13/bg.gif","favourites_count":82,"created_at":"Mon Apr 14 03:46:38 +0000 2008","profile_text_color":"040a46","profile_image_url_https":"https://si0.twimg.com/profile_images/1210884135/architecture_normal.jpg","profile_image_url":"http://a2.twimg.com/profile_images/1210884135/architecture_normal.jpg","profile_sidebar_fill_color":"ffffff","description":"sysadmin/developer, toolsmith, from Sydney, Australia","contributors_enabled":false,"lang":"en","profile_background_tile":false,"followers_count":998,"screen_name":"auxesis","default_profile_image":false,"id_str":"14380900","friends_count":539,"profile_link_color":"91028f","id":14380900,"is_translator":false,"notifications":false,"profile_sidebar_border_color":"01f7ff"},"created_at":"Thu Jul 21 07:26:00 +0000 2011","geo":null,"in_reply_to_user_id":35592163,"favorited":false,"text":"@mdzimm you said it!","in_reply_to_status_id_str":"93934648765325312","entities":{"hashtags":[],"user_mentions":[{"name":"Matt Zimmerman","indices":[0,7],"screen_name":"mdzimm","id_str":"35592163","id":35592163}],"urls":[]},"in_reply_to_screen_name":"mdzimm","in_reply_to_user_id_str":"35592163","place":null,"coordinates":null,"truncated":false,"source":"<a href=\"http://twitter.com/#!/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>","id_str":"93944801195589632","contributors":null,"retweeted":false,"retweet_count":0,"id":93944801195589630}}

[...repeats hundreds of times...]

**Comment by mdz** [comment]
Here's state.json: {"syncing":3,"updated":1311352102215,"syncingLast":1311352102215,"status":"done syncing mentions","statusLast":1311352102215,"home_timeline":464,"home_timelineLast":1311289266532,"user_timeline":1703,"user_timelineLast":1311289267411,"mentions":1109,"mentionsLast":1311352102207,"friends":202,"friendsLast":1311288773328}

**Comment by mdz** [comment]
This apparently went away

**Comment by ctide** [comment]
Fixed with synclets, I believe.
