### ISSUE TITLE
Needed to do "npm install winston"

### ISSUE THREAD

**Issue by Sjors** [LockerProject/Locker#127]
I upgraded my Mac to Leopard and I pull the latest version (808df542ba8b1f5...) from Github, so I'm not sure which of these two factors are responsible. Launching the server resulted in the follow error:

```
node lockerd.js 

node.js:134
    throw e; // process.nextTick error, or 'error' event on first tick
    ^
Error: Cannot find module 'winston'
```

After a few minutes on Google I solved it with a simple "npm install winston", but that might not be obvious for people not familiar with Node.js

**Comment by othiym23** [comment]
There's a definite documentation issue lurking in there, but in general, when you've pulled the newest codebase, rerunning npm install immediately thereafter is a good idea.

**Comment by ctide** [comment]
You'll need to do npm install one last time when you pull down the source again, but moving forward running the locker will automatically ensure that all the packages are up to date when launching.
