### ISSUE TITLE
Expand /diary GET to support days and possibly pagination.

### ISSUE THREAD

**Issue by temas** [LockerProject/Locker#13]
Right now the GET to /diary only returns the current days events, which is correct for the basic call at all times.  To take this a step further, we should support getting previous days diaries as well as pagination if a diary starts getting really long.

I see pagination probably changing the result from an array to an object that gives the line count of the first line, the max line count and the array of lines.

**Comment by ctide** [comment]
I'm going to close this out since the diary needs to be reimplemented at some point, most things aren't pushing information to it anymore anyways.
