### ISSUE TITLE
Dashboard first page connector message confusing

### ISSUE THREAD

**Issue by temas** [LockerProject/Locker#131]
The first page of the dashboard now states that the owner should "Install a Connector".  Connector is unknown terminology at this point and this statement has been confusing to a few people trying to start with the locker.  They only get things going because of slight familiarity with the project or following the similar word on the left.  This phrase could become a link to the actual services list as a first step.  Later we could have a wizard to guide people through picking connectors to install.

**Comment by mdz** [comment]
Assigned to Tom since I think guided setup addresses this

**Comment by nym** [comment]
The guided setup is now in master.
