### ISSUE TITLE
Auth error page doesn't mention what the error was

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#139]
I just attempt to auth Github and got a redirect URI mismatch error, which I noticed in the URL: /Me/github/auth/?error=redirect_uri_mismatch

The page, however, just says "Got an error while attempting to authenticate :" and "Please reenter your credentials below."  It should probably mention what happened.

**Comment by ctide** [comment]
Synclet auth returns the error from the provider when it doesn't get an auth token.
