### ISSUE TITLE
Chain syncs in twitter losing some?

### ISSUE THREAD

**Issue by temas** [LockerProject/Locker#143]
The async chain of sync calls in the twitter connector seems to have some odd behavior for the tail end.  When friends and followers were at the end I would sometimes see it not generate contact events ever.  I'm wondering if this is possibly rate limiting being hit or just some long pulls in the middle of the chain causing it to appear like that.  It needs a bit deeper exploration.

**Comment by temas** [comment]
More than likely this is fixed by commit bbe3259332e9bff6c7d5 but it needs testing.

**Comment by ctide** [comment]
Going to close this out, can reopen if we see it happening in the synclet code as well.
