### ISSUE TITLE
Facebook Connector Sync Error

### ISSUE THREAD

**Issue by insanoid** [LockerProject/Locker#145]
After authenticating the facebook connector and clicking on sync all, i get the following error on the console.

proxying GET /Me/facebook/newsfeed to http://localhost:50328//newsfeed
8 Aug 11:05:07 - info: [Locker] Proxy complete
8 Aug 11:05:18 - error: [Facebook Account] 
8 Aug 11:05:18 - error: [Facebook Account] /Users/User/lockerTemp/lockerbox/Locker/Connectors/Facebook/sync.js:305
8 Aug 11:05:18 - error: [Facebook Account]         addAll(posts, newPosts.reverse());
                               ^
8 Aug 11:05:18 - error: [Facebook Account] TypeError: Cannot call method 'reverse' of undefined

and on the browser a few seconds later I usually get  :

An error has occurred: {"stack":"Error: socket hang up\n    at Socket.<anonymous> (http.js:1286:45)\n
at Socket.emit (events.js:64:17)\n    at Array.0 (net.js:831:12)\n    at EventEmitter._tickCallback (node.js:126:26)","message":"socket hang up"}

**Comment by ctide** [comment]
Closing this out as it's being replaced by the facebook synclet which doesn't (hopefully!) exhibit this behavior.
