### ISSUE TITLE
Hard to tell which build is running from the locker UI

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#146]
Things are moving pretty quickly, and a few times recently there's been confusion about functionality because it wasn't clear which build the owner was running. It would be great to see, for example, a build number on the dashboard.

**Comment by ctide** [comment]
Hitting /core/revision will return the git revision number that's currently now.

**Comment by amcjen** [comment]
This is currently available via http://localhost:8042/core/revision .  Did you want this exposed on the UI itself?

**Comment by mdz** [comment]
On Mon, Sep 12, 2011 at 05:03:46PM -0700, Eric Jennings wrote:

> This is currently available via http://localhost:8042/core/revision .  Did you want this exposed on the UI itself?

Yes, I do.  Thanks!

## 
- mdz

**Comment by amcjen** [comment]
Added this feature to the branding branch.
