### ISSUE TITLE
Not able to load friends/photos from Flickr Connector

### ISSUE THREAD

**Issue by nym** [LockerProject/Locker#147]
I followed the following instructions:
https://github.com/LockerProject/Locker/wiki/Setting-up-Flickr

I clicked "load friends" and "photos", and the only activity in the console happened after I clicked Photos, but I can't see any photos or contacts showing up in HelloPhotos / HelloContacts.

Here's my console log (clipped)

8 Aug 14:49:14 - info: [Locker] proxying GET /favicon.ico to http://localhost:18042/favicon.ico
8 Aug 14:49:16 - info: [Locker] proxying GET /Me/flickr/friends to http://localhost:18043//friends
8 Aug 14:49:16 - info: [Locker] Proxy complete
8 Aug 14:49:18 - info: [Locker] proxying GET /favicon.ico to http://localhost:18042/favicon.ico
8 Aug 14:49:29 - info: [Locker] proxying GET /favicon.ico to http://localhost:18042/favicon.ico
8 Aug 14:49:31 - info: [Locker] proxying GET /favicon.ico to http://localhost:18042/favicon.ico
8 Aug 14:49:33 - info: [Locker] proxying GET /Me/flickr/ to http://localhost:18043//
8 Aug 14:49:33 - info: [Locker] Proxy complete
8 Aug 14:49:33 - info: [Locker] proxying GET /favicon.ico to http://localhost:18042/favicon.ico
8 Aug 14:49:35 - info: [Locker] proxying GET /Me/flickr/photos to http://localhost:18043//photos
8 Aug 14:49:35 - info: [Locker] Proxy complete
8 Aug 14:49:35 - info: [Locker] proxying GET /favicon.ico to http://localhost:18042/favicon.ico
8 Aug 14:49:38 - info: [Locker] proxying GET /favicon.ico to http://localhost:18042/favicon.ico
8 Aug 14:49:38 - error: [Flickr Account] DEBUG: got flickr photo 5255660354

8 Aug 14:49:38 - debug: Firing an event for photo/flickr from flickr action(new)
8 Aug 14:49:38 - info: [Locker] spawning into: /Users/tomlong/ltest/lockerbox/Locker/Me/photos
8 Aug 14:49:39 - info: [Locker] sending photos startup info of {"port":18044,"sourceDirectory":"/Users/tomlong/ltest/lockerbox/Locker/Collections/Photos","workingDirectory":"/Users/tomlong/ltest/lockerbox/Locker/Me/photos","lockerUrl":"http://localhost:8042","externalBase":"http://localhost:8042/Me/photos/","mongo":{"host":"localhost","port":27018,"collections":["photos"]}}
8 Aug 14:49:41 - error: [Photos] 8 Aug 14:49:41 - debug: connected to mongo [object Object]

8 Aug 14:49:41 - error: [Photos] 8 Aug 14:49:41 - debug: Photos sync init mongoCollection([object Object])

8 Aug 14:49:41 - error: [Photos] 8 Aug 14:49:41 - debug: dataStore init mongoCollection([object Object])

8 Aug 14:49:41 - info: [Photos] photos started at pid 18966, running startup callbacks.
8 Aug 14:49:41 - debug: Firing event to photos to /events
8 Aug 14:49:41 - info: [Locker] proxying POST /Me/photos/events to http://localhost:18044//events
8 Aug 14:49:41 - info: [Locker] Proxy complete
8 Aug 14:49:41 - error: [Photos] 8 Aug 14:49:41 - debug: Error processing: The flickr data was invalid

8 Aug 14:49:41 - error: [Locker] There was an error sending an event to photos at /events got 500
8 Aug 14:49:42 - error: [Flickr Account] DEBUG: got flickr photo 5255660374

8 Aug 14:49:42 - debug: Firing an event for photo/flickr from flickr action(new)
8 Aug 14:49:42 - debug: Firing event to photos to /events
8 Aug 14:49:42 - info: [Locker] proxying POST /Me/photos/events to http://localhost:18044//events
8 Aug 14:49:42 - info: [Locker] Proxy complete
8 Aug 14:49:42 - error: [Photos] 8 Aug 14:49:42 - debug: Error processing: The flickr data was invalid

8 Aug 14:49:42 - error: [Locker] There was an error sending an event to photos at /events got 500
8 Aug 14:49:44 - error: [Flickr Account] DEBUG: got flickr photo 5255686160

8 Aug 14:49:44 - debug: Firing an event for photo/flickr from flickr action(new)
8 Aug 14:49:44 - debug: Firing event to photos to /events
8 Aug 14:49:44 - info: [Locker] proxying POST /Me/photos/events to http://localhost:18044//events
8 Aug 14:49:44 - info: [Locker] Proxy complete
8 Aug 14:49:44 - error: [Photos] 8 Aug 14:49:44 - debug: Error processing: The flickr data was invalid

8 Aug 14:49:44 - error: [Locker] There was an error sending an event to photos at /events got 500
8 Aug 14:49:47 - error: [Flickr Account] DEBUG: got flickr photo 5255076867

8 Aug 14:49:47 - debug: Firing an event for photo/flickr from flickr action(new)
8 Aug 14:49:47 - debug: Firing event to photos to /events
8 Aug 14:49:47 - info: [Locker] proxying POST /Me/photos/events to http://localhost:18044//events
8 Aug 14:49:47 - info: [Locker] Proxy complete
8 Aug 14:49:47 - error: [Photos] 8 Aug 14:49:47 - debug: Error processing: The flickr data was invalid

8 Aug 14:49:47 - error: [Locker] There was an error sending an event to photos at /events got 500
8 Aug 14:49:49 - error: [Flickr Account] DEBUG: got flickr photo 5255076919

8 Aug 14:49:49 - debug: Firing an event for photo/flickr from flickr action(new)
8 Aug 14:49:49 - debug: Firing event to photos to /events
8 Aug 14:49:49 - info: [Locker] proxying POST /Me/photos/events to http://localhost:18044//events
8 Aug 14:49:49 - info: [Locker] Proxy complete
8 Aug 14:49:49 - error: [Photos] 8 Aug 14:49:49 - debug: Error processing: The flickr data was invalid

8 Aug 14:49:49 - error: [Locker] There was an error sending an event to photos at /events got 500
8 Aug 14:49:53 - error: [Flickr Account] DEBUG: got flickr photo 5255690868

8 Aug 14:49:53 - debug: Firing an event for photo/flickr from flickr action(new)
8 Aug 14:49:53 - debug: Firing event to photos to /events
8 Aug 14:49:53 - info: [Locker] proxying POST /Me/photos/events to http://localhost:18044//events
8 Aug 14:49:53 - info: [Locker] Proxy complete
8 Aug 14:49:53 - error: [Photos] 8 Aug 14:49:53 - debug: Error processing: The flickr data was invalid

8 Aug 14:49:53 - error: [Locker] There was an error sending an event to photos at /events got 500
8 Aug 14:49:55 - error: [Flickr Account] DEBUG: got flickr photo 5255691264

8 Aug 14:49:55 - debug: Firing an event for photo/flickr from flickr action(new)
8 Aug 14:49:55 - debug: Firing event to photos to /events
8 Aug 14:49:55 - info: [Locker] proxying POST /Me/photos/events to http://localhost:18044//events
8 Aug 14:49:55 - info: [Locker] Proxy complete
8 Aug 14:49:55 - error: [Photos] 8 Aug 14:49:55 - debug: Error processing: The flickr data was invalid

8 Aug 14:49:55 - error: [Locker] There was an error sending an event to photos at /events got 500
8 Aug 14:49:58 - info: [Locker] proxying GET /favicon.ico to http://localhost:18042/favicon.ico
8 Aug 14:50:00 - error: [Flickr Account] DEBUG: got flickr photo 5255078255

8 Aug 14:50:00 - debug: Firing an event for photo/flickr from flickr action(new)
8 Aug 14:50:00 - debug: Firing event to photos to /events
8 Aug 14:50:00 - info: [Locker] proxying POST /Me/photos/events to http://localhost:18044//events
8 Aug 14:50:00 - info: [Locker] Proxy complete
8 Aug 14:50:00 - error: [Photos] 8 Aug 14:50:00 - debug: Error processing: The flickr data was invalid

8 Aug 14:50:00 - error: [Locker] There was an error sending an event to photos at /events got 500
8 Aug 14:50:01 - info: [Locker] proxying GET /favicon.ico to http://localhost:18042/favicon.ico
8 Aug 14:50:01 - error: [Flickr Account] DEBUG: got flickr photo 5255078473

8 Aug 14:50:01 - debug: Firing an event for photo/flickr from flickr action(new)
8 Aug 14:50:01 - debug: Firing event to photos to /events
8 Aug 14:50:01 - info: [Locker] proxying POST /Me/photos/events to http://localhost:18044//events
8 Aug 14:50:01 - info: [Locker] Proxy complete
8 Aug 14:50:01 - error: [Photos] 8 Aug 14:50:01 - debug: Error processing: The flickr data was invalid

8 Aug 14:50:01 - error: [Locker] There was an error sending an event to photos at /events got 500
8 Aug 14:50:04 - info: [Locker] proxying GET /install?id=9 to http://localhost:18042/install?id=9
8 Aug 14:50:04 - info: [Locker] Having to spawn hellophotos
8 Aug 14:50:04 - info: [Locker] spawning into: /Users/tomlong/ltest/lockerbox/Locker/Me/hellophotos
8 Aug 14:50:04 - info: [Locker] sending hellophotos startup info of {"port":18045,"sourceDirectory":"/Users/tomlong/ltest/lockerbox/Locker/Apps/HelloPhotos","workingDirectory":"/Users/tomlong/ltest/lockerbox/Locker/Me/hellophotos","lockerUrl":"http://localhost:8042","externalBase":"http://localhost:8042/Me/hellophotos/"}
8 Aug 14:50:04 - info: [Locker] Proxy complete
8 Aug 14:50:04 - info: [Locker] proxying GET /favicon.ico to http://localhost:18042/favicon.ico
8 Aug 14:50:05 - info: [Hello Photos] hellophotos started at pid 18968, running startup callbacks.
8 Aug 14:50:05 - info: [Hello Photos] proxying GET /Me/hellophotos/ to http://localhost:18045//
8 Aug 14:50:05 - info: [Locker] proxying GET /Me/hellophotos/css/style.css?v=2 to http://localhost:18045//css/style.css?v=2
8 Aug 14:50:05 - info: [Locker] Proxy complete
8 Aug 14:50:05 - info: [Locker] proxying GET /static/js/boilerplate/libs/modernizr-1.7.min.js to http://localhost:18042/static/js/boilerplate/libs/modernizr-1.7.min.js
8 Aug 14:50:05 - info: [Locker] proxying GET /static/js/boilerplate/plugins.js to http://localhost:18042/static/js/boilerplate/plugins.js
8 Aug 14:50:05 - info: [Locker] proxying GET /static/js/jquery-1.6.1.min.js to http://localhost:18042/static/js/jquery-1.6.1.min.js
8 Aug 14:50:05 - info: [Locker] proxying GET /Me/hellophotos/js/hellophotos-client.js to http://localhost:18045//js/hellophotos-client.js
8 Aug 14:50:05 - info: [Locker] Proxy complete
8 Aug 14:50:06 - info: [Locker] Querying {"collection":"photo","query":{},"limit":9000,"skip":0}
8 Aug 14:50:06 - info: [Locker] proxying GET /favicon.ico to http://localhost:18042/favicon.ico
8 Aug 14:50:06 - error: [Flickr Account] DEBUG: got flickr photo 5255693102

8 Aug 14:50:06 - debug: Firing an event for photo/flickr from flickr action(new)
8 Aug 14:50:06 - debug: Firing event to photos to /events
8 Aug 14:50:06 - info: [Locker] proxying POST /Me/photos/events to http://localhost:18044//events
8 Aug 14:50:06 - info: [Locker] Proxy complete
8 Aug 14:50:06 - error: [Photos] 8 Aug 14:50:06 - debug: Error processing: The flickr data was invalid

8 Aug 14:50:06 - error: [Locker] There was an error sending an event to photos at /events got 500
8 Aug 14:50:07 - info: [Locker] proxying GET /favicon.ico to http://localhost:18042/favicon.ico
8 Aug 14:50:08 - info: [Locker] proxying GET /favicon.ico to http://localhost:18042/favicon.ico
8 Aug 14:50:10 - error: [Flickr Account] DEBUG: got flickr photo 5255153115

8 Aug 14:50:10 - debug: Firing an event for photo/flickr from flickr action(new)
8 Aug 14:50:10 - debug: Firing event to photos to /events
8 Aug 14:50:10 - info: [Locker] proxying POST /Me/photos/events to http://localhost:18044//events
8 Aug 14:50:10 - info: [Locker] Proxy complete
8 Aug 14:50:10 - error: [Photos] 8 Aug 14:50:10 - debug: Error processing: The flickr data was invalid

8 Aug 14:50:10 - error: [Locker] There was an error sending an event to photos at /events got 500
8 Aug 14:50:13 - info: [Locker] proxying GET /favicon.ico to http://localhost:18042/favicon.ico
8 Aug 14:50:15 - error: [Flickr Account] DEBUG: got flickr photo 5267315476

8 Aug 14:50:15 - debug: Firing an event for photo/flickr from flickr action(new)
8 Aug 14:50:15 - debug: Firing event to photos to /events
8 Aug 14:50:15 - info: [Locker] proxying POST /Me/photos/events to http://localhost:18044//events
8 Aug 14:50:15 - info: [Locker] Proxy complete
8 Aug 14:50:15 - error: [Photos] 8 Aug 14:50:15 - debug: Error processing: The flickr data was invalid

8 Aug 14:50:15 - error: [Locker] There was an error sending an event to photos at /events got 500
8 Aug 14:50:19 - error: [Flickr Account] DEBUG: got flickr photo 5302048610

8 Aug 14:50:19 - debug: Firing an event for photo/flickr from flickr action(new)
8 Aug 14:50:19 - debug: Firing event to photos to /events
8 Aug 14:50:19 - info: [Locker] proxying POST /Me/photos/events to http://localhost:18044//events
8 Aug 14:50:19 - info: [Locker] Proxy complete
8 Aug 14:50:19 - error: [Photos] 8 Aug 14:50:19 - debug: Error processing: The flickr data was invalid

8 Aug 14:50:19 - error: [Locker] There was an error sending an event to photos at /events got 500
8 Aug 14:50:21 - error: [Flickr Account] DEBUG: got flickr photo 5334514144

8 Aug 14:50:21 - debug: Firing an event for photo/flickr from flickr action(new)
8 Aug 14:50:21 - debug: Firing event to photos to /events
8 Aug 14:50:21 - info: [Locker] proxying POST /Me/photos/events to http://localhost:18044//events
8 Aug 14:50:21 - info: [Locker] Proxy complete
8 Aug 14:50:21 - error: [Photos] 8 Aug 14:50:21 - debug: Error processing: The flickr data was invalid

8 Aug 14:50:21 - error: [Locker] There was an error sending an event to photos at /events got 500
8 Aug 14:50:21 - info: [Locker] proxying GET /install?id=6 to http://localhost:18042/install?id=6
8 Aug 14:50:21 - info: [Locker] Having to spawn hellocontacts
8 Aug 14:50:21 - info: [Locker] spawning into: /Users/tomlong/ltest/lockerbox/Locker/Me/hellocontacts
8 Aug 14:50:21 - info: [Locker] sending hellocontacts startup info of {"port":18046,"sourceDirectory":"/Users/tomlong/ltest/lockerbox/Locker/Apps/HelloContacts","workingDirectory":"/Users/tomlong/ltest/lockerbox/Locker/Me/hellocontacts","lockerUrl":"http://localhost:8042","externalBase":"http://localhost:8042/Me/hellocontacts/"}
8 Aug 14:50:21 - info: [Locker] Proxy complete
8 Aug 14:50:21 - info: [Locker] proxying GET /favicon.ico to http://localhost:18042/favicon.ico
8 Aug 14:50:22 - info: [Hello Contacts] hellocontacts started at pid 18970, running startup callbacks.
8 Aug 14:50:22 - info: [Hello Contacts] proxying GET /Me/hellocontacts/ to http://localhost:18046//
8 Aug 14:50:22 - info: [Locker] proxying GET /Me/hellocontacts/css/style.css?v=2 to http://localhost:18046//css/style.css?v=2
8 Aug 14:50:22 - info: [Locker] Proxy complete
8 Aug 14:50:22 - info: [Locker] proxying GET /static/js/jquery-1.6.1.min.js to http://localhost:18042/static/js/jquery-1.6.1.min.js
8 Aug 14:50:22 - info: [Locker] proxying GET /static/js/boilerplate/libs/modernizr-1.7.min.js to http://localhost:18042/static/js/boilerplate/libs/modernizr-1.7.min.js
8 Aug 14:50:22 - info: [Locker] proxying GET /Me/hellocontacts/js/hellocontacts-client.js to http://localhost:18046//js/hellocontacts-client.js
8 Aug 14:50:22 - info: [Locker] Proxy complete
8 Aug 14:50:22 - info: [Locker] proxying GET /static/js/boilerplate/plugins.js to http://localhost:18042/static/js/boilerplate/plugins.js
8 Aug 14:50:22 - info: [Locker] Querying {"collection":"contact","query":{},"limit":9000,"skip":0}
8 Aug 14:50:22 - info: [Locker] proxying GET /favicon.ico to http://localhost:18042/favicon.ico
8 Aug 14:50:22 - error: [Flickr Account] DEBUG: got flickr photo 5460449030

8 Aug 14:50:22 - debug: Firing an event for photo/flickr from flickr action(new)
8 Aug 14:50:22 - debug: Firing event to photos to /events
8 Aug 14:50:22 - info: [Locker] proxying POST /Me/photos/events to http://localhost:18044//events
8 Aug 14:50:22 - info: [Locker] Proxy complete
8 Aug 14:50:22 - error: [Photos] 8 Aug 14:50:22 - debug: Error processing: The flickr data was invalid

8 Aug 14:50:22 - error: [Locker] There was an error sending an event to photos at /events got 500
8 Aug 14:50:23 - info: [Locker] proxying GET /favicon.ico to http://localhost:18042/favicon.ico
8 Aug 14:50:28 - info: [Locker] proxying GET /favicon.ico to http://localhost:18042/favicon.ico
8 Aug 14:50:29 - error: [Flickr Account] DEBUG: got flickr photo 5460457048

8 Aug 14:50:29 - debug: Firing an event for photo/flickr from flickr action(new)
8 Aug 14:50:29 - debug: Firing event to photos to /events
8 Aug 14:50:29 - info: [Locker] proxying POST /Me/photos/events to http://localhost:18044//events
8 Aug 14:50:29 - info: [Locker] Proxy complete
8 Aug 14:50:29 - error: [Photos] 8 Aug 14:50:29 - debug: Error processing: The flickr data was invalid

8 Aug 14:50:29 - error: [Locker] There was an error sending an event to photos at /events got 500
8 Aug 14:50:30 - info: [Locker] proxying GET /favicon.ico to http://localhost:18042/favicon.ico
8 Aug 14:50:30 - error: [Flickr Account] DEBUG: got flickr photo 5504306780

8 Aug 14:50:30 - debug: Firing an event for photo/flickr from flickr action(new)
8 Aug 14:50:30 - debug: Firing event to photos to /events
8 Aug 14:50:30 - info: [Locker] proxying POST /Me/photos/events to http://localhost:18044//events
8 Aug 14:50:30 - info: [Locker] Proxy complete
8 Aug 14:50:30 - error: [Photos] 8 Aug 14:50:30 - debug: Error processing: The flickr data was invalid

8 Aug 14:50:30 - error: [Locker] There was an error sending an event to photos at /events got 500
8 Aug 14:50:32 - error: [Flickr Account] DEBUG: got flickr photo 5581180310

8 Aug 14:50:32 - debug: Firing an event for photo/flickr from flickr action(new)
8 Aug 14:50:32 - debug: Firing event to photos to /events
8 Aug 14:50:32 - info: [Locker] proxying POST /Me/photos/events to http://localhost:18044//events
8 Aug 14:50:32 - info: [Locker] Proxy complete
8 Aug 14:50:32 - error: [Photos] 8 Aug 14:50:32 - debug: Error processing: The flickr data was invalid

8 Aug 14:50:32 - error: [Locker] There was an error sending an event to photos at /events got 500
8 Aug 14:50:34 - error: [Flickr Account] DEBUG: got flickr photo 5600849339

8 Aug 14:50:34 - debug: Firing an event for photo/flickr from flickr action(new)
8 Aug 14:50:34 - debug: Firing event to photos to /events
8 Aug 14:50:34 - info: [Locker] proxying POST /Me/photos/events to http://localhost:18044//events
8 Aug 14:50:34 - info: [Locker] Proxy complete
8 Aug 14:50:34 - error: [Photos] 8 Aug 14:50:34 - debug: Error processing: The flickr data was invalid

8 Aug 14:50:34 - error: [Locker] There was an error sending an event to photos at /events got 500
8 Aug 14:50:35 - error: [Flickr Account] DEBUG: got flickr photo 5621009780

8 Aug 14:50:35 - debug: Firing an event for photo/flickr from flickr action(new)
8 Aug 14:50:35 - debug: Firing event to photos to /events
8 Aug 14:50:35 - info: [Locker] proxying POST /Me/photos/events to http://localhost:18044//events
8 Aug 14:50:35 - info: [Locker] Proxy complete
8 Aug 14:50:35 - error: [Photos] 8 Aug 14:50:35 - debug: Error processing: The flickr data was invalid

8 Aug 14:50:35 - error: [Locker] There was an error sending an event to photos at /events got 500
8 Aug 14:50:37 - error: [Flickr Account] DEBUG: got flickr photo 5959567509

8 Aug 14:50:37 - debug: Firing an event for photo/flickr from flickr action(new)
8 Aug 14:50:37 - debug: Firing event to photos to /events
8 Aug 14:50:37 - info: [Locker] proxying POST /Me/photos/events to http://localhost:18044//events
8 Aug 14:50:37 - info: [Locker] Proxy complete
8 Aug 14:50:37 - error: [Photos] 8 Aug 14:50:37 - debug: Error processing: The flickr data was invalid

8 Aug 14:50:37 - error: [Locker] There was an error sending an event to photos at /events got 500
8 Aug 14:50:40 - error: [Flickr Account] DEBUG: got flickr photo 5959573807

8 Aug 14:50:40 - debug: Firing an event for photo/flickr from flickr action(new)
8 Aug 14:50:40 - debug: Firing event to photos to /events
8 Aug 14:50:40 - info: [Locker] proxying POST /Me/photos/events to http://localhost:18044//events
8 Aug 14:50:40 - info: [Locker] Proxy complete
8 Aug 14:50:40 - error: [Photos] 8 Aug 14:50:40 - debug: Error processing: The flickr data was invalid

8 Aug 14:50:40 - error: [Locker] There was an error sending an event to photos at /events got 500
8 Aug 14:50:42 - error: [Flickr Account] DEBUG: got flickr photo 5959573919

**Comment by mdz** [comment]
I see similar behavior. Me/flickr ends up populated, but the collection remains empty.

**Comment by mdz** [comment]
Hitting /Me/photos/update manually seems to work around the issue for me

**Comment by nym** [comment]
Yeah, it seems like the Link / Photo collections need to be "poked"
sometimes to update.

Cheers,

## Tom Longson (nym)

http://tomlongson.com

On Tue, Aug 16, 2011 at 10:47 AM, mdz
reply@reply.github.com
wrote:

**Comment by ctide** [comment]
This was resolved by converting flickr to a synclet.
