### ISSUE TITLE
Certain OAuth providers require constant refreshing of tokens.

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#149]
For example, Google hands out access tokens valid for an hour and requires the use of a refresh token being POSTed to receive a new access token.

"When your access token expires, our API endpoints will respond with HTTP 401 Unauthorized. At any time, you can use the token endpoint with your refresh token, client credentials and the parameter grant_type=refresh_token to get a new short-lived access token"

(http://code.google.com/apis/accounts/docs/OAuth2.html)

**Comment by temas** [comment]
I think we've talked about it previously, but we need to investigate everyauth for the connector level.

**Comment by smurthas** [comment]
This refresh is handled by the gdata-js module. Whenever a 401 is encountered, it tries to refresh the token. If a new token is granted, it emits a 'tokenRefresh' event. The Google Contacts connector currently listens for those events and updates the auth.json file.

Is there something that is broken as a result of this?

**Comment by smurthas** [comment]
This is resolved in commit r97ae445
