### ISSUE TITLE
Services do not spawn when called through the proxy

### ISSUE THREAD

**Issue by jamii** [LockerProject/Locker#15]
With commit ac67a509ec8ffcd4fdcb20f6b1861c4010c8c57a

Install a service (tested with XMPP and IMAP)
Navigate to the service page via dashboard
The front page shows up
Restart node
Navigate to the service page via dashboard
Node says 'Having to spawn ...'
Front page does not load
No python processes are running
The front page does not load

**Comment by temas** [comment]
Updates in commits 7fec01eb635d4c12d169f1ac208d844ed239c1a7 and 666489870bd54098108dbc8d784cf8e5a3de6d9e

Pending tests by @jamii

**Comment by jamii** [comment]
Oops, should have closed this.
