### ISSUE TITLE
Problems with google contacts synclet

### ISSUE THREAD

**Issue by ctide** [LockerProject/Locker#161]
I periodically see some big failures like this:

23 Aug 11:37:02 - info: [Locker] Synclet timeline starting for twitter
23 Aug 11:37:02 - error: [Google Contacts Account contacts] 401 baby!!

23 Aug 11:37:03 - error: [Google Contacts Account contacts] 

23 Aug 11:37:03 - error: [Google Contacts Account contacts] undefined:1

23 Aug 11:37:03 - error: [Google Contacts Account contacts] Ӳj㫝��$m����ɂ�˾A
�G���5Ҵ[�!(hI�O���#X������^]��f��}
�QE϶���a�7��<`�+�>w�2�y�g:3���-��  ��������/�����dk����ı��U�b�)o�B�s�l;%�p�ԕ�vPx@V,�Y&F|L�n�W�N�tu��� ���SJ*1~��͞��0{iq�rD��Z�
                                 +@Vm�����
                                          *Ii��J

23 Aug 11:37:03 - error: [Google Contacts Account contacts] ^^

23 Aug 11:37:03 - error: [Google Contacts Account contacts] SyntaxError: Unexpected token ILLEGAL
    at Object.parse (native)

**Comment by mdz** [comment]
I see something similar too:

25 Aug 10:42:52 - error: [Google Contacts Account contacts] 401 baby!!

25 Aug 10:42:53 - error: [Google Contacts Account contacts] 

25 Aug 10:42:53 - error: [Google Contacts Account contacts] undefined:1

^^
SyntaxError: Unexpected token ILLEGAL
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/home/mdz/src/singly/Locker/node_modules/gdata-js/gdata.js:103:33)
    at IncomingMessage.emit (events.js:64:17)
    at HTTPParser.onBody (http.js:121:23)
    at CleartextStream.ondata (http.js:1227:22)
    at CleartextStream._push (tls.js:303:27)
    at SecurePair.cycle (tls.js:574:20)
    at EncryptedStream.write (tls.js:96:13)
    at Socket.ondata (stream.js:36:26)
    at Socket.emit (events.js:64:17)

**Comment by quartzjer** [comment]
my google contacts synclet starts and never finishes, could be related :(

**Comment by smurthas** [comment]
I'll check it out!

On Sep 1, 2011, at 22:18, quartzjer
reply@reply.github.com
wrote:

**Comment by smurthas** [comment]
This is be resolved in commit r97ae445
