### ISSUE TITLE
Contacts/people needs some thought for i18n

### ISSUE THREAD

**Issue by temas** [LockerProject/Locker#163]
Currently we have assumptions on first/last name support in search and sorting.  This needs to be part of a bigger i18n chat probably.

**Comment by ctide** [comment]
Is this something we really think needs to be in for milestone 1?  Seems we can punt this off for at least a month or two.

**Comment by smurthas** [comment]
I agree with ctide - it's definitely important, but doesn't seem like it needs to block our current objective. If others feel really strongly, please comment - for now I'm moving it out.

**Comment by temas** [comment]
closing this and filing a larger i18n tracker.
