### ISSUE TITLE
Twitter synclet crashes locker: Error: EBADF, Bad file descriptor '/.../Me/twitter-1/981.json' 

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#168]
Updated my locker (which already had data in it), then started running through guided setup. After Twitter, I got one of these:

25 Aug 08:54:58 - error: [Twitter Account friends] { statusCode: 502,
  data: '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1
[...]

followed by hundreds and hundreds of these:

25 Aug 08:54:58 - error: [Locker] failed to set current, l145 of common/node/synclet/datastore
25 Aug 08:54:58 - error: [Locker] twitter-1_663
25 Aug 08:54:58 - error: [Locker] undefined
25 Aug 08:54:58 - error: [Locker] function (err, newType) {
        if (type === 'same') return callback(err, newType);
        ijodFiles[type].addRecord(timeStamp, object, function(err) {
            callback(err, newType);
        });
    }

followed by:

fs.js:221
  return binding.open(path, stringToFlags(flags), mode);
                 ^
Error: EBADF, Bad file descriptor '/home/mdz/src/singly/Locker/Me/twitter-1/981.json'
    at Object.openSync (fs.js:221:18)
    at new IJOD (/home/mdz/src/singly/Locker/Common/node/ijod.js:23:28)zsh: exit 1     node lockerd.js

which crashed my locker. Not sure if this is one bug or more.

**Comment by mdz** [comment]
In my case, Me/twitter-1 does not exist (but I have lots of Me/twitter/NNN.json)

**Comment by mdz** [comment]
Possibly the same as #170 and #179 according to ctide

**Comment by ctide** [comment]
Fixed in f2a98de9b3522c1c8c2b7695d41286cbc1e24169
