### ISSUE TITLE
failed to set current, l145 of common/node/synclet/datastore

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#170]
I get thousands of these, and it seems to be preventing twitter from syncing. For some reason, this code:

```
    console.error(type)
    console.error(object)
    console.error(callback);
```

doesn't seem to print anything to the log, but this:

```
    console.dir([type,object,callback]);
    console.error('failed to set current, l145 of common/node/synclet/datastore');
```

prints things like:

['twitter_zalgo', undefined, [Function]]

**Comment by ctide** [comment]
Fixed in f2a98de9b3522c1c8c2b7695d41286cbc1e24169
