### ISSUE TITLE
Flickr Authorization Fails

### ISSUE THREAD

**Issue by bassdread** [LockerProject/Locker#171]
After entering my API details I am prompted to click a link "you need to auth w/ flickr yet" clicking this link returns an error from Flickr stating this action isnt allow in a frame. Clicking the suggested link from Flickr returns a error stating Locker didn't provide a callback url.

The POST to Flickr seems to be missing the oauth_callback= parameter.

**Comment by ctide** [comment]
Closing this as the flickr connector's been replaced by the flickr synclet (which has documentation for setting up auth keys properly.)  Let me know if you're still having problems using the synclet version of flickr.
