### ISSUE TITLE
What should I be backing up?

### ISSUE THREAD

**Issue by cbbrowne** [LockerProject/Locker#174]
It's not quite evident what I should backup.

What I'd ideally like to do with my locker is to capture its output into a Git repository, and periodically commit what has been captured.

This is particularly useful in these early days, when it's most likely that there are "data-eating" bugs lurking around.  (That's not to be accusative, just that connectors are being hacked in pretty rapidly, and, c'mon, there be dragons there!)
- Should I be capturing things under $HOME/Locker/Me?
- Is some of it sitting in a MongoDB, so that I'd need to dump that in order to logically back it up?
- Is this something where it would be useful to have an "app" module that:
  a) Runs mongodump?
  b) Lists the paths where Locker thinks archivable data is living?

**Comment by smurthas** [comment]
The entirety of the Me dir is what you want - try the BackMeUp app - it creates a tarball of the whole dir! The mongo data is currently only really used as an index into the data, the raw json is stored in all of the other subdirs of Me/.
