### ISSUE TITLE
Fails in a mysterious way when mongod is left running from an earlier locker invocation

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#184]
net.js:1023
  if (typeof self.fd === 'number') throw new Error('Server already opened');
                                         ^
Error: Server already opened
    at HTTPServer.listen (net.js:1023:42)
    at Object.startService (/home/mdz/src/singly/Locker/Ops/webservice.js:451:12)
    at finishStartup (/home/mdz/src/singly/Locker/lockerd.js:137:20)
    at /home/mdz/src/singly/Locker/lockerd.js:114:17
    at /home/mdz/src/singly/Locker/Common/node/lcrypto.js:64:13
    at path.js:292:19

No idea why this happens.

**Comment by merc3po** [comment]
Is this still happening?

**Comment by smurthas** [comment]
Yes. This is still relevant.

**Comment by mdz** [comment]
#672 should address this
