### ISSUE TITLE
error: [Search] TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#186]
About to index the following:
{ type: 'status/twitter',
  via: 'synclet/twitter',
  timestamp: 1314731832205,
  action: 'new',
  obj: 
   { source: 'twitter_tweets',
     type: 'new',
     data: 
      { _id: '4e5d3732c1fb30840e714156',
        in_reply_to_screen_name: null,
        truncated: false,
        in_reply_to_user_id_str: null,
        coordinates: null,
        created_at: 'Sat Jun 11 21:03:09 +0000 2011',
        contributors: null,
        retweeted: false,
        retweet_count: 0,
        in_reply_to_user_id: null,
        id_str: '79654927328219137',
        user: [Object],
        geo: null,
        source: '<a href="https://wiki.ubuntu.com/Gwibber" rel="nofollow">Ubuntu</a>',
        entities: [Object],
        in_reply_to_status_id: null,
        favorited: false,
        id: 79654927328219140,
        in_reply_to_status_id_str: null,
        place: null,
        text: '♺ @TechCrunch: Fred Wilson On Disruption: "You Can\'t Stop What People Ultimately Want To Have Happen" &lt;&lt; if only this were true in politics' } } }

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^

30 Aug 12:17:19 - error: [Search] TypeError: Cannot read property 'id' of undefined
    at [object Object].indexType (/home/mdz/src/singly/Locker/Common/node/lsearch.js:119:22)
    at Array.indexMore (/home/mdz/src/singly/Locker/Common/node/lsearch.js:244:27)
    at EventEmitter._tickCallback (node.js:126:26)

**Comment by mdz** [comment]
This is accompanied by a storm of:

30 Aug 12:18:46 - info: [Locker] proxying POST /Me/places/events to http://localhost:18047//events
30 Aug 12:18:46 - info: [Locker] Proxy complete
30 Aug 12:18:46 - info: [Locker] Having to spawn search
30 Aug 12:18:46 - info: [Locker] search is still spawning, adding callback to queue.
30 Aug 12:18:46 - info: [Locker] Proxy complete

**Comment by amcjen** [comment]
This should be resolved with the searchresults merge!
