### ISSUE TITLE
Cannot read property 'length' of undefined in search.jade

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#187]
500 TypeError: /home/mdz/src/singly/Locker/Apps/Search/views/search.jade:16 14| - if (results[r]._type === 'contacts') 15| li > 16| - if (results[r].fullobject.photos.length > 0) 17| .fll 18|   19| .clb Cannot read property 'length' of undefined
14| - if (results[r]._type === 'contacts')
15| li

> 16| - if (results[r].fullobject.photos.length > 0)
> 17| .fll
> 18|  
> 19| .clb
> Cannot read property 'length' of undefined
> at anonymous (eval at (/home/mdz/src/singly/Locker/node_modules/jade/lib/jade.js:162:8))
> at Object. (/home/mdz/src/singly/Locker/node_modules/jade/lib/jade.js:167:12)
> at ServerResponse._render (/home/mdz/src/singly/Locker/node_modules/express/lib/view.js:343:22)
> at ServerResponse.render (/home/mdz/src/singly/Locker/node_modules/express/lib/view.js:218:17)
> at /home/mdz/src/singly/Locker/Apps/Search/app.js:82:11
> at [object Object].callback (/home/mdz/src/singly/Locker/Apps/Search/lib/lockersearch/index.js:42:13)
> at IncomingMessage. (/home/mdz/src/singly/Locker/node_modules/request/main.js:260:21)
> at IncomingMessage.emit (events.js:81:20)
> at HTTPParser.onMessageComplete (http.js:133:23)
> at Socket.ondata (http.js:1227:22)

**Comment by amcjen** [comment]
This should be resolved with the searchresults merge!
