### ISSUE TITLE
"Can't render headers after they are sent to the client"

### ISSUE THREAD

**Issue by amcjen** [LockerProject/Locker#188]
When trying to run a search query on the dashboard, I get the following output.  

(I echoed the error before this gets called, and get the following:  
30 Aug 19:04:43 - error: [Locker] TypeError: Cannot read property 'slaveOk' of null.  error: [Locker] broke!)

http.js:573
    throw new Error("Can't render headers after they are sent to the client.")
          ^
Error: Can't render headers after they are sent to the client.
    at ServerResponse._renderHeaders (http.js:573:11)
    at ServerResponse.writeHead (http.js:806:20)
    at /Volumes/Data/opt/locker/Common/node/synclet/dataaccess.js:73:25
    at Object.getCurrent (/Volumes/Data/opt/locker/Common/node/synclet/datastore.js:131:9)
    at /Volumes/Data/opt/locker/Common/node/synclet/dataaccess.js:71:23
    at /Volumes/Data/opt/locker/Common/node/synclet/datastore.js:22:9
    at /Volumes/Data/opt/locker/Common/node/lmongoclient.js:37:13
    at /Volumes/Data/opt/locker/Common/node/lmongoclient.js:29:13
    at /Volumes/Data/opt/locker/node_modules/mongodb/lib/mongodb/db.js:74:30
    at /Volumes/Data/opt/locker/node_modules/mongodb/lib/mongodb/connections/server.js:64:34

**Comment by ctide** [comment]
That slaveOk null error means your mongo instance was unreachable for some reason.  Can you reproduce this reliably?

**Comment by amcjen** [comment]
I can get rid of it when I clear out my Me/ directory.  Then if I only install Twitter (and Facebook I believe), it won't occur.  However, when I install gcontacts, soon after I get the error again when trying to run search.  Correlation only, no idea if gcontacts is causing it.

**Comment by amcjen** [comment]
Closing.  Haven't seen this one in a while.
