### ISSUE TITLE
Broken images in "Hello Photos"

### ISSUE THREAD

**Issue by jasoncavnar** [LockerProject/Locker#190]
When I click photos I get a broken image with this:

This is example of how easy it is to load your photos using HTML and jQuery.

{
  "_id": "4e5da7092312866830889a6e",
  "id": "12bcc416a64057433465f55f298244f57952240c",
  "sources": [
    {
      "service": "synclet/facebook",
      "id": null
    }
  ],
  "url": "facebook_photo"
}

When I try to open broken image icon in new tab I get:

An error has occurred: {"stack":"Error: socket hang up\n    at Socket.<anonymous> (http.js:1285:45)\n    at Socket.emit (events.js:64:17)\n    at Array.0 (net.js:831:12)\n    at EventEmitter._tickCallback (node.js:126:26)","message":"socket hang up"}

**Comment by bassdread** [comment]
Hi, can you confirm there is something in Me/facebook/photo.json? If so is there anything when you visit http://localhost:8042/Me/facebook/getCurrent/photo ?

You don't need to paste the content of those links just check there is something there. If nothing is there the sync has failed somehow.

**Comment by ctide** [comment]
This is fixed now.  It was fixed as part of the work done to get photo events from synclets being handled properly.
