### ISSUE TITLE
Facebook home call sometimes returns the full set of data

### ISSUE THREAD

**Issue by ctide** [LockerProject/Locker#193]
1 Sep 20:26:57 - error: [Facebook Account home] https://graph.facebook.com/me/home?access_token=..&date_format=U&since=1314933501

1 Sep 20:26:58 - info: [Locker] Synclet home finished for facebook
1 Sep 20:27:01 - info: [Locker] Synclet users starting for github
1 Sep 20:27:15 - info: [Locker] Synclet users finished for github
1 Sep 20:27:52 - info: [Locker] Synclet recent starting for foursquare
1 Sep 20:27:54 - info: [Locker] Synclet recent finished for foursquare
1 Sep 20:28:49 - info: [Locker] Synclet home starting for facebook
1 Sep 20:28:49 - info: [Locker] Synclet timeline starting for twitter
1 Sep 20:28:49 - error: [Facebook Account home] https://graph.facebook.com/me/home?access_token=...&date_format=U&since=1314933501

1 Sep 20:28:50 - info: [Locker] Synclet home finished for facebook
1 Sep 20:28:50 - info: [Locker] Synclet checkins starting for foursquare
1 Sep 20:28:50 - info: [Locker] Synclet timeline finished for twitter
1 Sep 20:28:50 - debug: Firing an event for timeline/twitter from synclet/twitter action(new)
1 Sep 20:28:50 - debug: Firing event to links to /events
1 Sep 20:28:50 - debug: Firing event to places to /events
1 Sep 20:28:50 - info: [Locker] proxying POST /Me/links/events to http://localhost:18047//events
1 Sep 20:28:50 - info: [Locker] Proxy complete
1 Sep 20:28:50 - info: [Locker] proxying POST /Me/places/events to http://localhost:18048//events
1 Sep 20:28:50 - info: [Locker] Proxy complete
1 Sep 20:28:50 - error: [Links] QUEUE SIZE: 1
QUEUE SIZE: 0

1 Sep 20:28:51 - info: [Locker] Synclet checkins finished for foursquare
1 Sep 20:28:54 - info: [Locker] Synclet recent starting for foursquare
1 Sep 20:28:55 - info: [Locker] Synclet recent finished for foursquare
1 Sep 20:28:58 - info: [Locker] Synclet home starting for facebook
1 Sep 20:28:58 - error: [Facebook Account home] https://graph.facebook.com/me/home?access_token=...&date_format=U&since=1314933501

1 Sep 20:29:15 - info: [Locker] Synclet users starting for github
1 Sep 20:29:28 - info: [Locker] Synclet users finished for github
1 Sep 20:29:30 - info: [Locker] Synclet home finished for facebook
1 Sep 20:29:30 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:30 - debug: Firing event to links to /events
1 Sep 20:29:30 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:30 - debug: Firing event to links to /events
1 Sep 20:29:30 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:30 - debug: Firing event to links to /events
1 Sep 20:29:30 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:30 - debug: Firing event to links to /events
1 Sep 20:29:30 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:30 - debug: Firing event to links to /events
1 Sep 20:29:30 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:30 - debug: Firing event to links to /events
1 Sep 20:29:30 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:30 - debug: Firing event to links to /events
1 Sep 20:29:30 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:30 - debug: Firing event to links to /events
1 Sep 20:29:30 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:30 - debug: Firing event to links to /events
1 Sep 20:29:30 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:30 - debug: Firing event to links to /events
1 Sep 20:29:30 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:30 - debug: Firing event to links to /events
1 Sep 20:29:30 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:30 - debug: Firing event to links to /events
1 Sep 20:29:30 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:30 - debug: Firing event to links to /events
1 Sep 20:29:31 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:31 - debug: Firing event to links to /events
1 Sep 20:29:31 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:31 - debug: Firing event to links to /events
1 Sep 20:29:31 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:31 - debug: Firing event to links to /events
1 Sep 20:29:31 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:31 - debug: Firing event to links to /events
1 Sep 20:29:31 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:31 - debug: Firing event to links to /events
1 Sep 20:29:31 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:31 - debug: Firing event to links to /events
1 Sep 20:29:31 - info: [Locker] proxying POST /Me/links/events to http://localhost:18047//events
1 Sep 20:29:31 - info: [Locker] Proxy complete
1 Sep 20:29:31 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:31 - debug: Firing event to links to /events
1 Sep 20:29:31 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:31 - debug: Firing event to links to /events
1 Sep 20:29:31 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:31 - debug: Firing event to links to /events
1 Sep 20:29:31 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:31 - debug: Firing event to links to /events
1 Sep 20:29:31 - debug: Firing an event for home/facebook from synclet/facebook action(new)
1 Sep 20:29:31 - debug: Firing event to links to /events
1 Sep 20:29:31 - info: [Locker] proxying POST /Me/links/events to http://localhost:18047//events
1 Sep 20:29:31 - info: [Locker] Proxy complete
1 Sep 20:29:31 - info: [Locker] proxying POST /Me/links/events to http://localhost:18047//events
1 Sep 20:29:31 - info: [Locker] Proxy complete

**_omitted lots and lots of links and events**_

1 Sep 20:29:55 - info: [Locker] Synclet recent starting for foursquare
1 Sep 20:29:57 - info: [Locker] Synclet recent finished for foursquare
1 Sep 20:30:50 - info: [Locker] Synclet home starting for facebook
1 Sep 20:30:50 - info: [Locker] Synclet timeline starting for twitter
1 Sep 20:30:50 - error: [Facebook Account home] https://graph.facebook.com/me/home?access_token=...&date_format=U&since=1314934131

1 Sep 20:30:51 - info: [Locker] Synclet timeline finished for twitter
1 Sep 20:30:51 - info: [Locker] Synclet home finished for facebook
1 Sep 20:30:51 - info: [Locker] Synclet checkins starting for foursquare
1 Sep 20:30:53 - info: [Locker] Synclet checkins finished for foursquare
1 Sep 20:30:57 - info: [Locker] Synclet recent starting for foursquare
1 Sep 20:30:58 - info: [Locker] Synclet recent finished for foursquare
1 Sep 20:31:28 - info: [Locker] Synclet users starting for github
1 Sep 20:31:30 - info: [Locker] Synclet home starting for facebook
1 Sep 20:31:31 - error: [Facebook Account home] https://graph.facebook.com/me/home?access_token=...&date_format=U&since=1314934131

1 Sep 20:31:31 - info: [Locker] Synclet home finished for facebook

**Comment by quartzjer** [comment]
Seems like it was an intermittent Facebook api issue, haven't seen it in ages
