### ISSUE TITLE
2 Sep 10:07:02 - error: [Locker] rut roh! no value for primary key!

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#196]
I'm seeing a lot of these locally, when running on the flickr branch:

2 Sep 10:06:48 - error: [Locker] rut roh! no value for primary key!
2 Sep 10:06:53 - info: [Locker] Synclet users starting for github
2 Sep 10:07:02 - info: [Locker] Synclet users finished for github
2 Sep 10:07:02 - error: [Locker] rut roh! no value for primary key!
2 Sep 10:07:02 - error: [Locker] rut roh! no value for primary key!
2 Sep 10:07:02 - error: [Locker] rut roh! no value for primary key!
2 Sep 10:07:02 - error: [Locker] rut roh! no value for primary key!
2 Sep 10:07:02 - error: [Locker] rut roh! no value for primary key!
2 Sep 10:07:02 - error: [Locker] rut roh! no value for primary key!
2 Sep 10:07:02 - error: [Locker] rut roh! no value for primary key!
2 Sep 10:07:02 - error: [Locker] rut roh! no value for primary key!
2 Sep 10:07:02 - error: [Locker] rut roh! no value for primary key!
2 Sep 10:07:02 - error: [Locker] rut roh! no value for primary key!
2 Sep 10:07:02 - error: [Locker] rut roh! no value for primary key!
2 Sep 10:07:02 - error: [Locker] rut roh! no value for primary key!
2 Sep 10:07:02 - error: [Locker] rut roh! no value for primary key!
2 Sep 10:07:02 - error: [Locker] rut roh! no value for primary key!
2 Sep 10:07:02 - error: [Locker] rut roh! no value for primary key!
2 Sep 10:07:02 - error: [Locker] rut roh! no value for primary key!
2 Sep 10:07:02 - error: [Locker] rut roh! no value for primary key!
2 Sep 10:08:48 - info: [Locker] Synclet timeline starting for twitter
2 Sep 10:08:49 - info: [Locker] Synclet timeline finished for twitter
2 Sep 10:08:49 - error: [Locker] rut roh! no value for primary key!

**Comment by ctide** [comment]
Fixed in: https://github.com/LockerProject/Locker/commit/c64f58a80e7bd8b524377c75718730eaceded72a
