### ISSUE TITLE
Missing icons to connect to services

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#198]
Jason says he set up a new hosted locker and clicked on Links, then was not provided with any options for connecting to services. It sounds like the tray wasn't pulled down. He pulled it down manually, but says it was empty. He tried the other screens (photos/contacts?) with the same result, no icons.

**Comment by ctide** [comment]
This should only happen if there's no apikeys.json file, or if it wasn't read properly.  This shouldn't ever happen on the hosted environment, so I'm going to close this.  If it happens again, we have to catch it while it's happening so we can investigate it in the locker itself.
