### ISSUE TITLE
Search fails after migration 1315333526000_reindex.js

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#201]
6 Sep 12:00:35 - info: [Locker] running migration : 1315333526000_reindex.js for service Search

seems to succeed, but searches don't work afterward. I get:  "No Locker search providers found" and on the console:

6 Sep 12:04:11 - error: [Locker Search] term: foo
6 Sep 12:04:11 - info: [Locker] Looking for providers of type search
6 Sep 12:04:11 - error: [Locker Search] No results object returned for search

If I stop and start the locker, instead I get: "That's an invalid query term, try again!"

**Comment by mdz** [comment]
Here's the log output for the second case (after locker restart):

6 Sep 12:05:54 - error: [Locker Search] term: foo

6 Sep 12:05:54 - info: [Locker] Looking for providers of type search
6 Sep 12:05:54 - info: [Locker] Having to spawn search
6 Sep 12:05:54 - info: [Locker] spawning into: /home/mdz/src/singly/Locker/Me/search
6 Sep 12:05:54 - info: [Locker] sending search startup info of {"port":18045,"sourceDirectory":"/home/mdz/src/singly/Locker/Collections/Search","workingDirectory":"/home/mdz/src/singly/Locker/Me/search","lockerUrl":"http://localhost:8042","externalBase":"http://localhost:8042/Me/search/"}
6 Sep 12:05:54 - info: [Locker] Proxy complete
6 Sep 12:05:54 - info: [Search] Set local uri to http://localhost:18045/ for search
6 Sep 12:05:54 - info: [Search] search started at pid 6740, running startup callbacks.
6 Sep 12:05:54 - info: [Search] proxying GET /Me/search/query?q=foo to http://localhost:18045//query?q=foo
6 Sep 12:05:54 - error: [Search] Error querying via /search/query GET request.

6 Sep 12:05:54 - error: [Locker Search] No results object returned for search

**Comment by amcjen** [comment]
This is strange.  The only thing that will trigger a "No Locker search providers found" error is if locker can't find your search collection.  Seeing as this is on by default, and not uninstallable, something else in the migration must have made it unavailable.

**Comment by temas** [comment]
Just ran from my fairly clean branch, but did have live data from last week.  It successfully did the migration and all services were accessible.

**Comment by mdz** [comment]
I rolled back Me/ and I can't reproduce search being unavailable. However, I can reproduce the "invalid query term" behavior every time.

**Comment by temas** [comment]
I was mistaken and there is a definite bug that I've identified.  Fix in progress.
