### ISSUE TITLE
EADDRINUSE kills lockerd

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#202]
While syncing data, lockerd dies without killing off any other processes giving the following error:

```
node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: EADDRINUSE, Address already in use
    at doConnect (net.js:555:5)
    at net.js:725:9
    at dns.js:192:30
    at Object.lookup (dns.js:190:11)
    at Socket.connect (net.js:718:20)
    at Object.createConnection (net.js:265:5)
    at Agent._getConnection (http.js:1365:15)
    at Agent._establishNewConnection (http.js:1180:21)
    at Agent._cycle (http.js:1405:10)
    at Socket.<anonymous> (http.js:1296:10)
```

All process that should be running already seem to be running and that fact that it kills lockerd, suggests that this is actually happening in the lockerd.js process. 

Perhaps it is a limit on the number of open sockets (as a result of all events happening over http)??

EDIT:

The alternate way you see this crash is:

```
7 Sep 19:16:35 - debug: Firing an event for home/facebook from synclet/facebook action(new)
7 Sep 19:16:35 - debug: Firing event to links to /events
7 Sep 19:16:35 - debug: Firing an event for home/facebook from synclet/facebook action(new)
7 Sep 19:16:35 - debug: Firing event to links to /events

node.js:134
throw e; // process.nextTick error, or 'error' event on first tick
^
Error: socket hang up
at Socket. (http.js:1287:45)
at Socket.emit (events.js:64:17)
at Array. (net.js:831:12)
at EventEmitter._tickCallback (node.js:126:26)
```

**Comment by ctide** [comment]
http://markmail.org/message/tp3alpcpphxcazjq#query:+page:1+mid:tp3alpcpphxcazjq+state:results discusses the issue that's happening here.  OSX keeps an ephemeral port sticking around for 30 seconds, so 16k connections over 30 seconds will cause the locker to collapse when it has no port to snag.

**Comment by ctide** [comment]
http://stackoverflow.com/questions/1216267/ab-program-freezes-after-lots-of-requests-why the first answer here also discusses this issue a bit.

**Comment by quartzjer** [comment]
I can't reproduce this anymore after this fix, re-open this if you can:

https://github.com/LockerProject/Locker/commit/1cb233f803108b271e22e16136b2d34b57bb4ea9#L1R107
