### ISSUE TITLE
Multiple Lockers accessing the same MongoDb

### ISSUE THREAD

**Issue by ghost** [LockerProject/Locker#214]
Hi,

I am trying to run multiple lockers  on my server and all of them should share the same mongoDb and to avoid mixing the data for different users i shall be adding the lockerPort as an additional attribute to each of my entries in the database. What i tried is that in config.json  i specified different port numbers for the lockerPort and the same port number for the mongo port. However when i start my second locker, it shuts down with an exception 'Server Already opened'. What am i missing here ?

Thanks.

**Comment by smurthas** [comment]
could you paste in the two config files and the console output from both?

**Comment by ctide** [comment]
You need to have each locker run their own Mongodb currently.  We don't, yet, support lockers running with a custom database name, or having them connect to an already running mongo database.

**Comment by ghost** [comment]
Hi,

My config files are as follows;
Locker1 

{
    "lockerHost" : "localhost",
    "lockerPort" : 8042,
    "logFile": null,
    "me" : "Me",
    "scannedDirs" : [
        "Apps", 
        "Collections", 
        "Connectors"
        ],
    "mongo" : {
        "dataDir": "mongodata",
        "host": "localhost",
        "port": 27018
    },
        "dashboard" : {
                "customLogo": "tlp_logo.png",
            "customFooter": "singly-footer.html",
            "customTitle": "the locker project"
        }
}

Locker2:
{
    "lockerHost" : "localhost",
    "lockerPort" : 8142,
    "logFile": null,
    "me" : "Me",
    "scannedDirs" : [
        "Apps", 
        "Collections", 
        "Connectors"
        ],
    "mongo" : {
        "dataDir": "mongodata",
        "host": "localhost",
        "port": 27018
    },
        "dashboard" : {
                "customLogo": "tlp_logo.png",
            "customFooter": "singly-footer.html",
            "customTitle": "the locker project"
        }
}

The console output is as follows:
Locker1: Locker1 runs normally.

18 Sep 20:42:21 - info: Set local uri to http://localhost:18043/ for devdashboard
18 Sep 20:42:21 - info: devdashboard started at pid 2323, running startup callbacks.
18 Sep 20:42:21 - info: ui spawned
18 Sep 20:44:21 - info: Synclet home starting for facebook

Locker2:
18 Sep 20:43:32 - info: devdashboard is still spawning, adding callback to queue.

net.js:1023
  if (typeof self.fd === 'number') throw new Error('Server already opened');
                                         ^
Error: Server already opened
    at HTTPServer.listen (net.js:1023:42)
    at Object.startService (/home/devrelay/LockerMongos/Locker2/Ops/webservice.js:474:12)
    at finishStartup (/home/devrelay/LockerMongos/Locker2/lockerd.js:154:20)
    at /home/devrelay/LockerMongos/Locker2/lockerd.js:128:17
    at /home/devrelay/LockerMongos/Locker2/Common/node/lcrypto.js:64:13
    at path.js:292:19

Thanks.

**Comment by ctide** [comment]
Yeah, you'll need to change mongoPort in the second locker config to 27019 (or anything really, just not something already in use such as 27018!)
