### ISSUE TITLE
Domain name error when syncing

### ISSUE THREAD

**Issue by bassdread** [LockerProject/Locker#216]
I get the following snippet https://gist.github.com/1225450 when syncing. Not sure which service is causing is the issue.

**Comment by quartzjer** [comment]
I fixed this in master so that it won't get "stuck" but I can't reproduce the exact error... is it at _all_ possible that before you update you can reproduce this, and grab the full console output from startup to the crash?

**Comment by bassdread** [comment]
https://gist.github.com/1228877 is a complete log using master prior to your patch

**Comment by quartzjer** [comment]
Do you still get this issue? Sadly, and oddly, there wasn't enough debug output to know which link did that, but if you're still getting it I might have you add some more manually to track this down if you're up for it? Just ping me in IRC tomorrow :)

**Comment by bassdread** [comment]
I have been running the latest code and not seen it since. Looks good to me.
