### ISSUE TITLE
LinkaLatte Not Returning Links

### ISSUE THREAD

**Issue by bassdread** [LockerProject/Locker#218]
My LinkaLatte app no longer returns results when using the search box. In the logs:

21 Sep 21:09:03 - info: proxying GET /Me/links/search?q=google to http://localhost:18044//search?q=google

Note the double slash before search.

Manually visiting the url http://localhost:18044//search?q=google gives "Cannot GET //search?q=google". Visiting the url http://localhost:18044/search?q=google displays a lot of json link results.

**Comment by bassdread** [comment]
In the js console on Chrome I get the errors

Failed to load resource: the server responded with a status of 404 (Not Found) :8042/socket.io/1/?t=1316635606016

and

Uncaught TypeError: Cannot read property 'network' of undefined allAlone.js:138

**Comment by quartzjer** [comment]
I think the uncaught error in allAlone is the real bug, does that happen on first load, or after a search? If it's on first load could you gist or put somewhere a copy of your http://localhost:8042/Me/links/getLinksFull?limit=100 ? If it's on search, do the same for the result of the search url?

**Comment by bassdread** [comment]
Happens on first load: https://gist.github.com/1235679

**Comment by bassdread** [comment]
Found the issue:

Line 138 in allAlone.js
return images[arg.item.encounters[arg.item.encounters.length - 1].network];

arg.item.encounters.length == 0

Seems arg.item.encounters is empty
