### ISSUE TITLE
google contacts synclet stops syncing

### ISSUE THREAD

**Issue by quartzjer** [LockerProject/Locker#219]
It doesn't appear to have any token refresh ability, so it will only sync the first time.

**Comment by smurthas** [comment]
[gdata-js](https://github.com/smurthas/gdata-js/blob/master/gdata.js) handles the token refresh transparently. Can you paste logs and the me.json file?

**Comment by quartzjer** [comment]
{"level":"info","message":"Synclet contacts starting for gcontacts"}
{"level":"error","message":"401, baaaaby!\n"}
{"level":"error","message":"refreshing token -- statusCode !== 200, yoikes! data: <HTML>\n<HEAD>\n<TITLE>Client must specify either client_id 
and client_secret or client_assertion, not both</TITLE>\n</HEAD>\n<BODY BGCOLOR=\"#FFFFFF\" TEXT=\"#000000\">\n<H1>Client must specify either 
client_id and client_secret or client_assertion, not both</H1>\n<H2>Error 400</H2>\n</BODY>\n</HTML>\n\nerr <HTML>\n<HEAD>\n<TITLE>Client must
 specify either client_id and client_secret or client_assertion, not both</TITLE>\n</HEAD>\n<BODY BGCOLOR=\"#FFFFFF\" TEXT=\"#000000\">\n<H1>C
lient must specify either client_id and client_secret or client_assertion, not both</H1>\n<H2>Error 400</H2>\n</BODY>\n</HTML>\n\nresult undef
ined\n"}

**Comment by quartzjer** [comment]
https://gist.github.com/1246710

**Comment by smurthas** [comment]
can you also paste in your me.json file (need to check if it has the correct api keys, etc)?

**Comment by quartzjer** [comment]
https://gist.github.com/1246730

**Comment by smurthas** [comment]
ok, I'm on it.

**Comment by quartzjer** [comment]
https://github.com/LockerProject/Locker/commit/e5dc762f5c6f3f27bfb3383bfcd415dc0413f8d0
