### ISSUE TITLE
Broken URL stored for http://ar.gy shortened urls

### ISSUE THREAD

**Issue by bassdread** [LockerProject/Locker#220]
The url in this tweet https://twitter.com/#!/jaybaer/status/116616954625802240 (http://ar.gy/bb1) ended up being stored as:

http://ar.gy/bb1nc=1nc=1nc=1nc=1nc=1nc=1nc=1nc=1nc=1nc=1nc=1nc=1nc=1nc=1nc=1nc=1nc=1nc=1nc=1nc=1nc=1nc=1nc=1nc=1nc=1nc=1nc(repeat another 500 times)

LinkaLatte displays it truncated but its no longer a valid link to the original url. Clicking on it results in a 414 Request-URI Too Large.

I have 2 other tweets from jaybaer all with similar http://ar.gy urls that have been stored in the same corrupted way:

http://ar.gy/bXwnc=1nc=1nc=1nc=1...
http://ar.gy/bb0nc=1nc=1nc=1nc=1...

I don't have the logs of the tweets being fetched, just what is stored locally.

**Comment by ctide** [comment]
This seems to be fixed now.  I made a test account that only followed him, and all of the ar.gy links showed up in my links collection correctly.
