### ISSUE TITLE
Notification bubbles disappear immediately in long-running tabs

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#221]
I leave my locker open in a tab in my browser. Each time I switch to it, i see a flicker of notification bubbles which disappear before I can read any of them. They should probably stay visible for a little longer after I switch, and perhaps be consolidated into a smaller number of notifications (it looked like there were a lot of "one more link" messages).

**Comment by MaxSchultz** [comment]
Whoops didnt mean to close above.... :P

Could merge multiple notifications into one closeable (sticky) notification that remains on the page until closed.

i.e. http://www.erichynds.com/examples/jquery-notify/example.gif

"25 photos, 4 contacts, 3 links added."
