### ISSUE TITLE
Contacts count got inflated in long-running browser tab

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#222]
I left my Singly locker open in a tab overnight, and noticed in the morning that the Contacts tab in the top nav listed about 2,700 contacts, up from about 500. I refreshed the page, and it went back down to around 500.

**Comment by temas** [comment]
I saw this while reseting my contacts vie /Me/contacts/update to test contacts fast.  I think it's related to that reset not being noted by UseUI which has a long running count.  Was that the case here potentially or is this a separate inflation?

**Comment by temas** [comment]
Actually just looking at one of my lockers I had running all morning I'm seeing this now.  Will investigate deeper.

**Comment by quartzjer** [comment]
I believe this properly fixes it: https://github.com/LockerProject/Locker/commit/797506cfc407ba24477ce192ed39d7d3d95819c4
