### ISSUE TITLE
the manifest/me.json merging not working?

### ISSUE THREAD

**Issue by quartzjer** [LockerProject/Locker#225]
It seems the types in the manifests aren't picked up?

https://me.spdev.east.singly.com:8443/providers?types=contact/twitter

Should def return the twitter synclet...

**Comment by ctide** [comment]
Yep, looks like none of that work was propagated to synclets:

https://github.com/LockerProject/Locker/commit/62177de5f733f60b6c1aa95262fa8900e46c92c8

**Comment by quartzjer** [comment]
I think this should fix it? https://github.com/LockerProject/Locker/commit/225d6db64547f8d2200d4c2e083bfac432c621cd

**Comment by ctide** [comment]
Fixed in https://github.com/LockerProject/Locker/commit/0da485ee5966cf15e96f2d0db6092873a16fa7a9

**Comment by mdz** [comment]
It's not clear to me that this is fixed. Should my number of contacts be returning to normal?
