### ISSUE TITLE
Remove Footer

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#234]
It causes UI issues and as of now, doesn't provide significant value. Gitrev can be capture elsewhere if it is needed.

**Comment by mdz** [comment]
The git rev is important (to me at least), and should be moved elsewhere
when the footer is removed.

## 
- mdz

**Comment by ctide** [comment]
It's still available, just have to hit /core/revision.  I thought we agreed we didn't want it in the UI itself?

**Comment by mdz** [comment]
Fine by me
