### ISSUE TITLE
Rename Contacts to People

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#238]
Just in the UI for now.

**Comment by mdz** [comment]
Fixed in https://github.com/LockerProject/Locker/commit/bdb9d0e6473fcef81c770912491ab51c3167a113

**Comment by smurthas** [comment]
I think you close the wrong issue? That commit references removing the footer.

**Comment by mdz** [comment]
I meant to close this bug, but I linked to the wrong commit.

https://github.com/LockerProject/Locker/commit/4fa16bf467979fcbc99913ce6778c9f10bbaa0aa
