### ISSUE TITLE
Let's try out Sphinx

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#246]
CLucene is causing some problems, it's cheap to try out Sphinx.

**Comment by amcjen** [comment]
I checked out Sphinx.  Neat, pretty fast too, but really likes to have a next-door style database (ideally MySQL, but could be anything).  We could run it standalone, and could also hack something together to tie it to Mongo, but I think right now let's put it on hold unless CLucene just blows up in our face or something.
