### ISSUE TITLE
Github confirm window is wrong size

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#250]
http://www.cl.cam.ac.uk/~cce25/locker_pics/GithubBadSize.png after adding Github as a service

**Comment by elsmorian** [comment]
Foursquare window also suffers from this.

**Comment by smurthas** [comment]
For reference, this is only true in the devdashboard.

**Comment by smurthas** [comment]
As the dev dashboard is about to be two generations old, I'm going to close this as a wontfix.
