### ISSUE TITLE
Errors when trying to use Latitude Connector 

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#252]
I suspect my Python path has not been properly set, but I have run ./lockerbox, and easy_install reports flask etc are all installed. However:

3 Oct 15:03:06 - info: Proxy complete
3 Oct 15:03:07 - error: Traceback (most recent call last):

3 Oct 15:03:07 - error:   File "service.py", line 7, in <module>

3 Oct 15:03:07 - error:  
3 Oct 15:03:07 - error: import webservice

3 Oct 15:03:07 - error:   File "/home/elsmorian/Documents/lockerbox/Locker/Connectors/GoogleLatitude/webservice.py", line 5, in <module>

3 Oct 15:03:07 - error:  
3 Oct 15:03:07 - error: from flask import Flask, flash, render_template, render_template_string, request, redirect, url_for

3 Oct 15:03:07 - error: ImportError
3 Oct 15:03:07 - error: : 
3 Oct 15:03:07 - error: No module named flask
3 Oct 15:03:07 - error: 

3 Oct 15:03:07 - info: latitude-1 process has ended. (1:null)

$ easy_install flask
Searching for flask
Best match: Flask 0.8
Processing Flask-0.8-py2.7.egg
Flask 0.8 is already the active version in easy-install.pth

Using /home/elsmorian/Documents/lockerbox/local/lib/python2.7/site-packages/Flask-0.8-py2.7.egg
Processing dependencies for flask
Finished processing dependencies for flask

**Comment by smurthas** [comment]
Can you reproduce this?
