### ISSUE TITLE
Running tests with a running locker fails

### ISSUE THREAD

**Issue by temas** [LockerProject/Locker#255]
I get conflicting port usage and other oddities when having my locker running and trying to run the test suite.  One thing I noticed is that all of the collections still think the passed in port is guaranteed to work rather than using port 0 to bind/listen then reporting back what they actually get to the core.

**Comment by mdz** [comment]
See also https://github.com/LockerProject/Locker/issues/199

**Comment by ctide** [comment]
Fixed in https://github.com/LockerProject/Locker/commit/dc619e137763183d24e8cf84336aa0fab4457a2f
