### ISSUE TITLE
Pre-commit hook to remove trailing whitespace

### ISSUE THREAD

**Issue by ctide** [LockerProject/Locker#257]
Add a pre-commit hook to remove trailing whitespace from commits before committing them

**Comment by smurthas** [comment]
do we really need this? I haven't seen much trailing white space any time recently.

**Comment by ctide** [comment]
Yes, otherwise it keeps coming back and Jer and I keep slowly removing it, but it makes diffs from us a lot more annoying to read.

**Comment by ctide** [comment]
This has to be done individually on everyone's machine, there's no way to push one out automatically as far as I can tell.

Creating a file 'pre-commit' in the .git/hooks directory under your repo that looks like this:

http://snipplr.com/view.php?codeview&id=28523

Will do it.
