### ISSUE TITLE
config.json doesn't seem to be documented anywhere?

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#262]
Maybe I missed it, but I haven't noticed it, and had to go digging in the code to see what it pull out of the json to find out how to configure locker.

**Comment by smurthas** [comment]
Very true! We'll have to get on that. Any chance you want to take a first pass?? :)

**Comment by elsmorian** [comment]
First pass: https://github.com/LockerProject/Locker/wiki/Config.json

**Comment by smurthas** [comment]
Great, thanks! I deleted the customHostedEndpoint page so that it shows up in red and reminds us to add it!
