### ISSUE TITLE
Flickr only importing one of my photos

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#266]
Previously, all of my flickr photos were getting imported, but now I'm only getting one.

I have only one set, I think, but it has a dozen or so photos in it.

**Comment by amcjen** [comment]
I have 18 collections and around 1,500 photos.  I only get one photo per year in the photo viewer, from 2004 to now.  Also, not every year of my photos are showing.  Here's a screenshot:

http://cl.ly/2F2A2C0h0l1w3f0Q2j0P

**Comment by mdz** [comment]
Jer was looking at this this evening and had at least a partial fix locally:

<quartzjer> I'm going to have to finish photo stuff after I land/home
 it's not tested enough yet to check into master

**Comment by quartzjer** [comment]
I've checked a bunch of fixes in but I'm not sure any of them would have fixed this and I can't reproduce it, if it happens after you update from master and the migration update runs let me know and I'll try to track flickr down further.

**Comment by mdz** [comment]
If I start with a fresh Me/ directory, then it pulls in all (14) of my photos from Flickr. :-/

**Comment by smurthas** [comment]
This was resolved.
