### ISSUE TITLE
Notifications should consolidate when in live view

### ISSUE THREAD

**Issue by temas** [LockerProject/Locker#282]
When the view is live and multiple notifications of the same type come in, they should consolidate into one view.

**Comment by smurthas** [comment]
I think was already solved in the old UI, @temas can you confirm (or deny) whether this is still relavant? If it is fixed, we should assign it to @ctide or @merc3po to ensure that we don't regress on this in the next UI.

**Comment by merc3po** [comment]
If by notifications you mean the Growlesque stuff, we're taking them out in the new version of the UI.

**Comment by ctide** [comment]
Closing this since the new UI is not porting over this functionality.
