### ISSUE TITLE
Counts for photos, people, links sometimes don't appear

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#283]
Even after a page refresh!

**Comment by temas** [comment]
Another case we're seeing now is 0s except for a collection that just updated.

**Comment by smurthas** [comment]
hrmm, the last comment says closed, but the issue is open? I believe this is closed by taking out websockets (and switching to JSONP). @temas, is that correct?

**Comment by temas** [comment]
Odd, you are correct, trying to close it again.
