### ISSUE TITLE
Mysterious undefined events

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#285]
Apparently from Twitter in my case, resulting in errors like this:

6 Oct 13:15:18 - error: Received a 404 when attempting to enrich search results from http://localhost:8042/Me/undefined/timeline/4e8e0539d34ee692d00141b7

**Comment by mdz** [comment]
Here's what Chris saw in his log before his locker ended up on this state: https://gist.github.com/54edcded58271b1e65ef

**Comment by temas** [comment]
This is possibly fixed in master now.  It just needs more testing to know it's done for sure.  See the commit b1901e251b41254d2bbfe01a2af8369bffc78cd2

**Comment by mdz** [comment]
Haven't seen any instances since Temas' commit. I believe this is fixed now.
