### ISSUE TITLE
Not possible to start locker from another dir

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#287]
Launching node from another dir, such as the Config dir after editing json config files,'node ../lockerd.js', results in an error as node can't find _lockerd.js.

**Comment by othiym23** [comment]
The official way to run the locker is to run the included "run" script, but it probably also has this problem.

**Comment by elsmorian** [comment]
Indeed it does. Not a big problem, but maybe an annoyance?

**Comment by othiym23** [comment]
Yeah, and a super low-hanging fruit to boot. I'll deal with it when I deal with lockerbox's minor nits.

**Comment by temas** [comment]
Overall file layout has changed slightly, and it has always been intended to run from the top level directory.  Closing this issue.
