### ISSUE TITLE
lockerbox.sh requires either wget or curl, but actually depends upon curl.

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#289]
Having tried to do install of Locker using lockerbox.sh I have found a few errors, and a few things that should be mentioned.

My install system was a blank Ubuntu 11.04 VM, and I was trying to identify issues that would arise when setting up locker for a few users.

Users need to 'sudo apt-get install git libssl-dev' to checkout code and build node. 

Users also must install curl, although you can wget the lockerbox.sh itself, and inside the script it tries to use curl or wget, the npm install script explicitly uses curl, but fails pretty silently, and is only obvious when you ./checkEnv

So, really all that is needed to get everything to install, and pass ./checkEnv

However,  I still had to manually npm install ini to get locker running.

There are also errors as Clucene requires a later version of Node than the one lockerbox.sh installs, but this doesn't stop things working.

**Comment by othiym23** [comment]
1. The wiki documents the build dependencies on OpenSSL and git; there are a billion ways to install and manage packages, and lockerbox can't possibly deal with all of them. You don't want a fairly simpleminded shell script to try to build and install complicated toolchains by itself, trust me.
2. You're right that requiring either curl or wget but depending on curl is a problem. This is a bug and I'll retitle this bug to deal with that.
3. Can you open a new bug and paste a gist of the npm issue you're seeing? That's not something any of us have seen recently in development. I'm not even sure I know what `ini` is.

**Comment by othiym23** [comment]
One further thing -- which version of lockerbox are you using? http://github.com/othiym23/lockerbox or smurthas or pib's? We're going to create an official LockerProject version, but most of the recent tweaking has been done in mine (othiym23's).

**Comment by elsmorian** [comment]
https://github.com/LockerProject/Locker/wiki/Detailed-Set-Up-Instructions does not mention the dependencies on git or libssl-dev, and it is linked from 'detailed instructions' from the lockerproject.org main page.

Thanks for renaming the bug, that is what I was trying to get at in a roundabout way :)

I shall open the ini bug when I have a chance to reinstall locker again.

The lockerbox is smurthas' as it too is linked from the main lockerbox.org page.

**Comment by othiym23** [comment]
OK, so there's two bugs here, the second one being that we need to actually pull a build of lockerbox.sh into the LockerProject hierarchy. Need more roundtuitz!

**Comment by elsmorian** [comment]
In the meantime I've Tweaked the Detailed Setup instructions page to mention the deps.

**Comment by smurthas** [comment]
Where are we at on this?

**Comment by merc3po** [comment]
@elsmorian Where are we on this?

**Comment by kristjan** [comment]
When I was installing a week ago, lockerbox failed for me and I was advised to just `npm install` and then `node _lockerd.js`, which worked. Based on that, it seems like lockerbox is kaput and the installation docs should be updated.

**Comment by smurthas** [comment]
if you already have node and mongod on your machine you are very close to getting things running, but not everyone else has that. lockerbox is still pretty valuable IMO.

**Comment by temas** [comment]
I definitely think we should get this updated and working.  It's been helpful to plenty of people.  Is this issue complete and we need a new one to track updates?

**Comment by mdz** [comment]
@kristjan if lockerbox failed for you, please file a bug on the lockerbox repo

**Comment by mdz** [comment]
There are a few issues discussed here, all of which pertain to either lockerbox or lockerproject.org, both of which have separate repos.
- apparently, OpenSSL development libraries are required in order to build node. but lockerbox doesn't take care of this → lockerbox issue
- curl is required in order to install npm, but this dependency isn't documented → lockerproject.org issue
- clucene →  this is obsolete as it is no longer required
- Manual install doesn't mention git or OpenSSL →  looks like this is fixed on the current wiki page

**Comment by mdz** [comment]
I filed the first issue as https://github.com/LockerProject/lockerbox/issues/6
Merci filed the second issue as https://github.com/LockerProject/lockerproject.org/issues/1

I think that handles everything here, and this one can be closed.
