### ISSUE TITLE
growl-like notifications don't appear on start when new

### ISSUE THREAD

**Issue by quartzjer** [LockerProject/Locker#298]
I don't get the popups anymore after opening up the dashboard again after a while.

**Comment by temas** [comment]
confirmed on my locker as well.

**Comment by smurthas** [comment]
othiym23 saw this with a dev version of chrome, but it could def be a regression in our code. Could one of you try to nail down the approx commit that broke it?

**Comment by temas** [comment]
There's definitely a regression.  I'm not seeing them on a live window either.
