### ISSUE TITLE
node _lockerd.js leaking

### ISSUE THREAD

**Issue by othiym23** [LockerProject/Locker#300]
The core locker process is steadily leaking String objects over time now, causing every locker to grow much larger than they used to between restarts. The V8 profiler clearly shows that the number of Strings is growing by tens of thousands over time, but it's not too useful in pinpointing where those objects are being held.

**Comment by smurthas** [comment]
is this now fixed?

**Comment by othiym23** [comment]
As far as I can tell, no(de). Something is still retaining a lot of memory in the production _lockerd.js Node instances.

**Comment by ctide** [comment]
Watch the memory grow! : https://gist.github.com/9b45d179f61e836f4dfe

I ran _lockerd with trace for a while, and have been investigating with the profiler as well.  It's definitely not releasing all the 'stuff' that's generated when processing a synclet response.
