### ISSUE TITLE
401, baaaaby!

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#301]
I'm seeing this about once per hour from gcontacts, but I don't know why. I'm no longer seeing a syntax error following it (as in #192), but I still see the 401 error itself.

10 Oct 12:25:19 - error: Google Contacts Account contacts   STDERR: 401, baaaaby!

**Comment by smurthas** [comment]
Debug code!! This is normal. :) It's actually on the gdata-js module, I'll remove it from there and update Locker.
