### ISSUE TITLE
Skelton viewer module

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#304]
We should have one. Not as part of the Locker repo itself, not even a submodule, just for docs.

**Comment by ctide** [comment]
https://github.com/LockerProject/Skeleton-Viewer

**Comment by smurthas** [comment]
this is closed then, right?

**Comment by ctide** [comment]
I left it open in case we wanted to add a readme or something explaining it

On Oct 11, 2011, at 8:25 PM, Simon Murtha-Smith
reply@reply.github.com
wrote:

**Comment by smurthas** [comment]
moved to the actual repo: https://github.com/LockerProject/Skeleton-Viewer/issues/1
