### ISSUE TITLE
Twitter Rate Limiting

### ISSUE THREAD

**Issue by alanz** [LockerProject/Locker#306]
My tablet Twitter client is reporting rate limiting (>350 requests/hr) on startup. The only twitter client I have been running is locker.

I suspect that the twitter request rate needs to slow down in the locker sync.

Running version 543b663aad469518102b400d1569a86b9fd779fb

**Comment by alanz** [comment]
More info

26 Oct 11:04:13 - debug: Firing an event for mentions/twitter from twitter action(update)
26 Oct 11:04:59 - info: Synclet checkins starting for foursquare
26 Oct 11:05:04 - info: Synclet checkins finished for foursquare
26 Oct 11:05:04 - info: processing synclet data from checkin of length 0
26 Oct 11:05:04 - info: processing synclet data from photo of length 0
26 Oct 11:05:04 - info: processing synclet data from profile of length 1
26 Oct 11:05:14 - info: Synclet home starting for facebook
26 Oct 11:05:17 - info: Synclet home finished for facebook
26 Oct 11:05:17 - info: processing synclet data from home of length 0
26 Oct 11:06:18 - error: Twitter Account friends    STDERR: { statusCode: 400,
  data: '{"error":"Rate limit exceeded. Clients may not make more than 350 requests per hour.","request":"\/1\/users\/lookup.json?path=%2Fusers%2Flookup.json&user_id=15383497&include_entities=true"}' }

**Comment by smurthas** [comment]
This has been fixed. There was a bug in how the synclet handled bad friend/follower data from Twitter (repolled into infinity).

**Comment by alanz** [comment]
Thanks. Shaping up to be a great product

**Comment by smurthas** [comment]
Spoke too soon, this is still happening. :(. Making it a high priority.

**Comment by smurthas** [comment]
Ok, this should be much better with 
https://github.com/LockerProject/Locker/commit/a6ddac375d7d49e949013924e9ae3c160ef20fbb
and
https://github.com/LockerProject/Locker/commit/d142a288f8c173cdb112ccda7c1e31145e24475e

**Comment by alanz** [comment]
FYI I had been running without rate limiting with
-    "synclets":[{"name": "related", "frequency": 1800},
-                {"name": "friends", "frequency": 3600},
-                {"name": "timeline", "frequency": 120},
-    "synclets":[{"name": "related", "frequency": 3600},
-                {"name": "friends", "frequency": 7200},
-                {"name": "timeline", "frequency": 240},
               {"name": "tweets", "frequency": 600},
               {"name": "mentions", "frequency": 600}],
