### ISSUE TITLE
Character display issues in search results

### ISSUE THREAD

**Issue by temas** [LockerProject/Locker#309]
Presumably this is a UTF8 issue, but it's not investigated yet.  https://dl.dropbox.com/u/1362507/Captured/EiOFQ.png  Following the first link goes to http://www.nintendo.co.jp/3ds/hardware/accessories/list_slidepad/index.html

**Comment by ctide** [comment]
http://imageshar.es/4e95d71f059ef06c320000ef

Search results is doing the right thing, somewhere in the links processing perhaps?

**Comment by quartzjer** [comment]
This is a known issue, that we're not using any character encoding conversion package yet to convert between the common 8559 from scraped pages and utf8 internally, so the titles can get mangled :/

**Comment by temas** [comment]
This UI is dead, closing.
