### ISSUE TITLE
github api limit 100 not 5000, not using api v3 in github module?

### ISSUE THREAD

**Issue by quartzjer** [LockerProject/Locker#312]

**Comment by smurthas** [comment]
Can we just hit the v3 api directly with the request module until the github module is updated to use v3?

**Comment by smurthas** [comment]
Have we hit the API limit anywhere? About how much/often does the synclet hit it? I'm just trying to get at whether this is urgent or even really needed anymore.

**Comment by quartzjer** [comment]
Fixed using v3! https://github.com/LockerProject/Locker/commit/548438fa9ae59324453dcea43f8d89eb52e8dcc5
