### ISSUE TITLE
Locker can't find photosv09 or contactsviewer

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#314]
These apps just proxy to /Me/contactsviewer/notready according to the logs, but no errors are shown, apart from So sad, couldn't find contactsviewer.

This is after a git pull and a delete of my Me dir.  Not, Links app seems to work, and is the only place where the wizard shows up to connect to services.

**Comment by smurthas** [comment]
This got changed (yesterday) but not documented, you need to do a

```
git  submodule update --init
```

if it complains about existing files in Apps/photosv0.9, Apps/MergedContacts, or Apps/PhotosViewer, just blow away those dirs and repull (+ submodule update).

This should be documented on the main page and should also be automatic upon pull (if we can).

**Comment by smurthas** [comment]
did this resolve your isssues?

**Comment by elsmorian** [comment]
Sorry, yes it did!
