### ISSUE TITLE
Logs are becoming unwieldy

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#315]
Logs are full of

13 Oct 11:38:50 - info: Normal proxy of /Me/links/state
13 Oct 11:38:50 - info: proxying GET /Me/links/state to http://localhost:40981//state
13 Oct 11:38:50 - info: Proxy complete

once every second. 

Would it be possible to toggle these state proxy events appearing, as a flag in config? Maybe change the log entry into a object with log file location, log style (Info/Debug/Error) and log state proxy events ?

**Comment by smurthas** [comment]
+1!

**Comment by smurthas** [comment]
This is fixed! PHEW!!!

check out the latest master and take a look at the config.json.example file and you can see how logging levels and file rotation can be utilized.
