### ISSUE TITLE
devdocs don't mention which fields are optional or required

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#316]
I am using the devdocs to test out the /query/getPlace API, however this occurs for other dataSets too.

For example, a query for 'Photo' with no other fields set results in an error, the documentation doesn't mention the offset field is required.

**Comment by smurthas** [comment]
Good catch!
1. The offset field _should_ be optional
2. The dev docs should at least list, if not enforce required (vs optional) fields
