### ISSUE TITLE
devdocs errors are not helpful!

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#317]
Related to #316,

Invalid query /getPhoto<br />Error: Lexical error on line 1. Unrecognized text.
/getPhoto

is the error returned when a user has not set the offset field when using devdocs. The error doesn't mention the lack of the missing field however.

**Comment by ctide** [comment]
Assigning this to temas, I can't really make much sense of the lexical parser.

**Comment by smurthas** [comment]
this is fixed.
