### ISSUE TITLE
click "18 new links" gritter, get 134 links in resulting list

### ISSUE THREAD

**Issue by othiym23** [LockerProject/Locker#322]
Wotta bargain!

**Comment by quartzjer** [comment]
I suspect this is when a bunch more links came in between the gritter and the render of the links page?  The links service and useui only send out count updates when it's idle for a few seconds and if it's busy processing them there wouldn't be any notification event until it quieted down, so this is entirely possible to get more after clicking on a link when lots are coming in.   

Not an easy situation to handle w/ the given UI, what should we do w/ this issue?

**Comment by temas** [comment]
We could try enforcing a lower max wait time to send the event, but this might end up spammy and cause the count to increase in the notification while it's displayed.

**Comment by ctide** [comment]
Do we need to display the # in the notification?  Why not just say New links processed or something to that affect and let people click on it to get the actual #?

**Comment by temas** [comment]
I think I have a working solution for this, but my links stream is slow tonight for a live test.  I'll verify it in the morning.
