### ISSUE TITLE
Devdocs API explorer doesn't allow boolean as a filter term

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#325]
For example for the places collection, using the me field in the JSON would be handy- IE

[me:true]

to get all places that the user has been.

**Comment by quartzjer** [comment]
Could you explain what you mean? The places endpoints aren't listed right now, but the links full=true works as a boolean?

**Comment by elsmorian** [comment]
I can't test for this at the moment, but I will close for now, if it works for current links collections.
