### ISSUE TITLE
Undefined count in the header

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#342]
I couldn't catch a screen shot, but while first connecting accounts, as events flowed in, the counts in the header read "undefined" for a few seconds.

**Comment by ctide** [comment]
I couldn't repro this.  Blew away and reconnected everything 3 times, and never saw any undefineds.

**Comment by temas** [comment]
I'm unable to repro this as well with a series of cases.  I'll watch for it while doing gsv3 today and close it if I can't repro after that.

**Comment by ctide** [comment]
I'm punting this from the milestone since none of us can repro it.

**Comment by quartzjer** [comment]
this ui element is gone now...
