### ISSUE TITLE
"Sync your viewers from GitHub" icon

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#343]
currently it's a plus sign - it should be a sync sign of some sort - doesn't have to be fancy.

**Comment by mdz** [comment]
How about a GitHub logo?

## 
- mdz

**Comment by ctide** [comment]
I don't think I can make a github logo look like a github logo in < 25 pixels

**Comment by mdz** [comment]
The current icon is 74x74, no?

## 
- mdz

**Comment by ctide** [comment]
It's browser resized to 28x28, which includes borders

**Comment by ctide** [comment]
http://imageshar.es/4e9cc6fb059ef06c3200067d was what I went with, if you don't like it, we can try something else

**Comment by mdz** [comment]
Works for me.

## 
- mdz
