### ISSUE TITLE
Syncing viewers doens't work

### ISSUE THREAD

**Issue by ctide** [LockerProject/Locker#355]
Unable to get any forked viewers to sync up to my singly.com account.

10:21 < ctide> is syncing viewers working for anyone else on prod?
10:22 < mdz> for me, it at least pops up the notification saying it is doing something
10:22 < mdz> I don't have any new viewers to sync in right now
10:22 < ctide> i got the notification, yeah, but
10:22 < ctide> i forked jer's viewer he emailed about
10:22 < ctide> and it's not showing up
10:30 < erictj> ctide: haven't tried.  trying in a sec
10:33 < quartzjer> ctide: have you tried any others? there was a problem w/ the linkvid one but I (thought I) fixed it last night, but just in case maybe try another
10:34 < ctide> i'll try snowstack
10:35 < ctide> not sure how long it should take, but that's not showing up either
10:38 < mdz> ctide, quartzjer's new viewer isn't syncing for me either
10:38 < mdz> LinkVid, that is
10:39 < ctide> how about snowstack
10:39 < ctide> does that one sync for you?
10:39 < mdz> whose account is that on?
10:39 < ctide> jers
10:39 < ctide> or really, any viewer
10:39 < ctide> could fork one of the main ones
10:40 < mdz> nothing
10:41 < ctide> i'll make a ticket

**Comment by mdz** [comment]
Testing locally. I forked two viewers (linkvid and snowstack). linkvid has come in, but not snowstack yet.

**Comment by mdz** [comment]
<smurthas> ctide, i found the bug yesterday
 didn't push the fix yet
 it's simple

**Comment by smurthas** [comment]
fixed.
