### ISSUE TITLE
analytics should not be hard-coded

### ISSUE THREAD

**Issue by quartzjer** [LockerProject/Locker#357]
move into template or config or dynamically loaded system

**Comment by smurthas** [comment]
@quartzjer, is this still an issue - if so we should definitely handle it soon.

**Comment by quartzjer** [comment]
ga.js is in https://github.com/LockerProject/Locker/tree/master/Apps/DevDocs/static/js and https://github.com/LockerProject/Locker/tree/master/Apps/UseUI/static/js and included by both (is it even used?). this should get cleaned up as part of the next analytics story.

**Comment by quartzjer** [comment]
this isn't relevant anymore :)
