### ISSUE TITLE
API calls to /Me/foo redirects to /Me/foo/ and breaks

### ISSUE THREAD

**Issue by quartzjer** [LockerProject/Locker#360]
/foooo/Me/bar redirects to /Me/bar/ and breaks any prefix

**Comment by ctide** [comment]
Can you give an example of where this breaks?  Hitting any of the apps, such as: http://localhost:8042/Me/photosv09 redirects and works fine.  What prefixes are ever used?

**Comment by quartzjer** [comment]
Sorry should have in the original, https://api.singly.com/***/Me/photosv09

**Comment by merc3po** [comment]
Is this still an issue after imthemap?

**Comment by quartzjer** [comment]
Yeah, it's a Location: header that the proxy spits back with the full domain being incorrect for api calls, not sure how best to fix it yet but it's also not blocking anything, just an edge case.
