### ISSUE TITLE
Places Collection Support

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#363]
Feature request for Places collection support:
- Latitude Synclet code pull and merge
- Support for places from geolocated tweets, flickr photos etc
- Support for querying places 'nearby' in the API, IE: get places in the locker where the distance from a (lat,long) is equal to, larger than, smaller than etc.

**Comment by temas** [comment]
Moved to http://getsatisfaction.com/singly/topics/places_collection_support
