### ISSUE TITLE
Dedup Miss

### ISSUE THREAD

**Issue by temas** [LockerProject/Locker#368]
I don't have logs or anything, but an obvious dedup miss.

https://dl.dropbox.com/u/1362507/Captured/lghe5.png

**Comment by ctide** [comment]
I think this is due to middle name / middle initial.  I had one of these in my locker too for a friend that occasionally uses their middle initial

**Comment by ctide** [comment]
Guess not, in my case it shows the middle initial:

http://imageshar.es/4ea6e3e8dab47f3316000267

**Comment by temas** [comment]
I had another one in my locker that was the same case.  All the services on one contact and only gcontact on the dup.

**Comment by mdz** [comment]
Is this still happening with the new contacts collection? /cc @smurthas

**Comment by smurthas** [comment]
While it is certainly possible, I'm going to close this as it is probably not around anymore. If we see it again, of course we can reopen.
