### ISSUE TITLE
Facebook API should show the downloading progress

### ISSUE THREAD

**Issue by tamersaadeh** [LockerProject/Locker#37]
When first initializing the Locker Application with Facebook and finally reach http://localhost:8042/<some_random_string>/friends, it loads an empty page and the terminal shows nothing. Users might think that the application either has crashed or does not actually work; simply useless. However, it actually does work, just not in an obvious way and it keep downloading all the images and other Facebook data in the background.

I suggest that the application implements some sort of progress bar or a method of showing downloaded data as it gets downloaded asynchronously. This way the user will be able to test the API and use the application, while the data is being downloaded.

**Comment by rand** [comment]
Agreed! We're working on improving the UX + DX right now. Ideas and contributions highly encouraged! Thanks.

**Comment by ctide** [comment]
We have a story in our backlog for showing state across all of the data sync routines.  I'm going to close this issue out in lieu of that work, which is queued up to be done in the next few months.
