### ISSUE TITLE
Need to handle someone de-authorizing a service

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#371]
Today, if I go to Facebook and remove access from Singly, Singly doesn't notice that I've done so. There's no way to get it back to a sane state.

**Comment by ctide** [comment]
This needs to be handled as part of the larger synclet-auth story that's currently floating through the technical debt spreadsheet.

**Comment by merc3po** [comment]
+1

**Comment by smurthas** [comment]
There are some stranded accounts on Singly production that have bad gcontacts auths. These need to be forced to re-auth when this is fixed.

**Comment by merc3po** [comment]
@othiym23 you should be able to close this when you're done with #613

**Comment by othiym23** [comment]
Yep, this is definitely part of the scope of #613.

**Comment by merc3po** [comment]
Since this is covered in #613 I'm closing it.
