### ISSUE TITLE
the /providers endpoint leaks auth data

### ISSUE THREAD

**Issue by garyp** [LockerProject/Locker#386]
Not urgent, but /providers probably shouldn't show auth data to Locker apps. For example, an excerpt of what http://localhost:8042/providers?types=contact returns:

...
{
    "title": "Twitter Account",
    "status": "waiting",
    "provider": "twitter",
    "provides": [
      "contact/twitter",
      "mentions/twitter",
      "related/twitter",
      "timeline/twitter",
      "tweets/twitter"
    ],
   ...
    "srcdir": "Connectors/Twitter",
    "authurl": "http://localhost:8042/auth/twitter/auth",
    "auth": {
      "consumerKey": "XXX",
      "consumerSecret": "XXX",
      "token": {
        "oauth_token": "XXX",
        "oauth_token_secret": "XXX"
      }
    },
    "id": "twitter",
    ...
  },
...

**Comment by quartzjer** [comment]
nice catch, thanks!

**Comment by smurthas** [comment]
for reference, similar (and probably related) to #379

**Comment by temas** [comment]
This actually deletes the auth off of the real objects.  Another fix shortly.
