### ISSUE TITLE
if a synclet doesn't finish, it hangs forever

### ISSUE THREAD

**Issue by quartzjer** [LockerProject/Locker#387]
Need a timer/timeout to kill it after some amount of time.

**Comment by ctide** [comment]
I don't think we ever really know how long a synclet would take to finish.  We can certainly speculate, but this could be disasterous (such as in the case of a new user with a massive amount of data in one service) and killing off the synclet would cause it to just do the same thing again the next time it runs.  Is there a synclet that's occasionally not finishing?  If so, we should fix that!

**Comment by quartzjer** [comment]
I've had a 4sq one get stuck for a day, it was likely a bum http request in some unknown state... Agree on the not-knowing-when being a real problem, I think the request module given a timeout might help too if that's the case.

I think for all the _existing_ synclets that there's a reasonable upper bound, at most 30 minutes maybe as a default, but could be overridden in the manifest?

**Comment by smurthas** [comment]
That sounds reasonable to me. +1.
