### ISSUE TITLE
locker crash during event processing

### ISSUE THREAD

**Issue by garyp** [LockerProject/Locker#391]
my locker just crashed and restarted with the following error log:

30 Oct 17:27:05 - info: Synclet tweets starting for twitter
30 Oct 17:27:06 - info: Synclet tweets finished for twitter
30 Oct 17:27:06 - info: processing synclet data from tweets of length 0
30 Oct 17:27:07 - info: proxying GET /socket.io/1/jsonp-polling/12210534211910246725?t=1320010027811&i=601 to http://localhost:18043//socket.io/1/jsonp-polling/12210534211910246725?t=1320010027811&i=601
30 Oct 17:27:22 - info: Synclet timeline starting for twitter
30 Oct 17:27:24 - info: Synclet timeline finished for twitter
30 Oct 17:27:24 - info: processing synclet data from timeline of length 1
30 Oct 17:27:24 - debug: Firing an event for timeline/twitter from twitter action(update)
30 Oct 17:27:24 - debug: Firing event to links to /events
30 Oct 17:27:24 - debug: Firing event to places to /events
30 Oct 17:27:24 - debug: Firing event to search to /events
30 Oct 17:27:24 - error: { stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'EPIPE, Broken pipe',
  errno: 32,
  code: 'EPIPE',
  syscall: 'write' }
30 Oct 17:27:24 - error: 'Error: EPIPE, Broken pipe\n    at Socket._writeImpl (net.js:159:14)\n    at Socket._writeOut (net.js:450:25)\n    at Socket.write (net.js:377:17)\n    at ClientRequest._writeRaw (http.js:392:28)\n    at ClientRequest._send (http.js:372:15)\n    at ClientRequest.end (http.js:696:18)\n    at Object.makeRequest (/home/gary/files/software/lockerbox/Locker/Common/node/levents.js:43:9)\n    at /home/gary/files/software/lockerbox/Locker/Common/node/levents.js:112:21\n    at Array.forEach (native)\n    at processEvents (/home/gary/files/software/lockerbox/Locker/Common/node/levents.js:94:28)'
30 Oct 17:27:24 - info: Killing running service contacts at pid 27943
30 Oct 17:27:24 - info: Killing running service useui at pid 27938
30 Oct 17:27:24 - info: Killing running service links at pid 27945
30 Oct 17:27:24 - info: Killing running service places at pid 27967
30 Oct 17:27:24 - info: Killing running service search at pid 27970
30 Oct 17:27:24 - info: Killing running service photos at pid 27942
30 Oct 17:27:24 - info: contacts is still running, cannot complete shutdown.
30 Oct 17:27:24 - info: useui process has ended. (1:null)
30 Oct 17:27:24 - info: contacts is still running, cannot complete shutdown.
30 Oct 17:27:24 - info: contacts process has ended. (1:null)
30 Oct 17:27:24 - info: links is still running, cannot complete shutdown.
30 Oct 17:27:24 - info: photos process has ended. (1:null)
30 Oct 17:27:24 - info: links is still running, cannot complete shutdown.
30 Oct 17:27:24 - info: places process has ended. (1:null)
30 Oct 17:27:24 - info: links is still running, cannot complete shutdown.
30 Oct 17:27:24 - info: search process has ended. (1:null)
30 Oct 17:27:24 - info: links is still running, cannot complete shutdown.
warn: Forever detected script exited with code: 1
warn: Forever restarting script for 1 time

**Comment by smurthas** [comment]
Are you able to reproduce this?

**Comment by garyp** [comment]
It hasn't happened again and I don't know how to reproduce it. I reported it in case the stack trace pointed at some obvious bug. If it doesn't then feel free to close this.

**Comment by smurthas** [comment]
nothing jumped out, so I'm going to close. thanks!
