### ISSUE TITLE
Search box drop down.

### ISSUE THREAD

**Issue by temas** [LockerProject/Locker#392]
If you set your browser smaller than a certain minimum width the search box can fall under the header.

**Comment by temas** [comment]
![Example](http://dl.dropbox.com/u/1362507/Singly/Singly.jpg)

**Comment by jsmecham** [comment]
I'll take care of this today.

**Comment by smurthas** [comment]
@ctide, assigned to you to ensure that this gets fixed in the new UI, not the old one. (wontfix for UseUI)

**Comment by ctide** [comment]
Fixed in new ui
