### ISSUE TITLE
lure/Error: page.should have_content('Make your own viewer!') (racy test?)

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#402]
/home/mdz/.rvm/rubies/ruby-1.8.7-p352/bin/ruby -S rspec ./spec/integration/dashboard_spec.rb
..F.

Failures:

  1) dashboard should allow access to api explorer
     Failure/Error: page.should have_content('Make your own viewer!')
       expected there to be content "Make your own viewer!" in "Contacts\nPeople\nJeremie Miller\nEmail\nFoursquare Profile\nGitHub Profile\nNobody Selected"
     # ./spec/integration/dashboard_spec.rb:33
     # ./spec/integration/dashboard_spec.rb:32

Finished in 10.08 seconds
4 examples, 1 failure

Failed examples:

rspec ./spec/integration/dashboard_spec.rb:29 # dashboard should allow access to api explorer
rake aborted!
ruby /home/mdz/.rvm/rubies/ruby-1.8.7-p352/bin/ruby -S rspec ./spec/integration/dashboard_spec.rb failed

Tasks: TOP => default => spec
(See full trace by running task with --trace)
'vows process exited abnormally (code=1, signal=null)'

**Comment by ctide** [comment]
I fixed this one
