### ISSUE TITLE
Racy tests?

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#406]
Lot's of errors, that went away when I ran it the third time. I am on latest master.

First two runs: https://gist.github.com/1352885

**Comment by smurthas** [comment]
As of latest today - I still get these on the first few runs of the tests.

**Comment by merc3po** [comment]
Where are we at on this? Is @kristjan covering this?

**Comment by amcjen** [comment]
We've changed tests so much since this was opened, I'd mark this for close.

**Comment by smurthas** [comment]
I haven't seen it in a while and CI has never encountered it, so I'm going to close it
