### ISSUE TITLE
Should log a message when a migration finishes

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#414]
I noticed with the recent places migrations, they sometimes take a while, and appear to be done when they actually aren't yet.

We might also consider some kind of visual indicator in the UI, since account holders may see some weird behavior while a migration is running (e.g. some data not being visible until it finishes)

**Comment by ctide** [comment]
The 'migration' finishes immediately, this isn't really possible with the way we've been doing 'migrations'.

**Comment by mdz** [comment]
Are you saying that it's more work than should be represented as an issue?

**Comment by ctide** [comment]
Yes
