### ISSUE TITLE
First load Sync for google Contact shows only one contact

### ISSUE THREAD

**Issue by gtzilla** [LockerProject/Locker#417]
during initial load on the google data

the app correctly notified me on the right with "628 new contacts" then "500" new contacts until in reached the end of all new contacts to be imported.

The screen then selected one contact, in my case "paulina" and displayed it. The "show all" was not present at the top of the column and there was no indicator or navigation to show all contacts. Reloading the page resolved the issue.

Cannot seem to reproduce it now that my data is imported.

**Comment by othiym23** [comment]
This is semi-expected behavior on import and might be addressed by some upcoming changes to the dashboard, but assigning Jer to take a quick look at it.

**Comment by smurthas** [comment]
this was with the old UI. closing as that has been replaced.
