### ISSUE TITLE
Clicking on "singly" logo in top left doesnt take me home

### ISSUE THREAD

**Issue by gtzilla** [LockerProject/Locker#419]
appears to do nothing, trying to return to "home" sans subviews.

**Comment by temas** [comment]
This is a confusing one because in the hosted environment the expected result is understood, but on the personal locker where does this go?  We need to figure this one out though, because the clicking on the logo has been observed many times.

**Comment by jsmecham** [comment]
Until there is some sort of dashboard or overview of "your" data, this should probably go nowhere (as in, no clickability, no visual cues)...

**Comment by MaxSchultz** [comment]
I was nagging Simon about this tonight too!  A page in this state would make a great placeholder home:

<img src="http://gyazo.com/a4ac5f966cadf6c57e32ea40187cb160.png">

**Comment by merc3po** [comment]
Agreed with jsmecham - there's nowhere for it to take you until we have a dashboard.

**Comment by smurthas** [comment]
@merc3po, assigned to you to ensure it gets "fixed" in the new UI, not the old one.

**Comment by merc3po** [comment]
Check and check! We have notes to support this in the new UI so I'll close this. Thanks everyone. :)
