### ISSUE TITLE
unable to install chrome plugin

### ISSUE THREAD

**Issue by sambirk** [LockerProject/Locker#42]
I'm using ubuntu natty 11.04 with package google-chrome-dev

The plugin locker-browser-history.crx downloads fine and show in folder

Drop onto chrome to install 
click "Are you sure you want to continue" 
I get a popup in chrome with the error

```
Extension Installation Error
Package is invalid: 
'CRX_EXCESSIVELY_LARGE_KEY_OR_SIGNATURE'.
```

**Comment by smurthas** [comment]
This code has been deprecated.
