### ISSUE TITLE
Mobile: Cannot sign in

### ISSUE THREAD

**Issue by gtzilla** [LockerProject/Locker#424]
Using android browser, the sign in button doesn't open any dialogue box to signin.

works normally in chrome using url: https://singly.com

**Comment by MaxSchultz** [comment]
You can use media-queries in the stylesheet to hide the sign in toggle and show the sign in box outright or use a simpler toggle/effect.

**Comment by smurthas** [comment]
Thanks! Moving this to a singly.com repo as it isn't a Locker issue.
