### ISSUE TITLE
Places migration is not working

### ISSUE THREAD

**Issue by amcjen** [LockerProject/Locker#427]
Tried twice, and places migration craps out for some reason.  Only takes new events, does not fetch old ones.  

Manually running /Me/places/update

**Comment by amcjen** [comment]
Update:  Chris mentioned the production box was chomping away.  It's possible this migration just takes a few hours.

**Comment by smurthas** [comment]
@erictj, is this still open?

**Comment by amcjen** [comment]
Yes, this is no longer an issue.  Jer updated the handling to be synchronous
