### ISSUE TITLE
Add "Develop" tab to me.singly.com

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#429]
We need a tab on the me.singly.com called "Develop". (Left to right the site should read: Photos, Contacts, Links, Places, Develop)

Within the dropdown menu of that tab should be at least the following options: 
"Creating a viewer" - Links to https://me.singly.com/Me/devdocs/
"Developing locally" - LInks to https://me.singly.com/Me/devdocs/local.html
"API Explorer" - Links to https://me.singly.com/Me/devdocs/explorer.html
"Community" - Links to https://github.com/LockerProject/Locker/wiki/Viewers

**Comment by MaxSchultz** [comment]
Given the context - I would expect a Docs link to show my own personal Google docs, pdf files etc. Maybe a Docs link with a developer tool icon?  Call it 'Develop' or 'Build' ?

**Comment by merc3po** [comment]
Ah, I hear you. The context of the tabs are going to change as part of a larger epic I'm working on currently. We'll be changing to a UI that's better suited to browsing and creating viewers. This would include a tab for "Documentation," which is the naming convention for platforms. I meant Docs to be an easily actionable stop-gap between the current state (hard to find documentation) and the future state (super easy!) but I see what you mean about the current context...

That said, "Develop" would work for the name of the tab. Just thought I'd also share the thought process. :-) Thanks, Max!

**Comment by smurthas** [comment]
I felt had the same intuition as Max when I saw this in my inbox. I also super, duper feel the need for a stop gap -- I think we could use "Develop" and put it over in the location it currently is and that would solve both problems (for now).

**Comment by MaxSchultz** [comment]
Would love a quickfire Sync Your Viewer option in here

**Comment by smurthas** [comment]
Yes, that would be great -- it could take the form of a dropdown (similar to one of the types we already have) that has:
1. Create a Viewer
2. API Explorer
3. Sync Your Viewers
4. All Viewers List (the wiki doc)

Again, a stopgap to a full UI rework/revisit, but probably super low hanging fruit to improve the situation.
