### ISSUE TITLE
Add favicon to singly.com

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#432]
We're missing a favicon. Please add this one to the site: http://dl.dropbox.com/u/25985358/favicon.ico

**Comment by ctide** [comment]
Fixed in integral

**Comment by mdz** [comment]
I filed this a while back, and ctide added the favicon on 18 October. Are you still not seeing it somewhere on the site?

https://github.com/Singly/integral/issues/34

**Comment by ctide** [comment]
It was not showing up when you were being proxied to the locker

**Comment by mdz** [comment]
Interesting, it shows up for me on https://me.singly.com/dashboard/. Maybe because I got there from singly.com?

**Comment by ctide** [comment]
When I load: https://me.singly.com/favicon.ico I just get redirected to my dashboard, and the site has no favicon

**Comment by merc3po** [comment]
Yeah I also get there from singly.com.

On Mon, Nov 14, 2011 at 1:58 PM, Chris Burkhart <
reply@reply.github.com

> wrote:
> 
> When I load: https://me.singly.com/favicon.ico I just get redirected to
> my dashboard, and the site has no favicon
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/LockerProject/Locker/issues/432#issuecomment-2737315

## 

Merci Victoria Grace

Playful Designer + Producer

http://artserf.net
http://linkedin.com/in/merci
http://twitter.com/merci
