### ISSUE TITLE
/Me/links endpoint fields param exhibits strange behavior

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#435]
The fields param on the /Me/links endpoint doesn't quite seem to be working for encounters. For instance, you would expect the following query to return only the encounters array and within that only the from field for each encounter:

http://localhost:8042/Me/links/?limit=10&fields={"encounters.from":1}&full=true

Instead if returns a bunch of empty encounters arrays:

```
[{
    "_id": "4ec173acd6ffe6fc6da3964a",
    "encounters": []
},
{
    "_id": "4ec17338d6ffe6fc6da39644",
    "encounters": []
},
{
    "_id": "4ec172c3d6ffe6fc6da39640",
    "encounters": []
},
...
```

Additionally, a query to

http://localhost:8042/Me/links/?limit=10&fields={"from":1, "link":1}&full=true

will return something closer to the desired result:

```
[{
    "_id": "4ec173acd6ffe6fc6da3964a",
    "link": "http://gartner.mediasite.com/mediasite/play/9cfe6bba5c7941e09bee95eb63f769421d?t=1320659595",
    "encounters": [{
        "_id": "4ec173acd6ffe6fc6da3964b",
        "from": "chris dixon",
        "link": "http://gartner.mediasite.com/mediasite/play/9cfe6bba5c7941e09bee95eb63f769421d?t=1320659595"
    },
    {
        "_id": "4ec1749ed6ffe6fc6da39652",
        "from": "Steve Schlafman",
        "link": "http://gartner.mediasite.com/mediasite/play/9cfe6bba5c7941e09bee95eb63f769421d?t=1320659595"
    }]
},
{
    "_id": "4ec17338d6ffe6fc6da39644",
    "link": "http://blog.vaultpress.com/2011/11/14/announcing-multisite-support/",
    "encounters": [{
        "_id": "4ec17338d6ffe6fc6da39645",
        "from": "Toni Schneider",
        "link": "http://blog.vaultpress.com/2011/11/14/announcing-multisite-support/"
    }]
},
...
```

However, a query to http://localhost:8042/Me/links/?limit=10&fields={"from":1}&full=true returns the same a the first result.

**Comment by quartzjer** [comment]
The encounters are only merged in when a link field is present in the links result, accounting for the second oddity... and the fields arg was just re-used as-is for the encounters find, def not ideal and a TODO to figure out how to make that sane (if needed at all).
