### ISSUE TITLE
/map and /available show run fields

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#441]
Nothing other than locker core should need/use this info and it feels like an over-exposure of information. Open for discussion, just wanted to raise the issue.

**Comment by temas** [comment]
There's actually no such thing as overexposure because it only ever goes to you.  I'd like to readdress this after we have architecture conversations this week.

**Comment by merc3po** [comment]
Where are we on this?

**Comment by smurthas** [comment]
/available is gone, /map still returns run field. seems a bit strange for a static app to be able to see all of this, but we can close for the sake of cleanliness and handle in the future if there is a need.
