### ISSUE TITLE
manually updated places / checkins have weird creation dates

### ISSUE THREAD

**Issue by othiym23** [LockerProject/Locker#454]
Fetched http://me.singly.com/Me/places/update to force the update of my places collection, got a huuuuuge pile of events that showed a date in HelloPlaces of sometime today.

**Comment by quartzjer** [comment]
I've not seen/reproduced this, could you check again and maybe grab the actual json returned at https://me.singly.com/Me/places?offset=0&limit=1000&sort=at&order=-1 ?

**Comment by smurthas** [comment]
Which date? Lot's of objects have a timestamp that is whenever the collection encountered the object and a "created_at" date or something like that that is a true creation date.

**Comment by othiym23** [comment]
I'm just going by the date shown in the stock HelloPlaces list viewer. If this is the behavior you guys expect, that's fine, but it surprised me, because I was expecting the date of the checkin / photo / whatever.

**Comment by merc3po** [comment]
Sounds like we can close this? @othiym23?

**Comment by othiym23** [comment]
Yeah, I think this can be put down to me being confused about what happened at place event creation time. Closing.
