### ISSUE TITLE
"All Photos" Text wraps badly

### ISSUE THREAD

**Issue by bassdread** [LockerProject/Locker#460]
Using latest Chrome 15.0.874.121 the text "All Photos" wraps outside the arrow see https://me.singly.com/dashboard/#photos

**Comment by bassdread** [comment]
http://chrishannam.co.uk/All_Photos_Text_Overrun.png shows the issue.

**Comment by mdz** [comment]
Doesn't happen for me with Ubuntu 11.10 and Chromium 14.0.835.202

**Comment by temas** [comment]
Verified if the browser font is set larger than default.  It needs a specific font size set on the element.
