### ISSUE TITLE
UI greys out when backend goes away

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#461]
If the locker is killed while the UI is open, the overlay appears and sometimes shows the welcome dialog.

**Comment by ctide** [comment]
Dupe of #446

**Comment by ctide** [comment]
Not a dupe of #446

**Comment by smurthas** [comment]
:)

**Comment by smurthas** [comment]
@ctide, assigned to you to make sure this gets fixed with the new UI, not the old one.

**Comment by ctide** [comment]
fixed in new UI
