### ISSUE TITLE
Photos timeline viewer not showing all photos

### ISSUE THREAD

**Issue by temas** [LockerProject/Locker#470]
My collection shows that I have 50 photos and they are all viewable inside of the masonry viewer.  When I switch to timeline I only have 20 total available.

**Comment by othiym23** [comment]
Simon, you've done the most work on the photos collection -- feel free to pass the potato if you think it doesn't make sense.

**Comment by smurthas** [comment]
This is an easy fix to the timeline viewer. I'll fix it this week!

**Comment by smurthas** [comment]
This is fixed on both my local machine and my singly account. If you see this on local development, make sure to do:

```
git submodule update
```
