### ISSUE TITLE
[search] TypeError: Cannot call method 'substr' of undefined

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#473]
I entered "occupy" in the search box, saw a Places result for "Occupy SF" and clicked on it. I got the places viewer with a red marker at a different location, and these errors in the log:

30 Nov 12:55:08 - info: search started at pid 7184, running startup callbacks.
[search] querying place\* for occu*
[search] querying contact\* for occupy*
[search] querying timeline/twitter\* for occupy*
querying place\* for occupy*
[search] querying photo\* for occupy*
[photos] [object Object]
[search] 30 Nov 12:55:08 - error: Received a 500 when attempting to enrich search results from http://localhost:8042/Me/photos/id/cc358465d66332b518864fe9ea6ef0edb251dae5
[search] 
[search] node.js:134
[search]         throw e; // process.nextTick error, or 'error' event on first tick
[search]         [search] ^
[search] TypeError: Cannot call method 'substr' of undefined
    at /home/mdz/src/singly/Locker/Collections/Search/search.js:337:88
    at /home/mdz/src/singly/Locker/node_modules/async/lib/async.js:118:13
    at Object.forEachSeries (/home/mdz/src/singly/Locker/node_modules/async/lib/async.js:134:9)
    at /home/mdz/src/singly/Locker/Collections/Search/search.js:333:19
    at /home/mdz/src/singly/Locker/node_modules/async/lib/async.js:484:34
    at Array.<anonymous> (/home/mdz/src/singly/Locker/node_modules/async/lib/async.js:408:34)
    at EventEmitter._tickCallback (node.js:126:26)
30 Nov 12:55:08 - info: search process has ended. (1:null)

**Comment by quartzjer** [comment]
I'm fixing the crash that manifests the issue, but the real problem is search collection needs reindexing, which is a pretty moot point until #320 is fixed.

**Comment by othiym23** [comment]
This is going to be addressed by the rewrite, so leaving it with Jer.
