### ISSUE TITLE
Registry Test Failures

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#474]
I get this every so often:

```
♢ Registry

FAKEWEB: Unhandled GET request to http://registry.singly.com/-/all/since?stale=update_after&startkey=1322508323216
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
^C
```

**Comment by smurthas** [comment]
This makes it hard to run tests fairly often - making a priority (I'd imagine it will also cause CI to fail)

**Comment by quartzjer** [comment]
I think this was fixed but never closed, I've not seen it again, we can re-open if it's reproducible or happens again...
