### ISSUE TITLE
github connector api limit easily hit

### ISSUE THREAD

**Issue by quartzjer** [LockerProject/Locker#477]
API Rate Limit Exceeded for 107.20.214.94

Not sure why it's IP based and not key but it's happening :(

**Comment by smurthas** [comment]
Is this a dupe of https://github.com/LockerProject/Locker/issues/312 ?

**Comment by quartzjer** [comment]
Fixed using v3! https://github.com/LockerProject/Locker/commit/548438fa9ae59324453dcea43f8d89eb52e8dcc5
