### ISSUE TITLE
Connector code should be deprecated

### ISSUE THREAD

**Issue by amcjen** [LockerProject/Locker#479]
During the hackathon, the extraneous code in the foursquare connector made it confusing to developers where they should put new extensions to functionality.  

Let's get rid of old connector code for connectors that are clearly synclet-based now.

**Comment by mdz** [comment]
This is on the board as "deal with dormant locker code"

**Comment by amcjen** [comment]
Ahh, perfect.

**Comment by quartzjer** [comment]
I've been picking away at this in connector directories where there's mixed old and new code, but I'm not super comfortable yet removing all the older connectors entirely, just fyi, making progress!

**Comment by quartzjer** [comment]
all of the connectors that have synclets and package.json's are now cleansed of old unused code :)
