### ISSUE TITLE
TypeError: Cannot read property 'etag' of undefined (when running tests)

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#480]
♢ Registry

  Can init
    ✓ successfully
  Haz Apps
    ✓ successfully
'TypeError: Cannot read property \'etag\' of undefined\n    at Request._callback (/home/mdz/src/singly/Locker/node_modules/npm/lib/utils/npm-registry-client/request.js:167:33)\n    at Request.callback (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:99:22)\n    at Request.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:361:18)\n    at Request.emit (events.js:64:17)\n    at EventEmitter.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:327:16)\n    at EventEmitter.emit (events.js:61:17)\n    at EventEmitter.end (/home/mdz/src/singly/Locker/node_modules/node-fakeweb/fakeweb.js:60:22)\n    at Request.end (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:442:16)\n    at Array.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:412:12)\n    at EventEmitter._tickCallback (node.js:126:26)'
'TypeError: Cannot read property \'etag\' of undefined\n    at Request._callback (/home/mdz/src/singly/Locker/node_modules/npm/lib/utils/npm-registry-client/request.js:167:33)\n    at Request.callback (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:99:22)\n    at Request.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:361:18)\n    at Request.emit (events.js:64:17)\n    at EventEmitter.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:327:16)\n    at EventEmitter.emit (events.js:61:17)\n    at EventEmitter.end (/home/mdz/src/singly/Locker/node_modules/node-fakeweb/fakeweb.js:60:22)\n    at Request.end (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:442:16)\n    at Array.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:412:12)\n    at EventEmitter._tickCallback (node.js:126:26)'
'TypeError: Cannot read property \'etag\' of undefined\n    at Request._callback (/home/mdz/src/singly/Locker/node_modules/npm/lib/utils/npm-registry-client/request.js:167:33)\n    at Request.callback (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:99:22)\n    at Request.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:361:18)\n    at Request.emit (events.js:64:17)\n    at EventEmitter.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:327:16)\n    at EventEmitter.emit (events.js:61:17)\n    at EventEmitter.end (/home/mdz/src/singly/Locker/node_modules/node-fakeweb/fakeweb.js:60:22)\n    at Request.end (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:442:16)\n    at Array.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:412:12)\n    at EventEmitter._tickCallback (node.js:126:26)'
'TypeError: Cannot read property \'etag\' of undefined\n    at Request._callback (/home/mdz/src/singly/Locker/node_modules/npm/lib/utils/npm-registry-client/request.js:167:33)\n    at Request.callback (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:99:22)\n    at Request.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:361:18)\n    at Request.emit (events.js:64:17)\n    at EventEmitter.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:327:16)\n    at EventEmitter.emit (events.js:61:17)\n    at EventEmitter.end (/home/mdz/src/singly/Locker/node_modules/node-fakeweb/fakeweb.js:60:22)\n    at Request.end (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:442:16)\n    at Array.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:412:12)\n    at EventEmitter._tickCallback (node.js:126:26)'
'TypeError: Cannot read property \'etag\' of undefined\n    at Request._callback (/home/mdz/src/singly/Locker/node_modules/npm/lib/utils/npm-registry-client/request.js:167:33)\n    at Request.callback (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:99:22)\n    at Request.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:361:18)\n    at Request.emit (events.js:64:17)\n    at EventEmitter.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:327:16)\n    at EventEmitter.emit (events.js:61:17)\n    at EventEmitter.end (/home/mdz/src/singly/Locker/node_modules/node-fakeweb/fakeweb.js:60:22)\n    at Request.end (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:442:16)\n    at Array.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:412:12)\n    at EventEmitter._tickCallback (node.js:126:26)'
'TypeError: Cannot read property \'etag\' of undefined\n    at Request._callback (/home/mdz/src/singly/Locker/node_modules/npm/lib/utils/npm-registry-client/request.js:167:33)\n    at Request.callback (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:99:22)\n    at Request.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:361:18)\n    at Request.emit (events.js:64:17)\n    at EventEmitter.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:327:16)\n    at EventEmitter.emit (events.js:61:17)\n    at EventEmitter.end (/home/mdz/src/singly/Locker/node_modules/node-fakeweb/fakeweb.js:60:22)\n    at Request.end (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:442:16)\n    at Array.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:412:12)\n    at EventEmitter._tickCallback (node.js:126:26)'
'TypeError: Cannot read property \'etag\' of undefined\n    at Request._callback (/home/mdz/src/singly/Locker/node_modules/npm/lib/utils/npm-registry-client/request.js:167:33)\n    at Request.callback (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:99:22)\n    at Request.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:361:18)\n    at Request.emit (events.js:64:17)\n    at EventEmitter.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:327:16)\n    at EventEmitter.emit (events.js:61:17)\n    at EventEmitter.end (/home/mdz/src/singly/Locker/node_modules/node-fakeweb/fakeweb.js:60:22)\n    at Request.end (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:442:16)\n    at Array.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:412:12)\n    at EventEmitter._tickCallback (node.js:126:26)'
'TypeError: Cannot read property \'etag\' of undefined\n    at Request._callback (/home/mdz/src/singly/Locker/node_modules/npm/lib/utils/npm-registry-client/request.js:167:33)\n    at Request.callback (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:99:22)\n    at Request.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:361:18)\n    at Request.emit (events.js:64:17)\n    at EventEmitter.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:327:16)\n    at EventEmitter.emit (events.js:61:17)\n    at EventEmitter.end (/home/mdz/src/singly/Locker/node_modules/node-fakeweb/fakeweb.js:60:22)\n    at Request.end (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:442:16)\n    at Array.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:412:12)\n    at EventEmitter._tickCallback (node.js:126:26)'
'TypeError: Cannot read property \'etag\' of undefined\n    at Request._callback (/home/mdz/src/singly/Locker/node_modules/npm/lib/utils/npm-registry-client/request.js:167:33)\n    at Request.callback (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:99:22)\n    at Request.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:361:18)\n    at Request.emit (events.js:64:17)\n    at EventEmitter.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:327:16)\n    at EventEmitter.emit (events.js:61:17)\n    at EventEmitter.end (/home/mdz/src/singly/Locker/node_modules/node-fakeweb/fakeweb.js:60:22)\n    at Request.end (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:442:16)\n    at Array.<anonymous> (/home/mdz/src/singly/Locker/node_modules/npm/node_modules/request/main.js:412:12)\n    at EventEmitter._tickCallback (node.js:126:26)'

**Comment by amcjen** [comment]
Still an issue Matt?  If not, let's mark it as OPT-CLOSE

**Comment by mdz** [comment]
I haven't seen it since, and it happened when running the test suite, so it's probably fixed. The test suite is about to become much more deterministic as well. :-)

**Comment by temas** [comment]
I've spent a fair deal of time inside the testing and haven't seen it.  Motion to close.
