### ISSUE TITLE
Twitter friends error:	failed to find remaining users

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#487]
5 Dec 13:29:01 - info: Synclet locations finished for glatitude
5 Dec 13:29:24 - info: Synclet friends starting for twitter
5 Dec 13:29:32 - info: Synclet recent starting for foursquare
5 Dec 13:29:33 - error: Twitter friends error:  failed to find remaining users
synclet returned an error: "failed to find remaining users"

5 Dec 13:29:33 - info: Synclet friends finished for twitter
5 Dec 13:29:33 - info: processing synclet data from contact://twitter/contact?id=twitter of length 235

**Comment by quartzjer** [comment]
This is when the twitter api doesn't return all the users, a recent bug on their side. Nothing we can do about it other than complain :/ (I've already sent it to the twitter api team too).
