### ISSUE TITLE
Merged Contacts Viewer page not marked UTF-8

### ISSUE THREAD

**Issue by josephboyle** [LockerProject/Locker#49]
The contacts page contained UTF-8 data but initially displayed incorrectly as ISO-8859-1 until I manually changed encoding from the browser menu. The page needs to have an HTTP header (e.g. Content-Type: text/html; charset=UTF-8) or META tag to specify UTF-8.

**Comment by josephboyle** [comment]
Looks like it could be added in Apps/MergedContacts/contacts.js:98
    res.writeHead(200, { 'Content-Type': 'text/html' });
Looking through the rest of the Locker code, charset is variously stated as utf8, utf-8, or UTF-8. It looks like all work but UTF-8 is canonical: http://en.wikipedia.org/wiki/UTF-8#Official_name_and_variants

**Comment by nym** [comment]
I just did a rewrite of the Merged Contacts Viewer. Can you tell me if this is still relevant?

**Comment by amcjen** [comment]
Updated the locker codebase to standardize on UTF-8 for all HTML/JS encoding, and utf8 for all serverside code, per Node.js docs.
