### ISSUE TITLE
Sign-up button on Singly.com not working

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#490]
A dev I let into Singly today let me know that the sign-up button wasn't working. His email is chad@____.__. He fwd-ed me the email that we generated with his invite.

**Comment by smurthas** [comment]
removed the link as i think it might not expire and obfuscated his email. :).

**Comment by smurthas** [comment]
AFAICT, this was a one time incident that had nothing to do with Locker code. Closing - if this happens again it will likely make more sense in relation to one of our hosting platform repos.
