### ISSUE TITLE
Test failure: dashboard should show a Gritter notification should show a close button when hovering over it 

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#492]
/home/mdz/.rvm/rubies/ruby-1.8.7-p352/bin/ruby -S rspec ./spec/integration/dashboard_spec.rb
......F

Failures:

  1) dashboard should show a Gritter notification should show a close button when hovering over it
     Failure/Error: page.execute_script(<<"BLORF")
     Selenium::WebDriver::Error::UnhandledError:
       Script execution failed. Script:     socket.$events.viewer({
              type:'view/github',
              via:'github',
              timestamp:1320881456139,
              action:'update',
              obj:{
                 source:'github_view',
                 data:{
                    id:'smurthas/Skeleton-Viewer',
                    manifest:'smurthas/Skeleton-Viewer/manifest.app',
                    at:'2011/11/09 15:23:33 -0800',
                    viewer:'photos',
                    _id:'4ebb0ce297e5172111034f6b'
                 }
              }
           });
       ;
        data is not defined
       Backtrace:
        0x43f80e
        0x4320ae
        0x4327e1
        0x41fd42
        0x42c843
        0x41b397
        0x484df8
        0x4861f2
        0x486491
        start_thread [0x7f55d68eeefc]
        0x7f55d3f2589d
     # ./spec/integration/dashboard_spec.rb:74

Finished in 11.53 seconds
7 examples, 1 failure

Failed examples:

rspec ./spec/integration/dashboard_spec.rb:71 # dashboard should show a Gritter notification should show a close button when hovering over it
rake aborted!
ruby /home/mdz/.rvm/rubies/ruby-1.8.7-p352/bin/ruby -S rspec ./spec/integration/dashboard_spec.rb failed

Tasks: TOP => default => spec
(See full trace by running task with --trace)

**Comment by othiym23** [comment]
I helped smurthas create this test case in the first place, and I'm explaining the client tests to Singletons, so I'll take this one on.

**Comment by ctide** [comment]
This test got blown away
