### ISSUE TITLE
Old Twitter data

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#495]
Twitter contacts used to pull in the status element for every single friends all the time. We've removed that now, but the old data is still there. We need to write a migration to remove it from the JSON, twitter mongo data, and contacts collection.

**Comment by quartzjer** [comment]
Why?

On Fri, Dec 9, 2011 at 1:54 PM, Simon Murtha-Smith
reply@reply.github.com
wrote:

**Comment by merc3po** [comment]
Is this still an issue?

**Comment by quartzjer** [comment]
I don't think so, I'll close it, can be reopened if it really is :)

**Comment by smurthas** [comment]
all good.
