### ISSUE TITLE
First visit to dashboardv3 shows a screenful of JSON

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#496]
I saw this last week, but wasn't able to reproduce it. It happened to me again over the weekend and I grabbed a screenshot: http://imgur.com/nfoCX

**Comment by ctide** [comment]
I'm going to close this as either some sort of local anomaly, or something weird on your machine.  Reopen if you ever see it again!

**Comment by mdz** [comment]
Boooooo
