### ISSUE TITLE
sorting of apps is odd in Dashboard v3

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#498]
Hey homie -

There appears to be no logic applied to how the apps are being sorted in the left-nav. It was supposed to be 1. bookmarked (which we took out) and then 2. most recently used apps. This isn't either of those (or the most-recently used sorting isn't working) but it isn't alphabetical either. 

Here's an image for reference: https://skitch.com/e-merc3po/gx39a/unsorted

**Comment by amcjen** [comment]
Weird.  It used to sort by most recently used.  

Does it resort correctly to MRU when you refresh the page? 

E.

**Comment by merc3po** [comment]
Oh yeah it does. When do we trigger page refreshes? Will that only be when I'm switching between YOU, EXPLORE, and CREATE?

**Comment by smurthas** [comment]
Yes, it's only on refresh. This important to improve, but I think we can push it off for a few weeks

**Comment by merc3po** [comment]
Roger that. Shall I close this issue and we can make other ones later?

**Comment by ctide** [comment]
It's on refresh intentionally, having those links move around while you're using them would be obnoxious.  Having them move at all felt really weird to me when I was building with it, so we might want to rethink this ordering plan altogether.

**Comment by merc3po** [comment]
Yeah this is why bookmarking was part of the original spec. Having the entire list move around probably does feel weird. I think this is good for now. :) I'll close this and we can re-open it later if we want.
