### ISSUE TITLE
publishing things to the registry complains but seems to work

### ISSUE THREAD

**Issue by ctide** [LockerProject/Locker#499]
13 Dec 13:59:50 - info: publishing /development/Locker/Me/github/ctide/prolific_posters/package.json
npm ERR! prepublish Error: undefined log message
npm ERR! prepublish     at log (/development/Locker/node_modules/npm/lib/utils/log.js:112:11)
npm ERR! prepublish     at lifecycle (/development/Locker/node_modules/npm/lib/utils/lifecycle.js:23:3)
npm ERR! prepublish     at /development/Locker/node_modules/npm/lib/publish.js:36:5
npm ERR! prepublish     at readJson (/development/Locker/node_modules/npm/lib/utils/read-json.js:21:12)
npm ERR! prepublish     at EventEmitter.publish (/development/Locker/node_modules/npm/lib/publish.js:33:3)
npm ERR! prepublish     at Object.<anonymous> (/development/Locker/node_modules/npm/lib/npm.js:193:11)
npm ERR! prepublish     at /development/Locker/Ops/registry.js:245:34
npm ERR! prepublish     at cb (/development/Locker/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:36:9)

**Comment by quartzjer** [comment]
I've not seen this again, possibly fixed in the newer versions of npm.
