### ISSUE TITLE
[searchlite] Empty response when attempting to reindex

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#504]
tutti:[~/scratch/lockerbox/Locker] curl 'http://localhost:8042/Me/search/reindexForType?type=links'
...long delay...
curl: (52) Empty reply from server

15 Dec 13:32:39 - verbose: Normal proxy of /Me/search/reindexForType?type=links
15 Dec 13:32:39 - verbose: proxying GET /Me/search/reindexForType?type=links to http://localhost:18043//reindexForType?type=links
15 Dec 13:32:39 - verbose: Proxy complete
[search] 15 Dec 13:32:40 - info: updating search index for links
15 Dec 13:32:54 - info: Synclet recent starting for foursquare
15 Dec 13:32:55 - info: Synclet recent finished for foursquare
15 Dec 13:33:30 - info: Synclet checkins starting for foursquare
15 Dec 13:33:32 - info: Synclet checkins finished for foursquare
15 Dec 13:33:32 - info: processing synclet data from profile://foursquare/profile?id=foursquare of length 1
15 Dec 13:33:55 - info: Synclet recent starting for foursquare
15 Dec 13:33:55 - info: Synclet recent finished for foursquare
15 Dec 13:34:19 - info: Synclet timeline starting for twitter
15 Dec 13:34:19 - info: Synclet timeline finished for twitter
15 Dec 13:34:19 - info: processing synclet data from tweet://twitter/timeline?id=twitter of length 3
15 Dec 13:34:19 - verbose: Firing an event for tweet://twitter/timeline?id=twitter#147428229303640060 action(update)
15 Dec 13:34:19 - verbose: Firing event to links to /events
15 Dec 13:34:19 - verbose: Firing event to places to /events
15 Dec 13:34:19 - verbose: Firing an event for tweet://twitter/timeline?id=twitter#147428904930508800 action(new)
15 Dec 13:34:19 - verbose: Firing event to links to /events
15 Dec 13:34:19 - verbose: Firing event to places to /events
15 Dec 13:34:19 - verbose: Firing an event for tweet://twitter/timeline?id=twitter#147428661958684670 action(new)
15 Dec 13:34:19 - verbose: Firing event to links to /events
15 Dec 13:34:19 - verbose: Firing event to places to /events
15 Dec 13:34:19 - verbose: proxying POST /Me/links/events to http://localhost:59472//events
15 Dec 13:34:19 - verbose: Proxy complete
15 Dec 13:34:19 - info: Having to spawn places
15 Dec 13:34:19 - info: spawning into: /home/mdz/src/singly/Locker/Me/places
15 Dec 13:34:19 - verbose: sending places startup info of {"port":18045,"sourceDirectory":"/home/mdz/src/singly/Locker/Collections/Places","workingDirectory":"/home/mdz/src/singly/Locker/Me/places","lockerUrl":"http://localhost:8042","externalBase":"https://me.lvh.me:8443/Me/places/","mongo":{"host":"localhost","port":27018,"collections":["place"]}}
15 Dec 13:34:19 - verbose: Proxy complete
15 Dec 13:34:19 - verbose: proxying POST /Me/links/events to http://localhost:59472//events
15 Dec 13:34:19 - verbose: Proxy complete
15 Dec 13:34:19 - info: Having to spawn places
15 Dec 13:34:19 - info: places is still spawning, adding callback to queue.
15 Dec 13:34:19 - verbose: Proxy complete
15 Dec 13:34:19 - verbose: proxying POST /Me/links/events to http://localhost:59472//events
15 Dec 13:34:19 - verbose: Proxy complete
15 Dec 13:34:19 - info: Having to spawn places
15 Dec 13:34:19 - info: places is still spawning, adding callback to queue.
15 Dec 13:34:19 - verbose: Proxy complete
[links] 15 Dec 13:34:19 - verbose: QUEUE SIZE: 0
[links] 15 Dec 13:34:19 - verbose: QUEUE SIZE: 0
15 Dec 13:34:20 - info: Set local uri to http://localhost:34461/ for places
15 Dec 13:34:20 - info: places started at pid 25076, running startup callbacks.
15 Dec 13:34:20 - verbose: proxying POST /Me/places/events to http://localhost:34461//events
15 Dec 13:34:20 - verbose: proxying POST /Me/places/events to http://localhost:34461//events
15 Dec 13:34:20 - verbose: proxying POST /Me/places/events to http://localhost:34461//events
15 Dec 13:34:22 - verbose: Firing an event for link://links/#6c78ec07c2e910cad7ea3a92173f8f09 action(new)
15 Dec 13:34:22 - verbose: Firing event to search to /events
15 Dec 13:34:22 - verbose: proxying POST /Me/search/events to http://localhost:18043//events
15 Dec 13:34:22 - verbose: Proxy complete
[links] 15 Dec 13:34:22 - verbose: QUEUE SIZE: 0
15 Dec 13:34:22 - verbose: Firing an event for link://links/#6c78ec07c2e910cad7ea3a92173f8f09 action(update)
15 Dec 13:34:22 - verbose: Firing event to search to /events
15 Dec 13:34:22 - verbose: proxying POST /Me/search/events to http://localhost:18043//events
15 Dec 13:34:22 - verbose: Proxy complete
[links] 15 Dec 13:34:23 - verbose: QUEUE SIZE: 0
15 Dec 13:34:23 - verbose: Firing an event for link://links/#7708c372085fb1fec10e6ec394fc5ff7 action(new)
15 Dec 13:34:23 - verbose: Firing event to search to /events
15 Dec 13:34:23 - verbose: proxying POST /Me/search/events to http://localhost:18043//events
15 Dec 13:34:23 - verbose: Proxy complete
15 Dec 13:34:23 - verbose: Firing an event for link://links/#7708c372085fb1fec10e6ec394fc5ff7 action(update)
15 Dec 13:34:23 - verbose: Firing event to search to /events
15 Dec 13:34:23 - verbose: proxying POST /Me/search/events to http://localhost:18043//events
15 Dec 13:34:23 - verbose: Proxy complete
15 Dec 13:34:35 - info: Synclet tweets starting for twitter
15 Dec 13:34:36 - info: Synclet tweets finished for twitter
15 Dec 13:34:54 - info: Synclet recent starting for foursquare
15 Dec 13:34:55 - info: Synclet recent finished for foursquare
15 Dec 13:35:34 - info: Synclet profile starting for github
15 Dec 13:35:35 - info: Synclet profile finished for github
15 Dec 13:35:35 - info: processing synclet data from profile://github/profile?id=github of length 1
15 Dec 13:35:36 - info: Synclet checkins starting for foursquare
15 Dec 13:35:37 - info: Synclet checkins finished for foursquare
15 Dec 13:35:37 - info: processing synclet data from profile://foursquare/profile?id=foursquare of length 1
15 Dec 13:35:55 - info: Synclet recent starting for foursquare
15 Dec 13:35:56 - info: Synclet recent finished for foursquare
15 Dec 13:36:19 - info: Synclet timeline starting for twitter
15 Dec 13:36:20 - info: Synclet timeline finished for twitter
15 Dec 13:36:20 - info: processing synclet data from tweet://twitter/timeline?id=twitter of length 3
15 Dec 13:36:20 - verbose: Firing an event for tweet://twitter/timeline?id=twitter#147429777651941380 action(new)
15 Dec 13:36:20 - verbose: Firing event to links to /events
15 Dec 13:36:20 - verbose: Firing event to places to /events
15 Dec 13:36:20 - verbose: Firing an event for tweet://twitter/timeline?id=twitter#147429414613946370 action(new)
15 Dec 13:36:20 - verbose: Firing event to links to /events
15 Dec 13:36:20 - verbose: Firing event to places to /events
15 Dec 13:36:20 - verbose: proxying POST /Me/links/events to http://localhost:59472//events
15 Dec 13:36:20 - verbose: Proxy complete
[links] 15 Dec 13:36:20 - verbose: QUEUE SIZE: 0
15 Dec 13:36:20 - verbose: proxying POST /Me/places/events to http://localhost:34461//events
15 Dec 13:36:20 - verbose: Proxy complete
15 Dec 13:36:20 - verbose: proxying POST /Me/links/events to http://localhost:59472//events
15 Dec 13:36:20 - verbose: Proxy complete
[links] 15 Dec 13:36:20 - verbose: QUEUE SIZE: 0
15 Dec 13:36:20 - verbose: proxying POST /Me/places/events to http://localhost:34461//events
15 Dec 13:36:20 - verbose: Proxy complete
[links] 15 Dec 13:36:21 - verbose: QUEUE SIZE: 0
15 Dec 13:36:21 - verbose: Firing an event for link://links/#cf0c944f6dcb5a2e70afff70995f8315 action(update)
15 Dec 13:36:21 - verbose: Firing event to search to /events
15 Dec 13:36:21 - verbose: Firing an event for link://links/#cf0c944f6dcb5a2e70afff70995f8315 action(new)
15 Dec 13:36:21 - verbose: Firing event to search to /events
15 Dec 13:36:21 - verbose: proxying POST /Me/search/events to http://localhost:18043//events
15 Dec 13:36:21 - verbose: Proxy complete
15 Dec 13:36:22 - error: There was an error sending an event to search at /events got Error: socket hang up
15 Dec 13:36:22 - error: There was an error sending an event to search at /events got Error: socket hang up
15 Dec 13:36:22 - verbose: proxying POST /Me/search/events to http://localhost:18043//events
15 Dec 13:36:22 - verbose: Proxy complete
15 Dec 13:36:23 - error: There was an error sending an event to search at /events got Error: socket hang up
15 Dec 13:36:23 - error: There was an error sending an event to search at /events got Error: socket hang up
[links] 15 Dec 13:36:25 - verbose: QUEUE SIZE: 0
15 Dec 13:36:25 - verbose: Firing an event for link://links/#f60b22be86e1a07ce400a0714c5666d5 action(new)
15 Dec 13:36:25 - verbose: Firing event to search to /events
15 Dec 13:36:25 - verbose: proxying POST /Me/search/events to http://localhost:18043//events
15 Dec 13:36:25 - verbose: Proxy complete
15 Dec 13:36:25 - verbose: Firing an event for link://links/#f60b22be86e1a07ce400a0714c5666d5 action(update)
15 Dec 13:36:25 - verbose: Firing event to search to /events
15 Dec 13:36:25 - verbose: proxying POST /Me/search/events to http://localhost:18043//events
15 Dec 13:36:25 - verbose: Proxy complete

**Comment by quartzjer** [comment]
re-open this if you can reproduce it now, should be fixed :)

**Comment by mdz** [comment]
working now with 98c08b5a3840b5146a8ce20ab659bcf4862f1eeb
