### ISSUE TITLE
"view code on github" links to the wrong place

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#505]
It's just linking back to lockerproject/locker in many cases: http://bit.ly/u0z0R0

**Comment by ctide** [comment]
That fix won't fix anything existing, btw, we'd need to write a migration to rescrape them to get existing ones functional

**Comment by smurthas** [comment]
Seem like the migration should be part of this. Otherwise create a new issue for the migration?

**Comment by ctide** [comment]
If you feel like it's necessary, then yeah, I'd create a new issue.  I'm not even sure how I'd even go about that migration, short of just deleting people's connected Githubs and forcing them to reconnect.  All the singly provided viewers have correct links, the only incorrect ones are ones that were pulled in via github.
