### ISSUE TITLE
API Rate limit exceeded for...

### ISSUE THREAD

**Issue by infobeans** [LockerProject/Locker#514]
We are getting multiple issues from Mac when trying to commit/push changes. 
issue #1) API Rate limit exceeded for...
issue #2) Missing repository

Please help

**Comment by quartzjer** [comment]
Could you provide some more detail or a sample of the log output? Thanks!

**Comment by infobeans** [comment]
Hi Jeremie,

Thanks for the quick response.

After logging the issue, we were able to resolve it from our end and it is not working fine.

Thanks again

Regards,
Jeevan Sharma

**Comment by quartzjer** [comment]
Glad it's working, let me know if I can do anything to help, and feel free to join on IRC in #lockerproject on freenode anytime!
