### ISSUE TITLE
No apikeys setup leaves locker useless

### ISSUE THREAD

**Issue by temas** [LockerProject/Locker#517]
You should be able to explore other parts of the locker or write a push app still if apikeys is not setup.

**Comment by smurthas** [comment]
The synclet reorg pull improves this by exiting with a useful error message, but I agree the longer term solution is to be able to run without it.

https://github.com/LockerProject/Locker/pull/510/files#diff-29

**Comment by temas** [comment]
I feel your commit addresses this for now, closing this issue.
