### ISSUE TITLE
create#publish rename box is radio not check

### ISSUE THREAD

**Issue by temas** [LockerProject/Locker#518]
The button to choose to rename your app should be a checkbox and not a radio button on the create#publish page of dashboardv3

**Comment by ctide** [comment]
It is a checkbox styled like a radio button to match the design.

**Comment by smurthas** [comment]
This is still really confusing. I almost filed another issue because I thought the same thing. We should reconsider the styling here.

**Comment by merc3po** [comment]
Do I need to make an asset or can it be restyled w/ CSS?

**Comment by smurthas** [comment]
I can just make it go back to looking like a regular checkbox. good?

**Comment by merc3po** [comment]
Yep
