### ISSUE TITLE
The service map should consist of a single service entry

### ISSUE THREAD

**Issue by temas** [LockerProject/Locker#534]
![The Whiteboard](http://dl.dropbox.com/u/1362507/Singly/Photo%20Jan%2005%2C%206%2003%2004%20PM.jpg)

Above is the whiteboard that resulted from an entire conversation that spun up due to the service map becoming polluted once again.

The core system has evolved for addressing and installation of services, at least three times, over the course of the core development, but remnants of each design change has remained in the code.  Attempting to clear out this rot has happened twice as well, but pieces were deemed necessary to persist without breaking too many things.  Now is the time to break all the things.

The concept presented here is that the map will only contain fully ready and addressable services in the system.  There is no more available or installed distinction.  To facilitate this, all of the available services and apps are maintained in the external registry and not in the system or service map.

This gives a clear distinction between the running system and available packages.

**Comment by temas** [comment]
@quartzjer @smurthas @erictj @othiym23 @mdz 

Let me know what else you'd like me to expand upon from our conversations.

**Comment by quartzjer** [comment]
+1!

**Comment by othiym23** [comment]
If it's not too huge a pain, it would be educational to have a sequence diagram / narrative description of how the locker goes about resolving available / installed services before / after making this change. In general, though, this seems like the right way to do it and now is totally the time to break all the things.

+1

**Comment by temas** [comment]
Some thoughts from my flight home

# Service Map Overhaul

## Required Data

These are not exhaustive, just first musings.
- In the map
  - provides
  - uses
  - static
  - accounts
  - handle
  - version
- In the repository
  - screenshot / icon

## TODOs
- Fix areas that use the available list:
  - File list in sm-TODO.md in repo
- Check everything that uses provides
  - File list in sm-TODO.md in repo
- Create unit tests 
  - service manager
  - synclet manager
  - registry

## Important Notes
- lconfig contains a list of the preinstalled packages
  - Collections
  - Defaults Apps
  - All connectors are in the registry
- The service map can b saved and loaded for startup speedups
  - Once the startup is complete the system can async scan for new entries, during this time holding any inbound attempts to connect to an unknown handle

**Comment by temas** [comment]
The migration for this needs to make sure that it does:
- merge manifest files and rewrite me.json with all fields
- iterate the installed me.json files and use that to npm install the correct modules.

**Comment by temas** [comment]
The imthemap branch is almost there.  Bit more testing and hopefully tonight it will be pushed for review.

**Comment by quartzjer** [comment]
Also a known issue, until there's a new built-in migration framework, any needed migrations will have to be external / one-off ones (like Ops/me2me.js).

**Comment by smurthas** [comment]
This is done with imthemap merged in
