### ISSUE TITLE
sad Linkalatte

### ISSUE THREAD

**Issue by othiym23** [LockerProject/Locker#556]
No links display, and this shows up in the Safari (but not Chrome, which gives a terser, less useful error message) console:

TypeError: 'undefined' is not an object (evaluating 'arg.item.encounters[arg.item.encounters.length - 1].from') [allAlone.js:223]

**Comment by quartzjer** [comment]
I can add extra error checking to make sure it doesn't die when it
hits this case, but could you also provide a gist of the full json
it's trying to load? (look in the dev tools for the full resource
url?)

On Mon, Jan 16, 2012 at 3:21 PM, Forrest L Norvell
reply@reply.github.com
wrote:

**Comment by othiym23** [comment]
That would have been an excellent thing to do, but the problem was occurring before about 80 different deployments, migrations, and replacements of our proxy server, so the problem's fixed itself now. We know that somewhere there's a link in my links collection without an encounter, though, maybe? Is there any way I can search MongoDB for the bad link?

**Comment by quartzjer** [comment]
Yeah probably, but my mongo fu isn't good enough to figure it out,
what would be in the links collection but not in the encounters one :/

On Mon, Jan 16, 2012 at 6:49 PM, Forrest L Norvell
reply@reply.github.com
wrote:

**Comment by othiym23** [comment]
It's time for me to get better with Mongo querying, so I'll see what I can come up with.

**Comment by smurthas** [comment]
The issue there is the links and encounters are "SQL-style" (i.e. two diff collections) instead of "Mongo-stlye" (embeds) so you'd have to loop through all of the links and query to encounters to find the missing one, there isn't a magical join that would tell you.

**Comment by othiym23** [comment]
This is definitely still an outstanding issue; I just ran into it on 01/27. It still renders my links list undisplayable until the problematic link has worked its way out of the list of recently-synced links.
