### ISSUE TITLE
Something is logging lots of raw JSON

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#560]
e.g.:

{"level":"info","message":{"0":105,"1":110,"2":115,"3":116,"4":97,"5":108,"6":10
8,"7":105,"8":110,"9":103,"10":32,"11":102,"12":114,"13":111,"14":109,"15":32,"1
6":114,"17":101,"18":103,"19":105,"20":115,"21":116,"22":114,"23":121,"24":32,"25":100,"26":97,"27":115,"28":104,"29":98,"30":111,"31":97,"32":114,"33":100,"34":118,"35":51,"36":10,"length":37,"parent":{"0":84,"1":117,"2":101,"3":32,"4":74,"5":97,"6":110,"7":32,"8":49,"9":55,"10":32,"11":48,"12":49,"13":58,"14":48,"15":48,"16":58,"17":53,"18":56,"19":32,"20":91,"21":105,"22":110,"23":105,"24":116,"25":97,"26":110,"27":100,"28":108,"29":105,"30":115,"31":116,"32":101,"33":110,"34":93,"35":32,"36":77,"37":111,"38":110,"39":103,"40":111,"41":68,"42":66,"43":32,"44":115,"45":116,"46":97,"47":114,"48":116,"49":105,"50":110,"51":103,"52":32,"53":58,"54":32,"55":112,"56":105,"57":100,"58":61,"59":54,"60":32,"61":112,"62":111,"63":114,"64":116,"65":61,"66":50,"67":55,"68":48,"69":49,"70":56,"71":32,"72":100,"73":98,"74":112,"75":97,"76":116,"77":104,"78":61,"79":47,"80":104,"81":111,"82":109,"83":101,"84":47,"85":77,"86":101,"87":47,"88":109,"89":111,"90":110,"91":103,"92":111,"93":100,"94":97,"95":116,"96":97,"97":32,"98":54,"99":52,"100":45,"101":98,"102":105,"103":116,"104":32,"105":10,"106":84,"107":117,"10:
[...megabytes worth...]

**Comment by quartzjer** [comment]
raw buffer objects it looks like, do you ahve any context before/after handy?

On Mon, Jan 16, 2012 at 7:02 PM, Matt Zimmerman
reply@reply.github.com
wrote:

**Comment by mdz** [comment]
Fixed by 955caea805aa73a390181c5db9c4ece3d5d65dd3
