### ISSUE TITLE
me2me silently hangs forever if DNS resolution fails

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#562]
Reproduced locally in a VM

**Comment by mdz** [comment]
It seems likely that other operations may show the same behavior, but this is the only case I've confirmed so far

**Comment by quartzjer** [comment]
This is likely not just a me2me problem, but a problem with any
registry install, and with npm commands in general?

On Mon, Jan 16, 2012 at 7:42 PM, Matt Zimmerman
reply@reply.github.com
wrote:

**Comment by temas** [comment]
This migration tools and issues related to it are now outdated.  Closed.
