### ISSUE TITLE
When first starting locker, thing aren't available

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#572]
http is open on 8042, but there is a bunch of stuff that isn't around yet.

http://bit.ly/wXfZvP

http://bit.ly/w7YAUS

**Comment by mdz** [comment]
@temas  said this would be fixed by making dashboardv3 mandatory in config.json

**Comment by smurthas** [comment]
That will only solve the first issue. The second one is still there in that is looks for the contactsviewer app by default if none is selected, but it's not there. We will need some sort of page to handle the case where the person hasn't added any apps yet, or hasn't connected services. Let's revisit this after the New Account Exp work lands.

**Comment by mdz** [comment]
Agreed. I was thinking maybe a "welcome" app that's mandatory comes up as the default. Maybe the setup experience already has that?

cc @erictj

**Comment by amcjen** [comment]
The newuserexp branch will force a redirect to the connect page (and the rest of the flow) if it finds no connectors have been hooked up yet.  If that's sufficient, then we can close this issue.

**Comment by amcjen** [comment]
If you have no connected services, and you visit localhost:8042 (or lvh.me:8443), you will automatically get redirected to this page:  

http://cl.ly/412d1q2Q3Z371W3o0o0e

If you start hand-entering URLs, then you can get it to break, but you have to actively try to do so.
