### ISSUE TITLE
It's very hard to tell which services are connected

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#575]
They used to and are supposed to

http://bit.ly/x2O8c5

_UPDATE:_ See below for new mock.

**Comment by mdz** [comment]
As long as we're here, I think the highlight is too subtle for indicating what's connected. I feel like maybe a checkmark over the icon would be clearer, or maybe even two lists (connected and available). @merc3po ?

**Comment by merc3po** [comment]
This is the original spec, which is clearer than the implementation: <img src="https://img.skitch.com/20120119-mj54x3nmedf5mbx5yfi9g9yhe2.jpg">

However I think that this is a better solution: <img src="https://img.skitch.com/20120119-g5yftwyxpjsut529w7jrt6umgn.jpg">

**Comment by mdz** [comment]
+1 on "connect more"

**Comment by smurthas** [comment]
I like the second one as well, I think it would be clearer to say "CONNECTED SERVICES" rather than "YOUR SERVICES".

**Comment by mdz** [comment]
Maybe "already connected" and "connect more"?

**Comment by merc3po** [comment]
Let's just say "Connected" and "Connect More"

<img src="https://img.skitch.com/20120119-pxyu95bxerh1gdw1kdwdyarxxt.jpg">

**Comment by mdz** [comment]
I thought it might be more visually distinct if they didn't both start with
"Connect", but it's your call.

On Thu, Jan 19, 2012 at 12:52:15PM -0800, Merci Victoria Grace wrote:

> Let's just say "Connected" and "Connect More"
> 
> <img src="https://img.skitch.com/20120119-pxyu95bxerh1gdw1kdwdyarxxt.jpg">
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/LockerProject/Locker/issues/575#issuecomment-3574015

## 
- mdz

**Comment by merc3po** [comment]
I thought the word "already" looked a wee bit strange:

<img src="https://img.skitch.com/20120120-8j62nw567gpd1bfusfcjsrnrtm.jpg">

**Comment by smurthas** [comment]
updated the issue title and text to reflect the new direction here.

**Comment by elsmorian** [comment]
I'd be tempted to use "Connected" and "More Services" :-)

**Comment by merc3po** [comment]
Nice - I like that. Let's use "Connected" and "More Services" :-) Thanks elsmorian!

<img src="https://img.skitch.com/20120123-ephbay529f8btkneqhyedhaxxp.jpg">
