### ISSUE TITLE
Authorship history doesn't do anything

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#589]
Should it? Might not be worth it for now. Either way, it needs to be fixed of removed.

**Comment by merc3po** [comment]
Let's move this to LOGO. The team expressed a desire to show authorship history but it looks like we're not getting that from Github right now, so let's remove it from MEGA. :)

**Comment by smurthas** [comment]
Ok, I'll remove the code for now and move this issues to LOGO.
