### ISSUE TITLE
Text for "Our Mission" section

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#591]
Here is the straight-up text: 

Singly exists for you.

We’re on a mission to empower individuals and developers by breaking down barriers that limit personalization and creative expansion of the web. To allow people to see, share, understand--and most importantly, own--their stories.

How?

Singly is an open personal data platform that delivers truly personalized computing. We’re building an ecosystem to unlock the creative potential of the developers who make the web the innovative platform it is. By connecting networks and platforms and allowing open interaction and portability of data, Singly will turn constraint into opportunity.

We aren’t simply allowing developers to build on this platform; we’re encouraging, supporting and interacting with them in every way.

We are pragmatic idealists. 

We approach our work with passion, optimism, and tenacity by embracing new ideas, contrasting opinions, and meaningful debate. If nothing else, we’ll never be complacent.

Personality is key.

Our office is open, beautiful and bright. In fact, so is our team. We ♥ node.js, sunlight, vegetables, good beer, music and anything open source. Singly prides itself on maintaining a positive atmosphere with open communication and an ever-challenging workload.

If you're inspired, infuriated or just interested, send us a Tweet or drop us an email, we’d love to hear from you.

And here is how it's meant to be formatted on the page: 

<img src="https://img.skitch.com/20120119-emmkm1a7kx2ggg3g8sx6mms5q2.jpg">

**Comment by smurthas** [comment]
This is not a locker issue, moving to integral.
