### ISSUE TITLE
UI feedback of 'things happening' is poor

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#595]
There is no visual concept of locker working in the background to download new data, which is disconcerting to the user.

For example, I can add 4Sq service, and a popup starts to load, and then disappears, and thats it. If I click on photos, no photos- and it is unclear what has happened. (Of course, if I wait 5 secs for locker to start downloading pictures they appear fine.)

Some sort of cue is need for the initial connection, and it might be nice to subtly indicate a refresh of info - something like a spinner spinning on top of the service icon, or a slow fade in and out?

**Comment by merc3po** [comment]
I want to make sure we look for this as we polish the experience, so I'm adding it to MEGA.

**Comment by merc3po** [comment]
Thoughts on this? 

<img src="https://img.skitch.com/20120126-jigqpeuyt4uddsux1wfe7747hy.jpg">

and then 

<img src="https://img.skitch.com/20120126-eacwrint6n41iers1515m7qc59.jpg">

**Comment by merc3po** [comment]
We can show the data types w/ icons rather than text, too, which will look prettier for sure. It might be less clear than text, though.

**Comment by elsmorian** [comment]
I like the look of this. A few thoughts-  Provides: instead of Gets:?
Would be nice to have a spinner or something next to the current services that are being installed I think, just to reassure the user that things are happening in between percent complete updates.

The colour of the buttons is tricky IMO- Green is cool for "go! connect your services!" But then they turn grey when connected, which feels a bit like it failed, but then it does say connected, and says what it's installing..

Maybe have them blue to start when they say CONNECT, grey and CONNECTING, ie installing and downloading data from the service, and then green when they say CONNECTED, all data has been downloaded and service is installed and working properly?

This also has room for a red or orange colour for an error state, which could be used for a data error or problem. People on IRC mentioned a profile page with an indication of which services you have already installed etc would be good, this would then maybe also be useful for this?

A connect all button bellow the connected buttons might be nice too, to add all the services with one click.

**Comment by merc3po** [comment]
Here's the account settings project issue: https://github.com/LockerProject/Locker/issues/613

**Comment by merc3po** [comment]
And here's the button states: https://github.com/LockerProject/Locker/issues/630

**Comment by temas** [comment]
I feel there's an issue of using any actual progress meter on this page.  It will cause people to stay on this page until it is all the way done.  As soon as data starts syncing the locker is usable, so we want them to quickly move through adding as many services as they want and then get to the exploration phase.  There should definitely be feedback, but not anything that makes them feel restricted.  I was also wondering if there should be anything different in the bottom left corner of the You page until full completion?

**Comment by elsmorian** [comment]
Agreed, the user shouldn't get the feeling they have to wait for the locker to be completely full to start using it. Quickly adding services would be quite nice with a series of checkboxes, account you want to add, and then one big connect button, which connects all services one by one and then guides to to the explore page?

A spinner at the top corner of each service icon when they are syncing might also be nice?

**Comment by merc3po** [comment]
Okay great. Splitting this into a different issue for implementation since this covered a bunch of issues. #680 will cover the new account experience.
