### ISSUE TITLE
Service icon state seem inverted

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#596]
Maybe this one is just me-

But when I start, all service icons are in full colour, which to me means available / ok / working fine.
After connecting the services, they turn greyed out, to me meaning unavailable, or unappreciable. 

Perhaps they should start off greyed out, becoming full colour on mouse over, indicating the user could change the state by clicking? After successful connection, they should go to full colour, indicating success. At least in my mind :)

**Comment by merc3po** [comment]
I'm going to close this, as we have a pending issue that should resolve this (shared) confusion: https://github.com/LockerProject/Locker/issues/575

If you have thoughts about the proposed solution, feel free to comment on that issue. Thanks so much elsmorian!
