### ISSUE TITLE
Python import error with glatitude

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#597]
After connecting Latitude service, I get an import error for lockerfs:

20 Jan 15:40:52 - error: Google Latitude locations error:   Traceback (most recent call last):

20 Jan 15:40:52 - error: Google Latitude locations error:     File "/home/elsmorian/NewLocker/Common/python/synclet/client.py", line 66, in <module>

20 Jan 15:40:52 - error: Google Latitude locations error:  
20 Jan 15:40:52 - error: Google Latitude locations error:   run(info)

20 Jan 15:40:52 - error: Google Latitude locations error:     File "/home/elsmorian/NewLocker/Common/python/synclet/client.py", line 20, in run

20 Jan 15:40:52 - error: Google Latitude locations error:  
20 Jan 15:40:52 - error: Google Latitude locations error:   sync = **import**((run['run'].rpartition('.'))[0])

20 Jan 15:40:52 - error: Google Latitude locations error:     File "/home/elsmorian/NewLocker/Me/node_modules/glatitude/locations.py", line 10, in <module>
    import lockerfs
ImportError: No module named lockerfs

20 Jan 15:40:52 - error: Service : Google Latitude, synclet: locations  . Failed to parse the response from the synclet.  Error was: 'SyntaxError: Unexpected end of input' and the response from the synclet was ''

**Comment by elsmorian** [comment]
This is still happening and preventing any import of latitude data.

**Comment by quartzjer** [comment]
I fixed this, YAY!  Man I have almost 15 thousand locations!
