### ISSUE TITLE
API explorer no longer mentions filters

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#598]
IIRC, you used to be able to play with the query filters in the API explorer, which was ver handy, and allowed you to test functionality such as only returning 10 places which you created.

Any chance we can get this back?

**Comment by merc3po** [comment]
Adding @smurthas to this as he's making significant improvements to that section this week. :-)

**Comment by smurthas** [comment]
Nothing has changed about how the API explorer works. Could you explain more?

**Comment by elsmorian** [comment]
My apologies guys, this was a result from me looking in the wrong place for the docs. I was unaware of teh difference between the collections API and query API :)
