### ISSUE TITLE
Getting items from API offers no sorting ability

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#600]
It would be rather nice to be able to request the first 20 or last items in a collection etc. sorted by time, or latitude from a starting point etc (ie 10 first photos you took, or 10 farthest places you've been from a lat).

**Comment by merc3po** [comment]
Hmm is this what Timeline is for @quartzjer?

**Comment by quartzjer** [comment]
Timeline will do this for some of the data, but I think the current query api can do quite a bit of it already.  Perhaps @elsmorian you could make specific issues for exact api calls you need and we can verify each of them as existing or new features independently? (time sort exists, but distance based doesn't for instance)

**Comment by elsmorian** [comment]
Sure, I will have a think and make specific issues for each :)
