### ISSUE TITLE
App Registry Exp. 

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#602]
Stub for the eng. story alreayd in progress, just to measure work that still needs to be done: 
https://docs.google.com/a/singly.com/document/d/1AHaCqkZFoclze2Tx7KmRmTRijonOo18s85fycxcYCxs/edit?hl=en_US

**Comment by temas** [comment]
This all seems relatively complete now.  Simon is pushing some changes to the github synclet to make sure data is in the correct order, but otherwise multiple testers have success.  Any more issues before close out?

**Comment by merc3po** [comment]
Huh if I click on one, I get blank page, but this is the live site and not local. (On my local I can't access my Locker at all)

**Comment by merc3po** [comment]
Also happening on my local, now that I can get into Locker again.

<img src="https://img.skitch.com/20120124-myx2ceqyytiwaijurr38i6n39f.jpg">

**Comment by smurthas** [comment]
i'll take a look at this, probably something simple.

**Comment by merc3po** [comment]
smurthas got this to work :)
