### ISSUE TITLE
integration tests can't be run against apps under development

### ISSUE THREAD

**Issue by othiym23** [LockerProject/Locker#603]
With the changes made by the imthemap branch, it is currently difficult to impossible (I couldn't figure out how) to get the integration tests to run against a version of the locker with the local development version of an App. There is a prepopulated directory containing some of the apps, and the rest are pulled down from the registry at runtime. There needs to be a mechanism in place for devs to indicate that a given app needs to be run locally rather than against the registry version / the version in Data.tests.

**Comment by quartzjer** [comment]
cc @temas

Temas and I have talked about this some and it's not reached group
level yet, but the consensus we have so far is that we should start
moving all _unit_ tests to the app/connector/collection directories
themselves (which is what many of the tests are), and have the top
level test directory become core unit and overall integration only
(related enough to mention here I guess).

After the processing-submissions story, we'll have the ability to
publish dev versions of anything without it getting used by anything
in production until it's signed, which might be the right route for
overall integration, especially if (when I think) we move all the
components to their own repos.

On Sat, Jan 21, 2012 at 3:17 PM, Forrest L Norvell
reply@reply.github.com
wrote:

**Comment by othiym23** [comment]
The problem is that this makes a TDD / BDD workflow (which I prefer / am much more productive following) much more difficult, because it interrupts the quick / tight write test -> tweak code -> get test passing flow with a publishing step. Does npm let you publish the same package with the same version multiple times?

Stepping back a bit, pushing unit tests out into the package directories for collections and connectors makes sense, but it gets fuzzier for apps. It seems like we'd want some way to share fixtures, and apps are dependent on the other services in a way that they aren't.

**Comment by quartzjer** [comment]
For TDD/BDD you probably have to approach apps the same way you would
if you're coding against any 3rd party API, which outside of unit
tests is probably a mix of fixtures and mocks (which I think is what
you're saying already)?

I used to think sharing fixtures made sense, but I'm pretty sure it
doesn't.  A connector should have it's own fixtures tied to whatever
version it is, and the same for a collection based on the fixtures it
supports for it's version.  Sure there is two copies of a "tweet"
fixture, but keeping them distinct lets the already-existing version
management work safely and any tests run locally.  We'll need to use
major/minor/patch properly as we encounter these dependency
relationships, but don't want to get too cart-horse and this isn't the
right thread either :)

On Sat, Jan 21, 2012 at 6:12 PM, Forrest L Norvell
reply@reply.github.com
wrote:

**Comment by othiym23** [comment]
Here is the workflow I've developed over the last few years of working with BDD:
1. Write an integration test case tied to one of the top-level features in the story I'm working on (e.g. click the link on Account Settings, get taken to the account settings area).
2. Drill down, writing functional and unit tests as I find the additions and modifications that need to be made to lower-level APIs and libraries.
3. Work my way back up until all of the tests are passing.
4. Repeat for each top-level feature in the story.

The primary value of this workflow is that it frees me from having to mentally bookmark my state at any given point in time -- I can just run the tests and see what's passing and failing. Especially when the code base is undergoing a lot of change at a lot of hands (like it is now), it's extremely valuable to not have to be constantly having to figure out where I am or what I'm doing -- my tests tell me what remains to be done.

It seems to me like it's going to be comparatively rare for the core locker developers to be working on a single submodule / npm package at a time in this new model. This means that there are now abstraction barriers between different bits of the test framework that didn't exist before, and there are more levels of indirection that get in the way of using the flow up above. I can tell you that for me this makes it a lot less likely that I'm going to be writing useful tests, because getting them passing is such a huge pain in the ass, and because making them serve my primary purpose -- that is, helping me track how close I am to being done and help me figure out where I need to focus next -- is difficult to impossible.

**Comment by quartzjer** [comment]
IMO there's an expectation perception difference here.  If you're
developing tests for a web app, you don't run all of the databases and
web servers and operating systems tests and depend on those in order
to test your app, you expect them to work as advertised.   We need to
depend on other parts of the locker ecosystem in this loosely coupled
way, not tightly bound into a a single testing (or even integration)
routine.

All of those patterns should apply but scoped to the level of the
app/collection/connector, and it might take some work for core to
better facilitate this kind of separation but we'll figure that out as
we hit those pain points.

On Sat, Jan 21, 2012 at 6:38 PM, Forrest L Norvell
reply@reply.github.com
wrote:

**Comment by othiym23** [comment]
I'm going to dig into the situation I'm confronting, because I am actually hitting a pain point _right now_.

I'm working on building out the account settings page, based on @merc3po's mockups. The way I have done this kind of UI work in the past is to write a capybara / webrat / Selenium test case that drives a piece of the behavior (clicks on the link for the account settings) and then verifies that the expected behavior results (the account settings page is displayed).

In this case, it's almost incidental that the behavior is in the dashboardv3 app, because it's hitting endpoints that are in the core (the locker's authorization credentials, the locker owner's profile, and, in the case of hosted lockers, their Integral registration information). Additionally, the controller and view logic is defined in browser-side Javascript, but the model is coming from several endpoints hosted off in the core of the locker and Integral.

There is very little our unit test framework can do to help me here, because the code is a large pile of callbacks built on top of jQuery. There isn't an easy way to inject mocks or stubs into the browser-side code short of using something like Env.js running on top of Rhino, which isn't a really accurate simulation of real browser behavior and is working around exactly what capybara was designed to provide. It's theoretically possible to refactor it all to be more testable from within the browser (using something like Jasmine or [jasmine-jquery](https://github.com/velesin/jasmine-jquery)). However, that's not how our code is designed right now, and doing that work is **way** beyond the scope of the story.

Two weeks ago, it would have been possible for me to write a capybara test, run the suite, and get feedback on the state of my work. Today, I can't do that. Can you help me find a way to get the feedback I want with our current framework?

**Comment by quartzjer** [comment]
> There is very little our unit test framework can do to help me here, because the code is a large pile of callbacks built on top of jQuery. There isn't an easy way to inject mocks or stubs into the browser-side code short of using something like Env.js running on top of Rhino, which isn't a really accurate simulation of real browser behavior and is working around exactly what capybara was designed to provide. It's theoretically possible to refactor it all to be more testable from within the browser (using something like Jasmine or [jasmine-jquery](https://github.com/velesin/jasmine-jquery)). However, that's not how our code is designed right now, and doing that work is **way** beyond the scope of the story.

Ok, outside of anything else, it sounds like the more modern style of
in-browser-navigated (#-based) apps are more difficult to test with
traditional tools.  I'm so way out of my element here both on testing
and in the browser, so I can't offer much help/input :(

> Two weeks ago, it would have been possible for me to write a capybara test, run the suite, and get feedback on the state of my work. Today, I can't do that. Can you help me find a way to get the feedback I want with our current framework?

So yes, two weeks ago the startup process was more locally tightly
coupled, the requirements to test new code could be turned on at once
(lockerd and the local in-dev app).  And now there's the extra step to
assert local code over registry that is one-time for the "normal"
lockerd and
 is in a more confused state as to how to do that for the test
instance that starts up.

Seems like there's two paths, one being fix the local test suite so
that it can be clearly told "use the local version of X" and given how
much of a hodgepodge it is (it's internally rigging a really
frustrated alternate local lockerd), I'm not even sure the best way to
do that, it's a very sore point that @temas has been looking at
heavily as well.

The other path is one I'm more keen on, create/run the test in the app
directory and pass it the http url of the lockerd to use as the base
(that is independently running already, treated as a completely
separate resource).  The local test runner creates the processInfo
object containing the lockerd to use for the api calls and starts the
app using the run line from package.json.  The app is then running
independently and local tests can use the local port it was given or
returned.

The challenge with this is obviously when the testing might change
state in lockerd, but I don't know how this is any different than the
patterns of any mutable external api, like having to test against
posting a tweet and verifying, etc.  Usually it's either mocking the
api (fakeweb), using the api to restore state (delete the tweet), or
having a way to externally reset outside of the test.

All I know is that the testing we were doing was giving us all a false
sense of confidence, the fact that tests looked like they ran
successfully was often flat out a lie, and turning on silly logging
made it painfully obvious how confused of a rig it was (and still is
in large part).

**Comment by othiym23** [comment]
If you'll recall, we (@nym, really) did write some tests in exactly the way you describe -- set up a test instance configured the way the tests expect, run the Selenium tests against them, write them in such a way that they create a new account each time because the framework couldn't tear down an existing locker / create a new one on the fly remotely. This was ungainly and led to us having a bunch of busted test lockers hanging around very quickly -- the approach doesn't scale.

Introducing capybara and tying it to the test locker set up by runTests.js wasn't meant to be a permanent solution (speaking on behalf of @ctide here, but I think he'd agree) because it is brittle, but at least it let us get our integration tests running in the CI environment. Assuming merging app work into master implies publishing and signing any apps that were changed on the branch, this workflow _should_ continue to work under the new regime. It's important that the tests we write be usable by CI, so that's good.

What would be ideal is having some way for a set of test cases to declare their package dependencies (i.e. "published", a specific npm version, "local"), and then some npm plumbing run by the test framework would set up the node_modules for that set of tests accordingly. It would be even better if we had two configuration files for this -- one local and outside of version control, one designed to be checked into Git and used by CI. It would also be awesome to modify the integration tests to be capable of being run completely free-standing from the rest of the framework. I don't even think it would be that much work (which, of course, means I'm volunteering to do it).

**Comment by othiym23** [comment]
As I see it, there are three chunks of work necessary to make this approach work:
1. Having some way of signaling to the locker core that it should use the current set of packages as supplied (something set in registry.json?).
2. A framework for running up a test Me / Data directory with a specific set of packages in node.modules (maybe something that generates a packages.json file and passes it off to npm?). It would be ideal if this were something that were factored out of locker core and callable from Ops/ so the rake task that drives the capybara tests could just call that script to set up / tear down a locker between each integration test.
3. Modifications to the test framework itself to allow sets of tests to declare dependencies, maybe / probably with those declarations being made out-of-band in a separate configuration file (that could look a lot like a packages.json file with some additional keywords, to simplify processing).

How does that sound?

**Comment by ctide** [comment]
Yes, using the locker that was built up via the unit tests was definitely a stopgap measure.  It was the simplest thing so that we could get some front end tests up and running quickly, as opposed to maintaining a separate set of test data that's designed just to work with the front end tests.

Ideally, the test suite should create a locker whose data set is established by a set of factories that probably fire off a bunch of events that generates a basic set of data that the integration tests expect to be there to run against.  It was just easier to postpone that work and use what was there from the unit tests to get something in place sooner as opposed to later.  Trying to isolate pieces (ie, having some base locker that's used by all front end tests) which are all tightly coupled together will just create a massive amount of problems to sort through.

**Comment by smurthas** [comment]
There's a lot here and I'm not sure what the best path it just yet, but I just spent the past several hours fighting to try to debug the dashboard and connectors without any real ability to test whether I was consistently making progress without breaking anything.

We definitely need to improve this!

**Comment by quartzjer** [comment]
> 1. Having some way of signaling to the locker core that it should use the current set of packages as supplied (something set in registry.json?).

An upsert does that already for a running locker, but I think there's
a need to have that happen during initial startup ahead of installing
required packages?  This could make new-locker-setups on production go
really fast too, to have a copy of all the base required packages
local and upsert them the first time.

> 1. A framework for running up a test Me / Data directory with a specific set of packages in node.modules (maybe something that generates a packages.json file and passes it off to npm?). It would be ideal if this were something that were factored out of locker core and callable from Ops/ so the rake task that drives the capybara tests could just call that script to set up / tear down a locker between each integration test.

Ok, so, a standalone tool to create a new Me dir and running lockerd
from a predefined list? Given the above, that sounds super doable
(guess I volunteered too, heh :).

> 1. Modifications to the test framework itself to allow sets of tests to declare dependencies, maybe / probably with those declarations being made out-of-band in a separate configuration file (that could look a lot like a packages.json file with some additional keywords, to simplify processing).

Not totally sure here, examples?

**Comment by othiym23** [comment]
I think this one actually got addressed eventually, so closing as quasi-resolved. 🏆
