### ISSUE TITLE
Top links to Singly services etc break when locally running

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#606]
Links go to https://singly.com/learnmore which returns an Internal Server Error, and things like https://lvh.me:8443/users/me/settings which don't resolve. I understand these are to do with the Singly hosted lockers, any chance on boot locker can check itself where it is hosted, and only display these if hosted at Singly?

**Comment by merc3po** [comment]
Is this still happening @elsmorian? If so I feel like we have other issues that are filed to deal w/ setting those URLs via a config file.

**Comment by elsmorian** [comment]
They don't seem to be showing up anymore!
