### ISSUE TITLE
If an invalid dashboard is specified in the config, locker bails hard

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#607]
It should probably default to something that it knows works and complain loudly.

**Comment by quartzjer** [comment]
I kinda disagree, it should bail hard shouldn't it?

On Mon, Jan 23, 2012 at 11:32 AM, Simon Murtha-Smith
reply@reply.github.com
wrote:

**Comment by quartzjer** [comment]
I'm going to close this as I don't think defaulting to (or even figuring out what "knows works" is) is good at all :)

Totally happy to have it reopened if you have a convincing reason why hard-bail isn't the best thing to do here!

**Comment by smurthas** [comment]
Yep, makes sense.
