### ISSUE TITLE
Account settings

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#613]
Capturing this engineering project in the issues list: https://docs.google.com/a/singly.com/document/d/1Oeq04eQIu5TqCj1CikoQ99dweNA3O2C2l4Hs9USGxc0/edit?hl=en_US

Here are the mocks: 
<img src="https://img.skitch.com/20120126-tam5wx3kiqbu8jdp2nr7wx93uj.jpg">
<img src="https://img.skitch.com/20120126-d1cj6ys9jf4gjma31ndprphkn8.jpg">
<img src="https://img.skitch.com/20120126-ferq5mtqehr199krmq5qqah9j2.jpg">

**Comment by othiym23** [comment]
This is not only closed, but in production (pending the update of production's config.json to point at the correct endpoint). No more MEGABLOX!

Some of the validation styling could use a little help. File as bugs if noticed.
