### ISSUE TITLE
when publishing via the dashboard, no indicator it's working

### ISSUE THREAD

**Issue by quartzjer** [LockerProject/Locker#614]
Takes 10 seconds or so after you click the publish button, and there's no way to tell it's actually doing anything...

**Comment by merc3po** [comment]
I'll make a loading animation :-)

**Comment by merc3po** [comment]
This might solve that issue, thoughts @quartzjer? https://github.com/LockerProject/Locker/issues/630

**Comment by merc3po** [comment]
This is the solution for the issue: https://github.com/LockerProject/Locker/issues/633
