### ISSUE TITLE
Not using my Twitter avatar 

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#618]
If I sign up first using Twitter, it's not using my Twitter avatar as my account avatar.

Since we sign up w/ either Twitter or Facebook, the Locker should grab either one of those as the avatar image. Detailed here in the original spec: https://docs.google.com/a/singly.com/document/d/1R7-e31FyB9wAgd9H-0T5t0cBEjqkssDUBNIcfviAVXM/edit?hl=en_US#bookmark=id.93iqvvddemm9

**Comment by amcjen** [comment]
It does show up, it just sometimes takes a few seconds because when we auth, the locker has to go out and get the profile, so it's not immediate.  Mine below showed up after about 3 seconds:

http://cl.ly/1Q3P3c3g2W0o1G2l1u1H

**Comment by merc3po** [comment]
I'm still seeing this on Locker/Sandbox. I only authed Twitter, went through the new-account-experience and waited several minutes. No avatar. (I only authed Twitter to mimic what most usability participants did.) 

<img src="https://img.skitch.com/20120204-nmkrfjgea57jsyuxn3wixtruc4.png">

**Comment by temas** [comment]
While exploring running on windows this weekend I saw some odd behavior here.  I connected twitter and saw my icon for a bit, but then going form gallery -> explore again it went away.

**Comment by othiym23** [comment]
Just so everyone knows, I flipped the default order from Facebook -> Twitter to Twitter -> Facebook. This is entirely to satisfy my own vanity, because I hate my Facebook avatar and don't want to have to futz with Facebook long enough to change it.

**Comment by merc3po** [comment]
Ha! That is both acceptable and funny. It shouldn't really be in an order though, it should be whichever they authed first. If they did FB first, then it's their FB; Twitter first, it's their Twitter ID. I think this relates to the FB/Twitter page being missing from the new account experience - #739

**Comment by othiym23** [comment]
It makes sense to use whichever authed first, but to do this would require more changes than are worth the effort right now, due to the way that the code pulls the profiles from the map. The right way to do it would be to pull the avatar at auth time and cache it within the locker. I'll create a new issue describing how that could be done and we can prioritize accordingly.

**Comment by merc3po** [comment]
Okay thanks. :-)
