### ISSUE TITLE
First startup is sloooow

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#623]
to install the basic, requires apps and services from the registry takes a long time.

Here are my thoughts on how we could solve this:
1. Create a way to "pre-install" things (pre populate the Me/node_modules dir?)
2. Make the registry FASTER (varnish? pay them some money?)

Any other thoughts?

**Comment by smurthas** [comment]
This also results in being able to click over to the CREATE section before dev docs is available.

**Comment by quartzjer** [comment]
I added the ability to locally install stuff last night (see email :)
that will totally solve this when first boot speed is important :)

I also set up a fastly.com account today that is a turn-key cdn to
front our registry and aggressively cache, didn't have time to test it
yet!

On Tue, Jan 24, 2012 at 8:08 PM, Simon Murtha-Smith
reply@reply.github.com
wrote:

**Comment by temas** [comment]
Jer's tweaks plus a few more I put in 1c6fed90c0c215e4917f8d5f4c3624846b9a85b0 should close this out.  Issues related to using these changes can be a new issue.
