### ISSUE TITLE
In a new locker, no service icons show up

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#627]
In a new locker freshly installed with an once-working apikeys.json file,

I get: https://skitch.com/elsmorian/g5sh7/locker-running

**Comment by quartzjer** [comment]
Heh that's a problem :)

I wonder, do you have twitter and Facebook apikeys? Was there any console errors or could you gist the full startup log (maybe with silly logging on?)?

**Comment by elsmorian** [comment]
I don't have either apikeys, just GLatitude, 4Sq and Github.

https://gist.github.com/1676646 is the startup log, but I can't see any errors.

**Comment by temas** [comment]
So there's currently an assumption that you have Facebook or Twitter, the two richest data sources right now.  The startup logic could be tweaked to skip that assumption if neither is configured, but they definitely help in terms of real data availability.

**Comment by elsmorian** [comment]
While I agree they are the richest source of data, the use that we shall be using locker for has a very high probability that users may not have any services connected, relying on pushes to the locker to get data into it for apps to use.

**Comment by amcjen** [comment]
I touched that piece of code last, so I'm happy to add some logic in there where if no Twitter or Facebook API keys exist, then just show all available services.  If you don't have _any_ API keys, then I'll have it show a message indicating so.

Good find!

**Comment by elsmorian** [comment]
That would be great!

**Comment by smurthas** [comment]
+1 what @erictj suggested.

**Comment by elsmorian** [comment]
This is still occurring in both a brand new locker, and one that has been git-pulled. my apikeys.json has glatitude, 4sq and github. Interestingly I added a twitter account, which then worked, but it's not showing the glatitude service on the page.

**Comment by elsmorian** [comment]
Also, I get a link to connect to Pandora, even though it is not in my apikeys file.

**Comment by amcjen** [comment]
Hmm, I don't have a glatitude API key at the moment, but replacing that with Gcontacts, when I have those four API keys in place, my first connect screen looks like this:

http://cl.ly/2X2M3n032d371z3b231M

Is that not what you're seeing?

Also, Pandora is a black sheep, b/c it doesn't really have a concept of API keys, so it shows up regardless of state in the apikeys.json file.
