### ISSUE TITLE
Three states for buttons: regular, hover, clicked

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#630]
Let's show people when they click, that they've clicked and that when they're hovering, they're hovering. This is groundbreaking stuff. You might want to step back.

Here are the assets on Dropbox: http://db.tt/P54wwJJM

And here they are lined up next to each other like little round shouldered duckies:
<img src="https://img.skitch.com/20120126-p8bqkqmiwsrg4ja23cxkjpcd9n.jpg">

**Comment by merc3po** [comment]
If you're doing this with CSS, the "clicked state" buttons have an opacity of 40%; and let's use the TypeKit font "Ratio" https://typekit.com/fonts/ratio

**Comment by merc3po** [comment]
This is also a related issue: https://github.com/LockerProject/Locker/issues/633

**Comment by kristjan** [comment]
@merc3po I think I've got 'em all. Wanna take a run through and post any URLs that still need treatment? Optimistically closing the issue for now.
