### ISSUE TITLE
User testing environment needs different URL for "Hosted by Singly" link

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#631]
Clicking on "Hosted by  Singly" signed out one of our testers and then broke the experience for him. He had to clear his cookies to sign back in and then the "CREATE" section was empty.

**Comment by temas** [comment]
So this is actually already in the code and just needed to be configured.
- customLearnmore - link target "#About-OurMission"
- customHostedby - link wording "Hosted by Singly"
