### ISSUE TITLE
Add "gamma" to site

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#634]
Appears in both Locker and Integral. 

Here's the button on Dropbox: http://db.tt/RDJmVEcu

The "gamma" should be in the top right nav and look like this
<img src="https://img.skitch.com/20120126-kbwtijwj1w3hpk8pwt1m6wqhst.jpg">

Clicking it should open up a modal like this: 
<img src="https://img.skitch.com/20120130-4e1nf47yt5e68aamrgmj9f225.jpg">

**Comment by kristjan** [comment]
Do we have a canonical means of popping up modal dialogs?

**Comment by smurthas** [comment]
Ya, there is one in the sign up flow.

**Comment by merc3po** [comment]
Yep we do - it's what was implemented for clicking the sign-up button and in the new user experience. @erictj has used it as a canon before.

**Comment by merc3po** [comment]
Here's the link to GetSatisfaction: http://getsatisfaction.com/singly

**Comment by amcjen** [comment]
The modal is all handled client-side in jquery.  I had to do some lame hacking with the new user flow in regards to cookies, to track state between Integral and Locker, so ignore that code.  But the basic handling is pretty straightforward.

**Comment by merc3po** [comment]
We have some messaging to do around this, but it doesn't belong in Locker...
