### ISSUE TITLE
Radio button should be a checkbox

### ISSUE THREAD

**Issue by kristjan** [LockerProject/Locker#638]
First it's confusing that there's a radio button with no friends, and it gets worse when it behaves like a checkbox (appears and disappears the rename field).

![](http://f.cl.ly/items/3h1m0O1T190U3T0I341R/Identity%20Crisis.png)

**Comment by kristjan** [comment]
Oops, duplicate of #518

**Comment by merc3po** [comment]
https://github.com/LockerProject/Locker/issues/518

On Thu, Jan 26, 2012 at 1:06 PM, Kristjn Ptursson <
reply@reply.github.com

> wrote:
> 
> First it's confusing that there's a radio button with no friends, and it
> gets worse when it behaves like a checkbox (appears and disappears the
> rename field).
> 
> ![](http://cl.ly/2O0R1G3b1W2F02320o3N)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/LockerProject/Locker/issues/638

## 

Merci Victoria Grace

Playful Designer + Producer

http://artserf.net
http://linkedin.com/in/merci
http://twitter.com/merci
