### ISSUE TITLE
Loading animation for the Registry

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#639]
<img src="https://dl.dropbox.com/s/dw7hn00udibb4av/loading-v4.gif">

**Comment by merc3po** [comment]
@smurthas I emailed a new one to you.

**Comment by smurthas** [comment]
@merc3po I set it load only show if loading takes more than 1000ms because it was pretty fast and mostly only showed

"l   o"

and then flashed away.

registry is faster enough that this almost never shows now, but will show in the event that the registry gets bogged down.

**Comment by merc3po** [comment]
That sounds ideal! Thanks, homie!
