### ISSUE TITLE
Startup fails when mongod has a stale lock file

### ISSUE THREAD

**Issue by jsmecham** [LockerProject/Locker#64]
If `node lockerd.js` crashes or is killed and mongo leaves a stale lock file, subsequent startups will fail with with the following error:

```
[21:23:44][Locker] lservicemanager lockerPortNext = 18042
[21:23:44][Locker][ERROR] mongod did not start successfully.

/Users/Justin/Projects/Locker/Source/lockerd.js:128
    dashboard.instance.kill(dashboard.pid, "SIGINT");
                       ^
TypeError: Cannot call method 'kill' of undefined
    at shutdown (/Users/Justin/Projects/Locker/Source/lockerd.js:128:24)
    at ChildProcess.<anonymous> (/Users/Justin/Projects/Locker/Source/lockerd.js:61:13)
    at ChildProcess.emit (events.js:67:17)
    at ChildProcess.onexit (child_process.js:192:12)
```

Adding debug output indicates that mongod has a stale lock file:

```
[21:27:37][Locker] ************** 
old lock file: /Users/Justin/Projects/Locker/Source/Me/mongodata/mongod.lock.  probably means unclean shutdown
recommend removing file and running --repair
see: http://dochub.mongodb.org/core/repair for more information
*************
```

lockerd should be aware of this possibility and provide the user with a more useful error message.

**Comment by temas** [comment]
Ran into this one too, will investigate more.

**Comment by seancron** [comment]
I'm also experiencing this issue.

**Comment by trel** [comment]
removing the lock file allowed lockerd.js to startup again.

**Comment by ctide** [comment]
https://github.com/LockerProject/Locker/commit/f1111ac13d6e9744a916f019212be47e56d4db40 should fix this most of the time.  I haven't seen a stale lock file without a running mongo any time recently, so, please reopen if you see this issue again.
