### ISSUE TITLE
Glatitude icons don't show up under Connected or More Services

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#642]
I have the same issue with pandora.

After this, is there anything stopping a republish of dashboard?

**Comment by merc3po** [comment]
I'm going to suggest we close this since Google-Latitude is not deployed to the live service, it's not actually broken.

**Comment by smurthas** [comment]
This should have been fixed with #615. @elsmorian can you confirm?

**Comment by elsmorian** [comment]
Yup! Thanks :D
