### ISSUE TITLE
Masonry viewer interprets t.co links in tweets as links to photos

### ISSUE THREAD

**Issue by othiym23** [LockerProject/Locker#646]
...even when they're just shortened links to regular web pages.

Seen in @alirayl's locker.

**Comment by quartzjer** [comment]
This should /only/ happen if the oembed data comes back with a type of
photo for the link (which if the target site is lying could happen)...
any chance you could get the relevant json from the link collection to
see the embed object?

On Sat, Jan 28, 2012 at 9:51 PM, Forrest L Norvell
reply@reply.github.com
wrote:

**Comment by alirayl** [comment]
It's fixed now.

**Comment by merc3po** [comment]
I'm opting this for review so that someone checks it 2x before closing it.

**Comment by othiym23** [comment]
Closing as resolved, eventually. 🐌
