### ISSUE TITLE
Publishing system doesn't pull submodule files within an app's repository

### ISSUE THREAD

**Issue by beaugunderson** [LockerProject/Locker#648]
I currently have [Spearmint](https://github.com/beaugunderson/Spearmint) added to my Singly instance in a draft state. It shows up in my sidebar but the publishing system appears to not have checked out the d3 submodule I've added.

Here's my `.gitmodule` file:

```
[submodule "js/d3"]
        path = js/d3
        url = https://github.com/mbostock/d3.git
```

All of the files show up except for the ones underneath js/d3 (and hence everything works but the parts that depend on d3). It would be great if git submodules were checked out with the main repo. :)

**Comment by beaugunderson** [comment]
The issue is in `Connectors/GitHub/repos.js`. The GitHub API exposes submodules as a tree node of type 'commit' with  mode '160000':

```
    {
      "type": "commit",
      "sha": "f67e89597db87f017c3d4706448ebe3ff8528853",
      "url": "https://api.github.com/repos/beaugunderson/Spearmint/git/commits/f67e89597db87f017c3d4706448ebe3ff8528853",
      "path": "js/d3",
      "mode": "160000"
    },
```

Unfortunately the URL returned by the GitHub API doesn't work (it returns 'not found'). I've opened a bug with GitHub. Once it's fixed I'll attempt to add some logic to recursively pull blobs from submodules.

**Comment by quartzjer** [comment]
Hmm, there has to be a better way to do this I think? Submodules have proven problematic in a diverse system, and d3 is ginormous as a git dep :)

What about symlinking in just the req'd files? Or a npm or git hook?

**Comment by beaugunderson** [comment]
Yeah, submodules are probably the wrong way to include something like d3, but I could see how it might be useful to support them in the future. I'll just include the necessary files from d3 at this point. :)

Here's the response from GitHub, by the way:

> Ah, I see the bug.  The URL isn't changing the repo path to match the
> submodule location.  I don't think the tree command gives us that
> info.  I'll just stop adding the URL.  I think to get the URL, we have
> to match up the commit and path to the `.gitmodules` file.  For now,
> you'll just have to pull that blob down manually and parse it to get
> that out.  I'll open an internal ticket to see about making this
> process better.
