### ISSUE TITLE
dashboardv3 shows no connectors if registryUpdate=false

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#649]
It looks like it's relying on the registry to tell which connectors are available. Even though there are connectors in the map, it's acting as if none are available.

**Comment by quartzjer** [comment]
The fix for this ended up in the regprocess branch as it was weaved into the sig validation, which I'm rallying to deploy asap :)

**Comment by mdz** [comment]
OK. Sandbox was supposed to use registryUpdate=false, but I'll just switch it off for now rather than block. Once your branch is merged in, we can switch it back

**Comment by smurthas** [comment]
We discussed this today over lunch. The behavior we really want is that if a service is pointing to the local tree, it should never update from the registry. That is now captured in #663.

**Comment by mdz** [comment]
Both #663 and this issue are fixed in regprocess

**Comment by mdz** [comment]
I believe they are distinct, though, not the same issue. This might have had the same root cause as the initial setup bug which @erictj  fixed though
