### ISSUE TITLE
"Filter by service" shows all "undefined"

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#653]
http://imageshack.us/photo/my-images/810/screenshotat20120130143.png/

**Comment by smurthas** [comment]
FWIW, this appears to only be happening in dashboard, not integral.

**Comment by mdz** [comment]
What do you mean?

**Comment by smurthas** [comment]
I mean that the bug is in locker code, not in integral code, despite the fact that they should be using the same code, implying that they are now out of sync and that we should use integral's version as a valuable diff to help find the bug.

**Comment by mdz** [comment]
@othiym23 this is the bug @smurthas was talking about just now

**Comment by smurthas** [comment]
@othiym23 I'm in this code right now and the fix is simple, so I'm going to put it in the submodule
