### ISSUE TITLE
On publish, need some copy/UI somewhere to explain that an issue is used

### ISSUE THREAD

**Issue by quartzjer** [LockerProject/Locker#657]
We create an issue automatically to track the publishing review process, need to explain that somewhere :)

**Comment by quartzjer** [comment]
This might get added in #682?

**Comment by merc3po** [comment]
What repo does the issue get created in? @quartzjer actually can you write the text for this? I'll put it in a mock in #682 :)

**Comment by merc3po** [comment]
This folds into #682, so I'm closing it.
