### ISSUE TITLE
Redirected to nonexistent Contacts Viewer after account successfully created

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#658]
I created an account on Sandbox and after choosing to "start exploring" at the end of the new-account-creation (which worked like a gem!) I was sent to a blank page: <img src="https://img.skitch.com/20120131-jaqw1pgmq34edxtay7uuycd47g.jpg">

**Comment by mdz** [comment]
I think this is the same underlying issue as #659

**Comment by quartzjer** [comment]
I'm looking at / trying to reproduce this...
