### ISSUE TITLE
Analytics v3

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#660]
Here's the project on Google docs: https://docs.google.com/a/singly.com/document/d/1V-jGW5amMROlWPTqnvCE0R7NdVR-jexMXppOMXWx3-E/edit?hl=en_US

Needs to be implemented for OPENIT.

**Comment by merc3po** [comment]
This is related work on SendGrid: https://github.com/Singly/integral/issues/72

**Comment by othiym23** [comment]
Lindsay specified what we want for OPENIT: https://docs.google.com/a/singly.com/document/d/1Pl9PquNgtmz58R4kNOcT3zJQCVRtVmuz4gIwD-qwxNk/edit?authkey=CPKk0RM&authkey=CPKk0RM

**Comment by merc3po** [comment]
I think that the doc @othiym23 references above is the best version of the story to work from.

**Comment by amcjen** [comment]
Setting this as _ready_.  Some more work to be done around a proper dashboard, but going to leave that for post-launch.  We're at least collecting the data now.

**Comment by merc3po** [comment]
Sweet! I'll do some run throughs today to make sure I can get the analytics
for a report.

On Wed, Feb 15, 2012 at 10:00 AM, Eric Jennings <
reply@reply.github.com

> wrote:
> 
> Setting this as _ready_.  Some more work to be done around a proper
> dashboard, but going to leave that for post-launch.  We're at least
> collecting the data now.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/LockerProject/Locker/issues/660#issuecomment-3985374

## 

Merci Victoria Grace

Playful Designer + Producer

http://artserf.net
http://linkedin.com/in/merci
http://twitter.com/merci

**Comment by amcjen** [comment]
awesomesauce.  Do let me know if anything looks amiss.  Remember too, our analytics are all over the place--we probably ought to create another story of collecting all that data from everywhere and getting it into a single user dashboard. (I started work on this already, but it won't be done in time for the launch)
