### ISSUE TITLE
Devdocs: Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#662]
```
/Me/devdocs/js/common.js:45Uncaught TypeError: undefined is not a function
```

**Comment by quartzjer** [comment]
I started looking at this, and there is a lot of broken logic in the devdocs index page now beyond just this error, I'm wondering what this page actually needs to do now?

**Comment by smurthas** [comment]
This will be completey revamped, so don't worry about this error.
