### ISSUE TITLE
'CREATE' returns internal server error

### ISSUE THREAD

**Issue by othiym23** [LockerProject/Locker#667]
Filing as a Locker issue, although the problem may actually lie with Integral.

![busted locker](https://img.skitch.com/20120131-bgcq7rafi7aurgmwga3tys2qqi.jpg)

**Comment by smurthas** [comment]
I can't reproduce this. Could you check the log files and provide a bit more info?

**Comment by merc3po** [comment]
I also haven't been able to reproduce this, so I'm going to close it. We can re-open if it appears again.
