### ISSUE TITLE
An app's "code on github" link should be populated automatically

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#676]
Currently it is specified in the package.json, but that is easy to set incorrectly: 

<img src="https://img.skitch.com/20120203-krt7cfshbjes1m9icrem22t7ug.png">

**Comment by merc3po** [comment]
Updated w/ a more recent screenshot

**Comment by smurthas** [comment]
There's not actually any UI work for this issue. Just need to update the publish scripts to auto-fill that correctly.

**Comment by merc3po** [comment]
Yeah just trying to avoid any confusion. :)

**Comment by smurthas** [comment]
done.
