### ISSUE TITLE
Add more context to Create Account flow

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#680]
(This shows the experience at 1024width resolution.)

Screen 1 of the account creation flow
<img src="https://img.skitch.com/20120202-m2ge7w7rk5a4y2y45dkan6hbjb.png">

Screen 1, "Learn more" 
<img src="https://img.skitch.com/20120202-t4xgpypm11rkn8wuf31nxynq5u.png">

Screen 2, see more services and show that we're getting Twitter w/out indicating a specific state "done" as per @temas' comment 
<img src="https://img.skitch.com/20120202-uujdwefrbx242yb9js46ai64k.png">

**Comment by amcjen** [comment]
This is in the settings-ui branch, so once that's merged with master, this feature should show up.
