### ISSUE TITLE
Publish UI should be read-only

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#682]
It is confusing to have a package.json and have "local" changes within the locker (from the publish screen). This screen should be for information checking only and have links to documentation about how to package and publish. Values should simply pass through from the package.json and a screenshot.png should be required as part of the app itself.

<b>Requires #689 and #700 to be done first; #707 is related but can be done at any time.</b>
1. Get to the Publish UI from the app-header of the app you're developing: 
   <a href="https://img.skitch.com/20120202-b9g6jyb7hmp2t633wkauafk7d.png" target="_blank"><img src="https://img.skitch.com/20120202-b9g6jyb7hmp2t633wkauafk7d.png"></a>
2. Fields are not editable:
   <a href="https://img.skitch.com/20120202-x2m1wd98es61853bu47297ea33.png" target="_blank"><img src="https://img.skitch.com/20120202-x2m1wd98es61853bu47297ea33.png"></a>
3. Fields show error states:
   <a href="https://img.skitch.com/20120202-ejf3rtkqdk1pgpwj941g2j2fwn.png" target="_blank"><img src="https://img.skitch.com/20120202-ejf3rtkqdk1pgpwj941g2j2fwn.png"></a>
   <b>NEEDS TEXT FOR EACH ERROR TYPE AND LINKS TO DOCUMENTATION</b>
4. If you want to get out of this screen without submitting your app, click either on the title of the app under "Your Apps" or click on the breadcrumb showing "Your App" and you will be taken back to seeing your app displayed in the EXPLORE section.
   <a href="https://img.skitch.com/20120202-p2yxpauhwqwh4m915e44pg42ep.png" target="_blank"><img src="https://img.skitch.com/20120202-p2yxpauhwqwh4m915e44pg42ep.png"></a>
5. After you submit the app, you are taken back to the app on Explore. You see a confirmation modal with a URL to the just-created issue on Github. The "publish" button is now inactive.
   <a href="https://img.skitch.com/20120202-84pr13f9akq1ee5pw3xi3jrnnj.png" target="_blank"><img src="https://img.skitch.com/20120202-84pr13f9akq1ee5pw3xi3jrnnj.png"></a>

**Comment by quartzjer** [comment]
I'm starting on the parts of this that happen inside the frame, also related is #693 as the docs to link to.
