### ISSUE TITLE
New DEVELOP section

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#684]
Structure + content captured in **Sections**. @merc3po, if you can put together a mock for the HOW IT WORKS page (content in the doc), that would be great - let me know if you need more info.

https://docs.google.com/a/singly.com/document/d/1fLsNmTW3_3mUO-8yGrL8ad395jHclO6i3Dnbx1SPJww/edit?hl=en_US&authkey=CKWQ79EB

**Comment by merc3po** [comment]
How It Works - Getting Started
<img src="https://img.skitch.com/20120202-xqr5wb1hsjhjwgt17t13mwidk.png">

Documentation - Build an App!
<img src="https://img.skitch.com/20120202-gy9axt4913a37292c78awkejam.png">

**Comment by merc3po** [comment]
This is getting broken into different, smaller issues: #689, #690, #691, #682, #693, #694, #695, #696, and #652
