### ISSUE TITLE
Faster updates from GitHub app repos

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#685]
For repos that are apps, we should be getting updates faster.  For lockers exposed on a public url, we should be able to use http://developer.github.com/v3/repos/hooks/.

Could also use faster polling from GitHub when present in the dashboard or something like that, but IMO the repos push API is very straightforward and we need to address push soon anyways.

Total alternative: manual sync button(s) on publish page (and possibly a few others)

**Comment by othiym23** [comment]
@quartzjer is going to add a Sync button to the publish page. This will  be good enough for OPENIT, but the rest of this is future work.

**Comment by quartzjer** [comment]
I did the work in #771, going to re-milestone this now.

**Comment by smurthas** [comment]
We can either do use the GH push API or add more sync now actions (i vote for the former), but many people are still having trouble getting things in a reasonable amount of time, so I'm moving this to be high priority

**Comment by quartzjer** [comment]
I'd vote for asap a simple visible sync button first, and defer the github push stuff a little longer, the external/api/token stuff will likely evolve in the next few weeks and could cause some regression on a push route now.

**Comment by merc3po** [comment]
@quartzjer Here's a mock showing a "sync Github" button in the UI: 
<img src="http://cl.ly/1V3M463X001H1h0p152K/Screen%20Shot%202012-03-05%20at%2011.40.28%20AM.png">

**Comment by kristjan** [comment]
User feedback!

> Syncing with Github was an odd process, but I see you have a big button for it now. That’s great.
