### ISSUE TITLE
No more js/config.js for developing from file://

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#686]
More often than not, this results in an API getting checked into someone's repo. There are lots of options here.

My thought, a simple JS library that just wraped jquery's getJSON method if run from within a locker, or creates a hidden iframe loaded from the locker and uses postMessage to do ajax from within the iframe, avoiding the cross origin stuff altogether.

**Comment by smurthas** [comment]
This is just about the simplest proposal that I could come up with: https://gist.github.com/1781534

First bit would be a file hosted that all app would include, second bit is just a simple usage example, just create a Singly client and make API calls. It will do a simple javascript prompt for an API if the protocol is `file:` and then save it to sessionStorage (so that it clears when the browser is closed, for security).

I have seen almost every single app dev mistakenly git add thier config.js file, and there expose their API key to the whole world. Also, .gitignore is just yet another step for a (not-so-git-friendly) dev to mess up (hell, I've even included my API key a few time by accident).

**I'd like to make this happen as fast as possible** - it will make a **huge** difference in the simplicity of the development experience and documentation.

Any thoughts?

**Comment by quartzjer** [comment]
Looks good, +1 here, only thing I'd suggest is making it API() or something more generic, not using Singly() :)

**Comment by smurthas** [comment]
Ya, I thought about that. It's a bit generic, but I think it will work.

**Comment by othiym23** [comment]
+1, but in contrast to @quartzjer I like the idea of having it be named Singly(). Too many generic APIs out there already!

**Comment by quartzjer** [comment]
I've had problems in the past with using company and/or possibly trademarked names in code, always good to avoid and be generic if possible, esp if the symbol will be hard-wired for a long time :)

**Comment by othiym23** [comment]
That's a good point -- maybe we can give it a non-Singly but still distinctive name. I suggest Trukkknutttz!

**Comment by beaugunderson** [comment]
I like this, but checking for the 'file:' protocol might be too narrow (it excludes people using their own webservers, which is how I work). I think checking for the 'file:' protocol or a non-singly domain would make this work for both uses cases. :)

**Comment by smurthas** [comment]
the problem with a non-singly domain, is that running in a local (development) locker on localhost or lvh.me will force you to enter an api key. What I'll do is move the baseUrl out a a global, so that you can use a config.js still to set it for local development if you want to run behind a local server and it won't override.

**Comment by smurthas** [comment]
This is merge into master. Further improvements can be new issues.
