### ISSUE TITLE
Reorganize leftnav

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#689]
Sections: 

YOUR APPS
Apps you're developing, allows you to preview them
Apps stay here even after they're published

INSTALLED APPS
Apps you've installed

CONNECT MORE SERVICES
Services you can connect, full opacity

YOUR CONNECTED SERVICES
Services you've connected with your Singly account; 40% opacity

Leftnav you don't have any apps in development:
<img src="https://img.skitch.com/20120202-k9312b7anmdptgku75wpsr2jxb.png">
<img src="https://img.skitch.com/20120202-mx3mmhrw5xj59uqq8py42btf23.png">

Leftnav if you have one or more apps in development:
<img src="https://img.skitch.com/20120202-etim5nhhbuqsn2k965r4yaa1aa.png">

**Comment by merc3po** [comment]
Here's the corresponding version for Integral: https://github.com/Singly/integral/issues/173

**Comment by smurthas** [comment]
An important point here, all the drop down details are to be removed from the left nav. They will be put back in with #700.
