### ISSUE TITLE
Header reorganization/renaming

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#690]
Rename sections as follows: 
You --> Explore
Explore --> App Gallery
Create --> Develop

Add 50px of buffer (currently set at 20px) between the leftnav and the rest of the chrome. (see mock below)
<img src="https://img.skitch.com/20120202-kq3xe6wudajeiu6p67bgp5r3ej.png">

**Comment by smurthas** [comment]
@merc3po Seems like on integral these should be

`| ABOUT | APP GALLERY | DEVELOP`

sounds good?

**Comment by merc3po** [comment]
Yeah sounds good. I think that's an entirely separate story, redoing the left-nav and the header for integral. I'll look into it.

**Comment by merc3po** [comment]
Here's an issue for the Integral version: https://github.com/Singly/integral/issues/172

**Comment by smurthas** [comment]
done.
