### ISSUE TITLE
New navigation in Develop section

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#691]
Light gray (F2F2F2) box extends all the way to the edge of the page. 
Contains links to documentation
Navigation is persistent, documentation pages load underneath it.
Links show in columns

Here's the same nav on Integral: https://github.com/Singly/integral/issues/191

<b>Here are the links and the content they link to: </b>
Build an App! (see #696)
API Explorer (loads existing page below the nav)
Publishing on Singly (#693)
Forums (link to here: http://forums.singly.com)
Chat with the team! (loads existing page below the nav)
Templates + Icons (loads existing page below the nav)
The Locker Project (links to http://lockerproject.org/)
Help + FAQ (links to here: http://forums.singly.com/discussion/2/request-features-and-report-bugs#Item_1)

<img src="https://img.skitch.com/20120208-mjwq9wx754yfbf5iajtc17yj5n.png"

**Comment by merc3po** [comment]
Realized we don't need #727...

**Comment by merc3po** [comment]
Took out the "Example Apps" section from this nav - we'll get to it later.

**Comment by amcjen** [comment]
Will need the content for the following pages:

Chat with the team! 
Templates + Icons

**Comment by amcjen** [comment]
Example Apps has been removed

**Comment by merc3po** [comment]
Those pages both exist already on our current Singly.com. 

Here's "Chat with the team!" - which I'd like to change to "Find us on IRC" - https://singly.com/#Develop-Chat
And here's Templates + Icons - https://singly.com/#Develop-TemplatesIcons

**Comment by amcjen** [comment]
Where do those pages live?  They look like they're in integral?

**Comment by merc3po** [comment]
Yeah they're on integral but that information should also be accessible when someone is signed-in.

**Comment by amcjen** [comment]
N/m, I brought them over.  Good to go! This story is ready for review/close :)

**Comment by merc3po** [comment]
Fuck yeah!
