### ISSUE TITLE
Rewrite "Develop Locally" as "Build an App"

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#696]
It goes on this page under the develop-nav

<img src="https://img.skitch.com/20120204-95ujcgrsnk22twggbjtr4gefx.png">

**Comment by smurthas** [comment]
realistically, this page will change quite a lot when we do #686, but for now, I can take the Develop Locally page, bring it up to date and style it.

**Comment by merc3po** [comment]
Sweet. :)

**Comment by smurthas** [comment]
done!!!
