### ISSUE TITLE
Rename all pre-installed apps to DEMO

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#701]
When you first start your account, you should have four apps pre-installed. These apps should be renamed to demonstrate that they are the "demo" versions of the apps. 

Masonry = DEMO Photos App
Linkalatte = DEMO Links App
Hello Places = DEMO Places App
Basic Contacts = DEMO Contacts App

What the account holder sees when they arrive at their account for the first time:
<img src="https://img.skitch.com/20120202-84bqqwbsxkhpjj5ucb386drdhq.png">

**Comment by temas** [comment]
If we're only picking one demo photos app to start with, should it be masonry or timeline?

**Comment by merc3po** [comment]
Masonry (I wrote them all in the issue description above.)

**Comment by merc3po** [comment]
Oops

**Comment by temas** [comment]
Doh, precoffee brain on that one ;)
