### ISSUE TITLE
App details view updates

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#702]
App details view of DEMO Photos Apps, an app that has already been added to the account.
Includes:
<b>Title
Author
Data type ("with ____ from")
Icons of the services
Link to Github code
Description
Version #
Action button
<img src="https://img.skitch.com/20120203-8h9gy5ey4439534jn8csmu2e1b.png">
1. Add an app (button state changes)
2. App moves to top of the list in "INSTALLED APPS" section of leftnav 

Here are the button states:
<img src="https://img.skitch.com/20120203-dhg23pyse5inteb9hgiiwneq6w.png">

**Comment by merc3po** [comment]
Not closing this yet, it's missing stuff
<img src="https://img.skitch.com/20120213-ximqaumm99xshkwsnufdec9efh.png">

**Comment by smurthas** [comment]
@merc3po I merged in the pull requests from @beaugunderson, can you confirm everything looks right and if so, close the issue?

**Comment by merc3po** [comment]
@smurthas is this on sandbox? I don't see it there.

**Comment by smurthas** [comment]
I don't know. It's merged into master.

**Comment by smurthas** [comment]
This is done
