### ISSUE TITLE
App card improvements

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#703]
An individual card, showing: 
<b>Title
Author
"This app uses:"
Icons of the services the app uses
A small screenshot</b>
<img src="https://img.skitch.com/20120203-f7m9etru96rgtkepsai25sfnbc.png">

An individual card, showing the hover state of the card (clicking opens the app details page seen in #702):
<b>Gradient goes from #CCCCCC to #E6E6E6 and back to #CCCCCC</b>
<img src="https://img.skitch.com/20120203-gywus75a6f5embjsd2k5k4j83i.png">

How the cards look in the App Gallery:
<img src="https://img.skitch.com/20120203-gwwqq31gmmiq62d43g2m3nsbjk.png">

**Comment by beaugunderson** [comment]
@merc3po It looks like the icons in the mock are a size between 24px and 32px; I used 24px because 32px was a tad too big

I also just realized that the cards should get a tad less wide than they are now according to the mockup

![screenshot](http://i.imgur.com/a0RGY.png)

**Comment by temas** [comment]
Done on shared-ui submodule.
