### ISSUE TITLE
Move filter functionality to top of App Gallery

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#705]
Use the same light gray box as in #691 as the background for the existing filtering functionality in the App Gallery. 

Showing the filters:
<b>Click "Hide filters" to toggle off</b>
<img src="https://img.skitch.com/20120203-tt3mr7w185aacxp8cdgmkud4d3.png">

Using the filters:
<b>Removing breadcrumbs for filters: the apps will just display below the filters but the breadcrumbs will no longer change to show the filters</b>
<img src="https://img.skitch.com/20120203-c3smf8phjj51afudu2qpqf756.png">

Hiding the filters:
<b>Click "Show filters" to toggle on</b>
<img src="https://img.skitch.com/20120203-rjc4wk8ck9sayca977qwa1wifq.png">

**Comment by beaugunderson** [comment]
Is there any CSS hotness for the rounded blue checkboxes yet? (If not I'm confident I can whip some up)

**Comment by beaugunderson** [comment]
It's all there except the blue checkboxes... Wanted to do some more research into a good crossbrowser way to implement them. Also, this is a big change and needs to be well-tested. :)

**Comment by temas** [comment]
Done by Beau
