### ISSUE TITLE
Embiggen app cards, add the "Add to Account" button

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#708]
App card, default state: 
<img src="https://img.skitch.com/20120203-2m27jirsp66u3x9hegk7jky5q.png">

App card, hover state on both the card and the button:
<img src="https://img.skitch.com/20120203-r61r84bn9eij1dp624jq758r9w.png">

App card, hover state on just the card:
<img src="https://img.skitch.com/20120203-j4rmsrwtm38yj9xgbihe88ygj.png">

App card, app has already been installed:
<img src="https://img.skitch.com/20120203-ngmkgdm11i3niinb6bgqgm9i51.png"> 

Here's what the states look like in the App Gallery: 
<img src="https://img.skitch.com/20120203-pmfr4t7rmbxhs8nwgusnrsna8d.png">

**Comment by temas** [comment]
Done by Beau
