### ISSUE TITLE
Account-creation button states not working

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#715]
In addition to the text changes on #714, the styling of the buttons isn't working.  #714 probably needs to be done first.

<b>
Correct behavior is:  
button changes to 40% opacity
word "Create" becomes "Creating" 
</b>

Currently on sandbox, the button does lose opacity and the word is different/doesn't change.

**Comment by smurthas** [comment]
does this happen anywhere that I should use as an example?

**Comment by merc3po** [comment]
So the text change should happen on Publish UI too, but the opacity issue is more pressing (since you end up pressing twice and then it gives you a JS window error) and impacts the sign-up flow.

**Comment by smurthas** [comment]
this was an integral issue. fixed now.
