### ISSUE TITLE
Text "No app like that exists...yet." Repeated

### ISSUE THREAD

**Issue by bassdread** [LockerProject/Locker#724]
Select a filter on Apps page (https://me.singly.com/dashboard/appGallery#AppGallery-Filter?&services=lastfm) for service with no apps and "No app like that exists...yet. Why don't you create the first?" is repeated.

**Comment by bassdread** [comment]
http://twitpic.com/8gfcm3 shows the duplicated text

**Comment by beaugunderson** [comment]
This no longer happens with the new filtering code :)
