### ISSUE TITLE
Github not pulling down all files

### ISSUE THREAD

**Issue by temas** [LockerProject/Locker#725]
The github synclet seems to not always pull down a complete set of files from a repository.  If it can only pull down a partial set it should not cache the last timestamp of the repository so that it can try again later to finish getting the files.  Currently the cached time gets set and the file state is stuck.  This could also be smart and schedule itself to run again more quickly to finish fetching.

**Comment by smurthas** [comment]
(from #747)

apps are showing up in the top left nav, but they haven't been properly synced. http://bit.ly/Ati1ux

The actual repo code: https://github.com/smurthas/PhotosViewer
What got synced to disk: http://bit.ly/yMzmHI (just package.json, css, and .gitignore)

If it doesn't pull down every single file successfully, it **definitely** shouldn't upsert into the map

**Comment by kristjan** [comment]
Same problem on https://github.com/kristjan/prolific_posters

Got package,json, css, .gitignore and README.md: http://cl.ly/1W3n3m1x2a1w290D1g2k

**Comment by smurthas** [comment]
Oh, interesting. That seems like it might be a bug in our code if we both only got the css dir?

**Comment by smurthas** [comment]
I still see this after a repos sync: http://bit.ly/wStr1N and only have package.json, css, and .gitignore.
Additionally, even after a "bad" sync, I still see the SHAs in the PhotoViewer.tree.json file: https://gist.github.com/1819841
I also, see them as being cached in the me.json file: https://gist.github.com/1819888

This is really, really important to get right as it is the only mechanism for publishing, and I am routinely seeing it break.

**Comment by smurthas** [comment]
@quartzjer I'm assuming you we're assigned to this just because of carry over from before. I'm going to take a look at it since I can easily repro it locally.

**Comment by quartzjer** [comment]
I thought I fixed this and closed it, wtf

On Mon, Feb 13, 2012 at 3:41 PM, Simon Murtha-Smith
reply@reply.github.com
wrote:
