### ISSUE TITLE
GLatitude connection popup is empty

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#734]
On a brand new locker, clicking connect to connect GLatitude popups a blank popup where the Google OAuth stuff is supposed to be. No errors are output. Popup address is about:blank.

**Comment by merc3po** [comment]
@erictj is Google Latitude part of the main product now? If so, let's fix this for OPENIT.

**Comment by elsmorian** [comment]
I'm not sure when this was fixed, but it now is! Thank-you mystery coding elf!
