### ISSUE TITLE
Missing first screen of new account experience

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#739]
Currently on Sandbox, you go immediately to the complete list of apps. 

In the spec for the New Account Experience, it shows a screen w/ just Twiter + Facebook as your initial choices for creating an account. The reason for this is that Twitter and Facebook have enough data to populate the four demo apps, whereas if you just sign up with Fitbit or Pandora or Foursquare, you won't be able to explore your data. 

First screen, now
<img src="https://img.skitch.com/20120208-p1fi82fuwb1jq2qd594xxaxexn.png">

**Comment by amcjen** [comment]
hm, this used to work.  Must've reverted.  I'll fix
