### ISSUE TITLE
Instagram photos not loading in my Locker

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#741]
Looks like this: <img src="https://img.skitch.com/20120208-dfac3ry8puwkimqdj86k2i6fc.png">

**Comment by quartzjer** [comment]
I've reproduced and it seems like crazytime, the 302 to redirect to the HTTP url for the image SOMEHOW gets turned into an HTTPS along the way

**Comment by quartzjer** [comment]
Seriously. Seriously?! https://github.com/elfsternberg/node-http-proxy/blob/411bb51cc6/lib/node-http-proxy/http-proxy.js#L216

**Comment by quartzjer** [comment]
fixed in integral using my fork w/ the bad logic commented out for now

**Comment by quartzjer** [comment]
filed as an issue at https://github.com/nodejitsu/node-http-proxy/issues/192 too
