### ISSUE TITLE
Empty modal

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#745]
I see this all the time. Right now I have GitHub connected. Seems as though the "Connect" screen and "Got It" modal aren't quite figuring out whether I have services connected all the time?

http://bit.ly/w6Vz2x

Adding to USEIT because I see it ALL THE TIME, but if I'm the only one, then we can move it to OPENIT.

**Comment by othiym23** [comment]
You are not the only one. I get it a lot when using the back button, so maybe it's a weird interaction between our code and jQuery.history.

**Comment by kristjan** [comment]
Seems to happen not when I click on a Develop age, but when I reload one

**Comment by smurthas** [comment]
Yes, I also get it on reloading.

**Comment by merc3po** [comment]
I'm getting this all the time, too. Both clicking around the develop section and it's still there when I reload. I have to sign out and back in to get rid of it. Happening on Sandbox.
