### ISSUE TITLE
Can still get to other pages when no services are connected

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#746]
http://bit.ly/xfJ2SP

**Comment by othiym23** [comment]
Simon clicked away during the signup process, before he'd connected any services.

Let's make connecting services during initial setup modal. It should not go away until you connect something. After you connect one, you still have the chance to connect more before you dismiss it.

**Comment by smurthas** [comment]
@erictj I'm hesitant to touch this while you are adding analytics because this seems like it will be part of it - is that true?

**Comment by kristjan** [comment]
This might be covered by the fix to #764. No links are visible until you've connected something besides Github. There are two things that are still a little irritating:
- There is a moment before the navs vanish when you could quickly click them
- You can click your avatar/name, which has the effect of reloading the page

**Comment by quartzjer** [comment]
The essence of the original issue is definitely fixed so I'm going to close this, those other quirks feel like polishing a marshmallow, but if they become an issue and not addressed anywhere else they can get filed on their own...
