### ISSUE TITLE
History doesn't work on DEVELOP section

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#750]
@erictj sorry if you are still working on this. I just noticed it and wanted to make sure it doesn't get forgotten.

**Comment by amcjen** [comment]
Is there something special I need to do for saving the nav in DEVELOP to the $.history?  I've never used that plugin before.

**Comment by mdz** [comment]
I reverted 664c07f because it broke the build in CI and I didn't know how to fix the failing test

**Comment by quartzjer** [comment]
YAY done
