### ISSUE TITLE
Confusing experience without any data

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#751]
When using an app for which there is no data, things are pretty confusing: http://bit.ly/ytOd3K

We solved this before by checking the uses.types info and seeing if those collections had any data. If they didn't we would show a splash page, which could be a call to action to add services for which there are, in this case, photos.

@merc3po assigning to you as this will need some UX thought before we can do anything.

**Comment by merc3po** [comment]
Ah yeah totally. I'll work on this.

**Comment by merc3po** [comment]
@smurthas do you have a screenshot of the old splash page? I never saw it.

**Comment by smurthas** [comment]
It wasn't very good. didn't have alls to action or anything just said something like "Singly makes you data great!".

**Comment by merc3po** [comment]
Created #770
