### ISSUE TITLE
Dashboard on iceweasel/firefox 3.5.19 does not work

### ISSUE THREAD

**Issue by alanz** [LockerProject/Locker#76]
The dashboard does not update the main panel on the right when the links on the left are clicked.

Just FYI

**Comment by alanz** [comment]
Note: head checkout today, using dev branch

Hence https://github.com/quartzjer/Locker/commit/f35ae5c781ad30ab0f544875e3a7e84cec6f8d2f

**Comment by jsmecham** [comment]
See http://github.com/quartzjer/Locker/pull/79
