### ISSUE TITLE
Half connect screen / half explore screen

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#764]
after connecting 1 service, refreshing the page (or closing and reopening) does this: http://bit.ly/zPG1f1

**Comment by kristjan** [comment]
This appears to have been subsumed by another change. Now when you first install, you immediately see the list of all available connectors.

**Comment by smurthas** [comment]
This is still there: http://bit.ly/zwUn1i

rm -r Me
./locker
goto: /dashboard/explore#Explore-connect
connect GitHub
click the orange Start Exploring link

**Comment by smurthas** [comment]
Also, if you then click an app, the header doesn't return: http://bit.ly/yXWWdX

**Comment by smurthas** [comment]
looks like the Start Exploring link points to /dashboard/contactviewer, which isn't a valid path.
