### ISSUE TITLE
Scheduler errors on invalid service IDs

### ISSUE THREAD

**Issue by temas** [LockerProject/Locker#77]
[09:28:59][Locker][ERROR] Attemtping to spawn an unknown service 6d88880637edced8137c7d68e73fd329

When a service has been removed and there is still an entry in scheduler.json it errors and continues on.  Might want to consider making this a silent error.

**Comment by smurthas** [comment]
the real problem right now is when this happens, the callback is not removed from the scheduler, so it continues to display every time the locker is launched. Really, what is needed is a proper service disable feature, which also removes scheduler, etc.

**Comment by smurthas** [comment]
While running tests I got the following error:
      Scheduler Issue #77 - Scheduler errors on invalid service IDs
        ✗ is resolved
          » expected null, got '{"at":"1970-01-01T00:41:40.000Z","type":1,"serviceId":"foursquare","url":"/whatever"}\n' // lscheduler-test-local.js:72

I am unable to reproduce it, but perhaps there is a race condition somewhere in either the test. In fact, the test itself has a comment that suggests there might be a race condition.

**Comment by smurthas** [comment]
Still there - perhaps we need to reconsider how this test works.

**Comment by ctide** [comment]
Fixed!
