### ISSUE TITLE
Leftnav not showing up in App Gallery

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#772]
Not sure why this is happening - the leftnav should be consistent across all sections of the site now. (The "featured" section should no longer appear.)

<img src="https://img.skitch.com/20120209-k58r8u5i264dt465mm8pmw7gs2.png">

**Comment by beaugunderson** [comment]
As for the 'why': at the time I took filtering out of the existing left navigation there wasn't new sidebar content to replace it yet--and the App Gallery depended on there being at least one app (in this case the 'Featured' app) listed in the left-hand navigation to serve as the default app when one wasn't specified. :)
