### ISSUE TITLE
Open "Forums" link in a new tab

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#773]
Apparently the usability testers are wary of opening something that they think won't open in a new tab if it's off-site. Also, if you try to open it in a new tab by holding "command" while you click (on a Mac), it does not work. Seemed weird.

**Comment by kristjan** [comment]
The lack of Cmd-click behavior is because there's a JS handler on all those links. Do you think opening external links in new windows is good enough, or would you like to put in the effort to fix behavior when they do more than just click?
