### ISSUE TITLE
"Your locker" should be "Your Singly account" 

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#774]
We're not using locker as a user-facing word, at LEAST not during the account creation flow.

Your Singly account saves the data from these services data for you, it doesn't post to them (unless you explicitly ask!).

Your Singly account saves and normalizes your data from these services so that, for instance, your contacts from Twitter, Facebook, Instagram, Flickr, etc. are all saved in your individual account for you. Once you've added data from these services to your account, you'll be able to add apps that let you see that data in new, cool ways.

**Comment by kristjan** [comment]
This is working for @mdz but not me. So this issues is closed, but something else is funny.

**Comment by mdz** [comment]
The "something else" was puppet being broken on one of the backend servers (now corrected).
