### ISSUE TITLE
Super slow weirdness on Sandbox

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#775]
I'm getting (random) pages loading ~2 minutes on a consistently inconsistent basis. Based on the JS error console it appears to be different files each time. 

On this particular page load, /develop [dashboard] loaded after 2 minutes, but then these weird little files kept loading until I killed the page after ~7 minutes. 

If we could investigate and kill this before usability testing that would be rad, since it's about every third or fourth page I load that takes at least 2 minutes to load.
<img src="https://img.skitch.com/20120209-t7daejq8rjae2wmayj2kbqykjk.png">

**Comment by temas** [comment]
Very odd, seeing this as well.  Investigating.

**Comment by temas** [comment]
I can replicate this by hand with openssl s_client -connect localhost:443 and sending it a valid request.  It hangs for a long time.  The same request sent directly to my locker is immediately served.  So that definitely isolates this as an integral issue.

**Comment by quartzjer** [comment]
I'm on gogo, but haven't seen anything take more than the expected 10-20sec expected here.

**Comment by temas** [comment]
Again it's gone again.  The intermittent nature of this is annoying and not allowing me to isolate it.

**Comment by temas** [comment]
Other tidbits I've been able to verify
- The integral front end still responds while it is hung
- System network settings are as expected
- Number of sockets in use is low relative to listen queues and http-proxy settings
- Locker is responsive during a hang

Just realized the slya-proxy is running on sandbox so looking down that route some.

**Comment by mdz** [comment]
This should be fixed by 1a539c0e065f76555e402f118e96887b55a1c3b6 in slya-proxy. Please reopen if it recurs.
