### ISSUE TITLE
Roll out LinkedIn

### ISSUE THREAD

**Issue by othiym23** [LockerProject/Locker#776]

**Comment by mdz** [comment]
This includes at least:
- getting a LinkedIn API key for sandbox
- adding it to sandbox's apikeys.json
- confirming LinkedIn works properly on sandbox
- getting a LinkedIn API key for production
- adding it to production's apikeys.json
- restarting all production accounts

**Comment by mdz** [comment]
None of this work is actually in Locker, interestingly, but we don't have a better place for it at the moment

**Comment by merc3po** [comment]
This doesn't seem like it needs to be done for OPENIT, right?

**Comment by mdz** [comment]
@merc3po agreed

**Comment by othiym23** [comment]
Closing as abandoned. 🌁
