### ISSUE TITLE
Intermittent Error when sending twitter contact

### ISSUE THREAD

**Issue by corntoole** [LockerProject/Locker#778]
The following error: `TypeError: Object #<Object> has no method 'connectToMongo'` keeps occurring in my local instance of Locker when attempting to send a contact to the database
Here is my environment info:

```
timbuktu-2:Locker corntoole$ ./checkEnv.sh 
Python version 2.6.1 found.
Node.js version 0.6.8 found.
npm version 1.1.0-2 found.
mongoDB version 1.8.2 found.
```

Here is a paste of the error:

```
9 Feb 18:56:41 - error: There was an error sending contact://twitter/contact?id=twitter#16582786 new to         http://localhost:8042/Me/797a6b19a98d9711c299bd7d8feb202f/events got Error: socket hang up
9 Feb 18:56:41 - info: Having to spawn 797a6b19a98d9711c299bd7d8feb202f
9 Feb 18:56:41 - info: spawning into: /Users/corntoole/Code/external-    proj/git/Locker/Me/797a6b19a98d9711c299bd7d8feb202f
[797a6b19a98d9711c299bd7d8feb202f] The "sys" module is now called "util". It should have a similar interface.
[797a6b19a98d9711c299bd7d8feb202f] 
/Users/corntoole/Code/external-proj/git/Locker/Collections/Contacts/contacts.js:126
locker.connectToMongo(function(mongo) {
       ^
[797a6b19a98d9711c299bd7d8feb202f] TypeError: Object #<Object> has no method 'connectToMongo'
    at Socket.<anonymous> (/Users/corntoole/Code/external-proj/git/Locker/Collections/Contacts/contacts.js:126:12)
    at Socket.emit (events.js:67:17)
    at Pipe.onread (net.js:347:14)
```

**Comment by quartzjer** [comment]
It looks like perhaps you have had your locker directory around since
last summer or before?  The hash code in there has to be from back
then, and I don't think that old of a Me/ directory is likely to work.

Is there data you want to keep in your Me/ directory? If not, you
should rm -rf Me/ and start over, if there is let me know and I'll
help you clean it up by hand over IRC/IM :)

On Thu, Feb 9, 2012 at 7:24 PM, Cornelius Toole
reply@reply.github.com
wrote:

**Comment by quartzjer** [comment]
Maybe not rm -rf Me/ but just "mv Me Me.old" so you don't loose it
just in case :)

**Comment by corntoole** [comment]
I renamed the directory and that seems to have fixed that issue. Thanks.
On the data recovery issue, I'm sure a good bit of the data (e.g. twitter timeline) got re-downloaded, but I would like to know how to recover it.
