### ISSUE TITLE
Hanging requests when proxying keepalives to dashboard

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#780]
ab -k -n 1000 http://localhost:8042/core/revision # core endpoint - behaves normally
ab -k -n 1000 http://localhost:8042/dashboard/js/dashboard.js # proxied static content - hangs
ab -n 1000 http://localhost:8042/dashboard/js/dashboard.js # without keepalives - behaves normally

**Comment by mdz** [comment]
@quartzjer suspects node-http-proxy

**Comment by mdz** [comment]
@merc3po I think this is the issue you noticed on sandbox (it is easily reproduced locally or on production as well)

**Comment by mdz** [comment]
I tried rolling back to node 0.4.9 and http-proxy 0.7.0 and the issue is still present there

**Comment by mdz** [comment]
Reproducible as far back as e5cb98a218ea451ded6187883028a7adf0b6ee98 so far

**Comment by quartzjer** [comment]
See #781, I did a bunch more testing and have found out ab and node don't get along, and tried to reproduce using seige and httperf which both worked fine here, no random lags or hangs regardless of changing keepalives and concurrencies.  Going to close this as well, seems like a dead end on the possible hang :(
