### ISSUE TITLE
Slow performance when proxying keepalives to devdocs

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#781]
ab -k -n 1000 http://localhost:8042/core/revision # core endpoint - behaves normally
ab  -n 1000 http://localhost:8042/Me/devdocs/js/common.js # proxied static content - behaves normally
ab -k -n 1000 http://localhost:8042/Me/devdocs/js/common.js # with keepalives - very slow!

**Comment by mdz** [comment]
@quartzjer suspects node-http-proxy

**Comment by mdz** [comment]
I tried rolling back to node 0.4.9 and http-proxy 0.7.6 and the issue is still present there

**Comment by quartzjer** [comment]
I tried a bunch of things and while I did see some strange differences, it depended a lot on what system I was using ab on and if it was over the network, often there was no difference.

I've found numerous suggestions that ab doesn't work with node, one of the examples: http://www.subbu.org/blog/2012/02/benchmarking-node-js-0-6-x-or-later

I tried siege and httperf and couldn't reproduce this either of them, so I'm going to close this for now.

**Comment by mdz** [comment]
I can reproduce this with wget easily:

tutti:[~/src/singly/Locker] time (count=250; while [ $count -ge 0 ]; do wget -q -O /dev/null http://localhost:8042/core/revision; count=$(($count-1)); done)
( count=250 ; while [ $count -ge 0 ]; do; wget -q -O /dev/null ; count= ; done  0.30s user 0.74s system 49% cpu 2.095 total
tutti:[~/src/singly/Locker] time (count=250; while [ $count -ge 0 ]; do wget -q -O /dev/null http://localhost:8042/Me/devdocs; count=$(($count-1)); done)
( count=250 ; while [ $count -ge 0 ]; do; wget -q -O /dev/null ; count= ; done  0.53s user 0.65s system 9% cpu 12.702 total
tutti:[~/src/singly/Locker] time (count=250; while [ $count -ge 0 ]; do wget --no-http-keep-alive -q -O /dev/null http://localhost:8042/Me/devdocs; count=$(($count-1)); done)
( count=250 ; while [ $count -ge 0 ]; do; wget --no-http-keep-alive -q -O  ; =  0.26s user 0.67s system 35% cpu 2.640 total

**Comment by mdz** [comment]
That one is a different test case I suppose, since it is only fetching one URL per connection (though as you can see, enabling/disabling keepalives does make a difference anyway)

**Comment by quartzjer** [comment]
I would expect different behaviors for sure, and I'm not sure which I'd expect to perform better even, but I don't think it's the root cause of any real issue to keep open?

When we get to needing to optimize massive http to an individual locker, I'm pretty sure we'll be refactoring out the http proxy from the stack anyway :)

**Comment by mdz** [comment]
I can't reproduce bad behavior with this code (which I _think_ uses keepalives):

#!/usr/bin/python

import httplib2
import time
import sys

url = sys.argv[1]
iterations = 250

h = httplib2.Http()

start = time.time()
while iterations > 0:
    resp, content = h.request(url, 'GET')
    iterations -= 1

end = time.time()

print end - start

**Comment by mdz** [comment]
The issue we're seeing in practice is #775 anyhow, so I'll track this there
