### ISSUE TITLE
No photos appear in Photos (DEMO) app w/ only Twitter connected

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#783]
This seems odd
<img src="https://img.skitch.com/20120210-djakkw515n9kas45spdwanf575.png">

**Comment by quartzjer** [comment]
I just did this today from scratch and had mine show up, maybe someone
else can reproduce either way?

On Thu, Feb 9, 2012 at 10:29 PM, Merci Victoria Grace
reply@reply.github.com
wrote:

**Comment by quartzjer** [comment]
Reproduced, seems there's none of my own tweets pulled in: https://me.sandbox.singly.com/Me/twitter/getCurrent/tweet?limit=10

**Comment by quartzjer** [comment]
Wrong url, it's https://me.sandbox.singly.com/Me/twitter/getCurrent/tweets?limit=10 and they're there now, it just takes a LONG time to fetch them, I have photos now too.  I'm going to close this and opened #785 as it's the real problem.
