### ISSUE TITLE
Rename "Locker Project" link in Develop nav

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#797]
Let's rename it to "Contribute to the Core Technology" - it's confusing people in usability consistently.

**Comment by kristjan** [comment]
That's real long compared to the rest of the items; how about "Contribute to Locker Core"?

**Comment by merc3po** [comment]
How about "Contribute to Core Tech" - we don't really use "Locker" around the site, and that implies that our product is called Locker.

**Comment by kristjan** [comment]
Deal

**Comment by mdz** [comment]
I find the new text confusing as well, because it's not apparent what "core tech" is and whether it's different from what the developer is already using. How about "Help extend the platform" or something like that?

**Comment by merc3po** [comment]
Cool that seems short enough :-)
