### ISSUE TITLE
Demo apps are all authored by [object Object]

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#800]
IE: https://skitch.com/elsmorian/8bc7c/locker-running

From a fresh git pull this morning.

**Comment by smurthas** [comment]
Did you do a `git submodule update`? There was an update to the dust template that renders that header to fix that.

**Comment by elsmorian** [comment]
No, this might be my problem. Is there any way of telling if a submodule update is needed, or is it good practice to do one after each git pull anyway?

**Comment by smurthas** [comment]
a `git status` will tell you, but it is a good idea to do one each time.

**Comment by elsmorian** [comment]
Okedoke. I can confirm this fixes the issue :)
