### ISSUE TITLE
appFrame isn't hidden when "Click to connect…" is shown

### ISSUE THREAD

**Issue by othiym23** [LockerProject/Locker#805]
![](https://img.skitch.com/20120215-jycnnckdjbii9636uk85qywew.jpg)

**Comment by quartzjer** [comment]
#769 is for apps that specifically don't have any services to list/use, but for ones that do require something and those aren't connected yet I disagree about hiding the app frame, I totally want to give the app an opportunity to do something in that case themselves too (and they should always be expected to not break if there's 0 results).

I'm voting to close this as it currently stands :)

**Comment by othiym23** [comment]
It was @smurthas's opinion that displaying both the arrow and #appFrame's contents was incorrect behavior, so I'll leave it to the two of you to duke it out. I could go either way.

**Comment by quartzjer** [comment]
I actually bumped into this numerous times tonight in cases where I wanted to use the app for things that weren't in it's uses, pretty annoying to be blockaded :/

**Comment by smurthas** [comment]
The bug is that both are showing at the same time (exactly as it is stated). If there is no uses.services field, I will not show the arrow and text.
