### ISSUE TITLE
RFC - Diary entries that note 0 activity

### ISSUE THREAD

**Issue by temas** [LockerProject/Locker#81]
Some of the diary entries right now say something like "Synced 0 xyz".  While this does denote the system did something it also just fills us up with a bunch of junk.  Please add thoughts here.

**Comment by jsmecham** [comment]
Should these not be logged at a "debug" level? That way only useful stuff percolates by default to "info" with the ability to see these less than useful messages through yet-to-be-added filtering controls in the UI.

**Comment by temas** [comment]
Yeah there is an overall need to redo loggin.  Diary is not intended to be a log at all, but a user understandable and visible system of the internal operations affecting their data.  At least that's my current take on it, still.

**Comment by rand** [comment]
We could leave the diary logic simple and comprehensive, and just filter out the null updates in the template.

**Comment by ctide** [comment]
Synclets don't generate any data in the diary, so I'm going to close this one out.  There's certainly a larger story around how we log things, but I don't think this specific issue is relevant to that.
