### ISSUE TITLE
After authing Twitter (and having signed up w/ Github) the rest of the UI shows up

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#817]
<img src="http://cl.ly/0s0f413S043l1d0l0000/Screen%20Shot%202012-02-15%20at%2010.31.00%20PM.png">

**Comment by kristjan** [comment]
What's the problem? I thought that title is the expected behavior, and the image is broken

**Comment by merc3po** [comment]
Ah yeah I think you're right, after reviewing the original mocks. Thank god my brain is not the only documentation. :-P
