### ISSUE TITLE
Problem uploading avatar

### ISSUE THREAD

**Issue by kristjan** [LockerProject/Locker#826]
Using http://www.gravatar.com/avatar/8134f2e2f24cf73b42d1b751582ba408?s=100

```
Unable to update your avatar: SyntaxError: Unexpected token <
```

CC @tantalor

**Comment by smurthas** [comment]
Spoke w @merc3po, we are going to remove the ability to put in a url and add in gravatar support (#827)

**Comment by mdz** [comment]
@smurthas so we should close this in favor of #827?

**Comment by smurthas** [comment]
Yes
