### ISSUE TITLE
Diary entries need to be more legible

### ISSUE THREAD

**Issue by temas** [LockerProject/Locker#83]
Diary entries are intended to be read by a normal user and reasonably understood.  Most of them are close, but at the same time rather confusing about what they are doing.  Need a sweep over them then note any exceptions or specific issues.

**Comment by rand** [comment]
There seems to be a bifurcation of need in the Diary functionality. One need is for a console-like stream of activity, including all events and attempts at action, and the other is for a nicely sanitized human-readable format to represent ongoing activity. Getting some clarity around the intent of the Diary will help us lock down the presentation logic.

**Comment by nym** [comment]
We're going to expose the same type of information in the dashboard in other ways so it's much more understandable to average users. The diary will be still available, but buried in order to be more of an advanced feature for those who require greater detail.

**Comment by temas** [comment]
Is there a design discussion link for this new idea?
