### ISSUE TITLE
Singly reset password fails

### ISSUE THREAD

**Issue by No9** [LockerProject/Locker#834]
When I tried to reset my password on Singly the the process seemed to work but I didn't receive an email.
Also i went to create the profile again using the same Git account and it allowed me to create a user with the same name and reset the password. 
This isn't a bug in itself as I didn't us a different git account but something smells..

**Comment by merc3po** [comment]
Were you logged in and resetting your password from the Account Settings page, or did you follow the "Forgot your password?" link on the Sign In page?

**Comment by No9** [comment]
Followed the reset password link

**Comment by amcjen** [comment]
Just tried this, and I can't repeat.  I got the e-mail and was able to reset it, and log back in.

No9, would you mind trying it again, and if it's good for you, we'll close this issue?

**Comment by No9** [comment]
Yup I couldn't reproduce either. 
Email came through fine this time.
