### ISSUE TITLE
Getting the API key gets stuck in a rut

### ISSUE THREAD

**Issue by No9** [LockerProject/Locker#835]
OS Linux Ubuntu 
Chrome 17.0.963.46
Firefox 10.0.1 

Started https://me.singly.com/dashboard/develop#Develop-BuildAnApp 
Followed instructions about creating a git repo 
Opened the page in Chrome local
The javascript message box locked all my chrome instances even the new ones. 
When I tried to open it up in Firefox the disabled field wouldn't let me select the key tried to inspect element and it still wouldn't let me see the key.

I know its a key but does it need to be so hard?

**Comment by quartzjer** [comment]
Thanks Anton, and sorry about the trouble!  We've been trying to make
it as easy as possible and obviously still have some work to do :)
What would you suggest would be the easiest pattern for you?

On Thu, Feb 16, 2012 at 7:03 PM, Anton Whalley
reply@reply.github.com
wrote:

**Comment by smurthas** [comment]
Ya, the alert is pretty overbearing. I think we could probably do something less intrusive, like a simple JS modal that wouldn't block, just prompt.

**Comment by smurthas** [comment]
In addition to this, it seems as though session storage doesn't work on all browser for file://, but in those case localStorage often does. I will make sure to check that out.

**Comment by No9** [comment]
+1 for smurthas  like a simple JS modal that wouldn't block, just prompt.
Beau helped me get over it in IRC so its all good. 
For anyone else reading this https://singly.com/users/me/apiToken is the link he sent.

**Comment by kristjan** [comment]
This is implemented in Singly/Integral@8ced2f0 and will be deployed soon
