### ISSUE TITLE
Failure installing application

### ISSUE THREAD

**Issue by kristjan** [LockerProject/Locker#839]
```
GET https://me.singly.com/registry/add/tylerstalder-moments 404 (Not Found)
```

cc @h3h

**Comment by quartzjer** [comment]
I saw this in the AM too, I think I know how to fix it, if nobody else has I'll try on my flight!

**Comment by temas** [comment]
If it's one of our older servers, they seem to need a registry sync forced

**Comment by mdz** [comment]
Jason saw this today on prod, and saw it on sandbox recently as well

**Comment by quartzjer** [comment]
Pretty sure they cached ids when they didn't have a key to validate, I'm going to junk the caching logic to permafix this.

**Comment by smurthas** [comment]
In addition to fixing this, I've also added #848, to catch, handle, and report back frontend errors to the locker.

**Comment by quartzjer** [comment]
#849 is meant to address this, but not done yet...

**Comment by quartzjer** [comment]
all, check out https://github.com/LockerProject/Locker/pull/849 I believe it's ready for a pull!
