### ISSUE TITLE
Can't load app: 'Cannot GET /Me/beaugunderson-meta-me/'

### ISSUE THREAD

**Issue by beaugunderson** [LockerProject/Locker#840]
I have an app (Meta Me) that does't load on me.singly.com:

![screenshot](http://i.imgur.com/vJfex.png)

I recently committed a description and a screenshot, hit the publish button, clicked 'check' and verified that it could see that update.

I haven't actually published the app yet (because I'm still testing it). In the past that hasn't mattered; does it now?

**Comment by beaugunderson** [comment]
Attempting to actually publish the app didn't solve the problem either. :)

**Comment by kristjan** [comment]
We get a 304 during install instead of a couple 200s from a working one (https://github.com/beaugunderson/playground)

https://gist.github.com/2003768

**Comment by beaugunderson** [comment]
Interesting, the directory shown in your gist is missing files (no index.html, js/, img/, for example)

**Comment by kristjan** [comment]
Yeah, it looks like the NPM tarball is actually incomplete

http://jer.iriscouch.net/registry/_design/app/_rewrite/beaugunderson-meta-me/-/beaugunderson-meta-me-0.0.2.tgz

**Comment by kristjan** [comment]
Current hypothesis is that the tarball was generated from an incomplete repo sync as a result of #725. @beaugunderson, if it works with the unpublished version, can you try republishing?

Thoughts on avoiding this in the future:
- Pull the tarballs GitHub makes out of tags
- Let devs upload their own tarball

**Comment by kristjan** [comment]
@quartzjer, Need your help on this one. Force synching doesn't appear to pull in the rest of the repo.

**Comment by beaugunderson** [comment]
I met up with @quartzjer last night and we resolved this by removing the cached entry. There should probably be another ticket opened to make the github synclet cache less aggressively (maybe the ability to overwrite partial syncs if the force parameter is true?)
