### ISSUE TITLE
Many photos not being displayed due to http/https mismatch

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#844]
Looking at the photos demo in my account, most of the photo previews are shown as broken images, because they're being served over HTTP rather than HTTPS.

**Comment by amcjen** [comment]
From what connectors are you getting broken images?

**Comment by mdz** [comment]
I don't know how to determine that for sure, but I think they're Twitter and Facebook based on the URLs, e.g.:

http://p.twimg.com/AlRNxaVCAAECFux.jpg
http://www.facebook.com/photo.php?fbid=10150543553236536&set=a.419863696535.198057.39606211535&type=1

**Comment by amcjen** [comment]
hmm, ok.  Flickr as well.  Not sure Flickr even allows https versions of their URLs. (I tried, and got a "cert not trusted" message)

We should be able to redirect the twitter and facebook ones though I think.

**Comment by mdz** [comment]
my Flickr photos seem to be showing up OK in photos DEMO, even though they're http: URLs. Weird.

**Comment by amcjen** [comment]
I dug deeper into this, and tried kicking every photo URL to https instead of http, and that caused a bunch of broken images, as Chrome won't load Instagram over https because of a CA cert mismatch.  Same with Twitpic.  Not sure what to do at this point.  Thoughts?

**Comment by beaugunderson** [comment]
@erictj Jeremie did add the ?proxy=1 parameter to `/Me/photos/thumbnail/:id` and `/Me/photos/:id` to proxy the image data--that will display the images at the expense of additional Singly bandwidth/CPU.

(This is how Spearmint attempts to get around Flickr and Facebook not returning CORS headers)

**Comment by amcjen** [comment]
Awesome @beaugunderson, I'll have a look at that.  Thanks!
