### ISSUE TITLE
GET of api.singly.com/:token/push is missing CORS headers

### ISSUE THREAD

**Issue by beaugunderson** [LockerProject/Locker#853]
```
XMLHttpRequest cannot load https://api.singly.com/[censored]/push.

Origin http://beaugunderson.com is not allowed by Access-Control-Allow-Origin.
```

Previously `/push` returned valid CORS headers.

This is what's needed:

```
res.header("Access-Control-Allow-Origin", "*");
res.header("Access-Control-Allow-Headers", "X-Requested-With");
```

**Comment by smurthas** [comment]
The Allow-Origin header is already there, and the Allow-Headers shouldn't be needed with `$.post` - is something failing or not working for you?

See https://github.com/smurthas/HistoMine/blob/master/extension/background.js#L41 for a working example

**Comment by beaugunderson** [comment]
I'm trying to GET, not POST :)

Edit: A GET of that URL should return the list of push datasets, according to the dev docs. This allows me to build the list automatically so that I can visualize data from them with the Playground app I'm working on.
