### ISSUE TITLE
LinkaLatte not working

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#862]
@jasoncavnar saw this on his locker on singly.com

**Comment by mdz** [comment]
This is still happening, and is adversely affecting Jason's demos. :-)

**Comment by mdz** [comment]
Possibly related?

[links] 
[links] /home/Collections/Links/dataIn.js:165
[links]                        locker.ievent(lutil.idrNew("link","links",obj.id),obj);
[links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links]  [links] ^[links] 
[links] TypeError: Cannot read property 'id' of undefined
    at /home/Collections/Links/dataIn.js:165:76
    at /home/node_modules/mongodb/lib/mongodb/collection.js:570:7
    at /home/node_modules/mongodb/lib/mongodb/db.js:821:14
    at [object Object]._executeQueryCommand (/home/node_modules/mongodb/lib/mongodb/db.js:1009:5)
    at Collection.findAndModify (/home/node_modules/mongodb/lib/mongodb/collection.js:566:11)
    at Object.addLink (/home/Collections/Links/dataStore.js:114:20)
    at /home/Collections/Links/dataIn.js:164:37
    at Object.extractFavicon (/home/Collections/Links/util.js:76:5)
    at /home/Collections/Links/dataIn.js:159:28
    at Object.extractText (/home/Collections/Links/util.js:65:5)

**Comment by kristjan** [comment]
Appears resolved; Jason can see links again.

New known bug in #912
