### ISSUE TITLE
Add explicit mongo path to config

### ISSUE THREAD

**Issue by josephboyle** [LockerProject/Locker#87]
josephboyle ‣ Looks like the same one nym mentioned May 28 12:06 https://gist.github.com/997405       June 1 10:32 
temas   ‣ mongod is in path?      10:36
josephboyle ‣ mongod not in path - do you set this in shell environment or supposed to be somewhere in startup scripts?       10:39
temas   ‣ josephboyle:  shell right now, file a ticket to add the explicit path to config

**Comment by temas** [comment]
If an explicit path is set use that, otherwise normal system path usage.

**Comment by smcnally** [comment]
my mongo install had default data path at /data/db
though mongod is in PATH, I was getting same error (as https://gist.github.com/997405)
I replaced Locker/Me/mongodata with a symlink to /data/db and all is well again 
since updating to 0.1.0
