### ISSUE TITLE
on restart, synclet next run gets reset

### ISSUE THREAD

**Issue by quartzjer** [LockerProject/Locker#874]
defaults to the next frequency, ignoring the existing offset saved

**Comment by smurthas** [comment]
This is how the function used to work: https://github.com/LockerProject/Locker/blob/7d062489f81963105083965a71eabc657337c102/Common/node/lsyncmanager.js#L214

notice lines 215-217 where it does the modulus and if < 0, bumps it up. That simple logic is all we need to add back in to schedule things evenly. Not sure why it ever got taken out!

**Comment by mdz** [comment]
I'm not entirely sure, but you and @smurthas  seem to be talking about different things here. Are there two separate issues?
