### ISSUE TITLE
Locker won't start without build.json 

### ISSUE THREAD

**Issue by tomgalloway** [LockerProject/Locker#879]
Hi,

On the latest code, lockerd.js trys to open build.json but this file isn't created or under source control. I've got round it by creating this file with dummy data but I'm not sure what data needs to be in here?

Cheers,
Tom

**Comment by quartzjer** [comment]
I'm mobile at the moment, but I believe the makefile should create it, try typing 'make'?

**Comment by tomgalloway** [comment]
Yeah that fixed it thanks.
