### ISSUE TITLE
"check for updates" button doesn't see the latest updates to my app

### ISSUE THREAD

**Issue by beaugunderson** [LockerProject/Locker#882]
Singly thinks the last update was 5 days ago:

![Screenshot](http://f.cl.ly/items/1i2e0L3Z180m471r2Y1z/Image%202012-02-28%20at%202.44.28%20PM.png)

In reality, it was 4 days [more recent than that](https://github.com/beaugunderson/Playground/commit/2c3c7719841b879059b9e8a1e9c71f65b4b50cdf). :)

I clicked the "check for updates" button 5 or so times today and yesterday.

**Comment by quartzjer** [comment]
There's a bug where an empty file makes the sync barf, in this case https://github.com/beaugunderson/Playground/blob/master/css/iframe.css is 0, I'll work on fixing the silly barf but you can also make the sync work by removing or putting something in there as a workaround :)

**Comment by beaugunderson** [comment]
Thanks for the workaround and the explanation! :)

---

Sent from my phone.

On Feb 28, 2012, at 6:37 PM, Jeremie Miller
reply@reply.github.com
wrote:
