### ISSUE TITLE
don't sort primary key indexed queries

### ISSUE THREAD

**Issue by quartzjer** [LockerProject/Locker#890]
it's a stupid idea

http://stackoverflow.com/questions/8440694/mongodb-not-using-indexes-when-sorting

**Comment by othiym23** [comment]
Can you expand on why you think it's stupid? The referenced thread doesn't say it's a bad idea to sort, just that you have to be aware of how sorts & queries will interact with the indexes you have, which is going to be true for pretty much any query optimizer for any DB.

**Comment by quartzjer** [comment]
What is stupid is that in most of our indexed primary key queries
we're passing in an irrelevant sort that is confusing things, I'm
cleaning them up this afternoon.

On Wed, Feb 29, 2012 at 3:15 PM, Forrest L Norvell
reply@reply.github.com
wrote:

**Comment by quartzjer** [comment]
Fixed in https://github.com/LockerProject/Locker/commit/87d6852032aca2d70565c5d07004c1fdb2982c78
