### ISSUE TITLE
statsd doesn't use the value of the count for counters

### ISSUE THREAD

**Issue by othiym23** [LockerProject/Locker#915]
...so I need to find a way to get the length counter to accurately report that length. That, or modify statsd.

**Comment by merc3po** [comment]
What does this relate to?

**Comment by othiym23** [comment]
Gathering information about the state of the infrastructure for performance monitoring. Also, I think @temas fixed this yesterday or the day before. Temas?

**Comment by temas** [comment]
I modified how it was sending the length, is it still incorrect?

**Comment by othiym23** [comment]
Closing as resolved. 🎌
