### ISSUE TITLE
file descriptor leakage

### ISSUE THREAD

**Issue by quartzjer** [LockerProject/Locker#917]
Something is leaking file descriptors, I'm seeing hundreds per node process, and lsof shows them as an unknown/anonymous socket, so far docs suggest that is one being deleted before close()'d?

**Comment by mdz** [comment]
I believe this is what @othiym23 intended to fix in 2c9aef54ff8f2dd5e3c75c948d29885774513bb3

**Comment by othiym23** [comment]
We can consider this one closed, unless we see a reversion. Node does not go out of its way to make working with datagrams simple, but the oversight was mine. Sorry about this / the storm of notifications we got overnight.
