### ISSUE TITLE
Error processing json: TypeError: Cannot read property 'page' of undefined

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#920]
Error processing json: TypeError: Cannot read property 'page' of undefined
13 Mar 15:34:44 - error: Uncaught exception:
13 Mar 15:34:44 - error: [TypeError: Cannot read property 'contact' of undefined]
13 Mar 15:34:44 - error: 'TypeError: Cannot read property \'contact\' of undefined\n    at Request._callback (/home/Connectors/Flickr/lib/paging.js:51:42)\n    at Request.callback (/home/node_modules/request/main.js:108:22)\n    at Request.<anonymous> (/home/node_modules/request/main.js:468:18)\n    at Request.emit (events.js:67:17)\n    at IncomingMessage.<anonymous> (/home/node_modules/request/main.js:429:16)\n    at IncomingMessage.emit (events.js:88:20)\n    at HTTPParser.onMessageComplete (http.js:137:23)\n    at Socket.ondata (http.js:1147:24)\n    at TCP.onread (net.js:354:27)'

**Comment by temas** [comment]
Fixed in b8c74e5bf7400a23f0bfbc736384495a3f433a3c
