### ISSUE TITLE
Uncaught exception at shutdown: TypeError: undefined is not a function

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#921]
13 Mar 15:34:44 - info: [mongo] Tue Mar 13 15:34:44 dbexit: really exiting now
13 Mar 15:34:44 - error: Uncaught exception:
13 Mar 15:34:44 - error: [TypeError: undefined is not a function]
13 Mar 15:34:44 - error: 'TypeError: undefined is not a function\n    at /home/node_modules/mongodb/lib/mongodb/db.js:661:28\n    at /home/node_modules/mongodb/lib/mongodb/db.js:715:28\n    at /home/node_modules/mongodb/lib/mongodb/cursor.js:131:30\n    at /home/node_modules/mongodb/lib/mongodb/cursor.js:175:32\n    at [object Object].<anonymous> (/home/node_modules/mongodb/lib/mongodb/cursor.js:447:48)\n    at [object Object].g (events.js:156:14)\n    at [object Object].emit (events.js:70:17)\n    at /home/node_modules/mongodb/lib/mongodb/connection/server.js:459:35\n    at [object Object].<anonymous> (/home/node_modules/mongodb/lib/mongodb/connection/server.js:406:7)\n    at [object Object].emit (events.js:88:20)'

Looks like it's probably due to:

Collections/Photos/dataStore.js:    collection.ensureIndex({url:1});
 Collections/Photos/dataStore.js:    collection.ensureIndex({name:1});

(all the pre-existing ensureIndex calls pass a callback)

**Comment by temas** [comment]
Fixed in b8c74e5bf7400a23f0bfbc736384495a3f433a3c
