### ISSUE TITLE
lastfm: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#929]
15 Mar 00:59:26 - error: Uncaught exception:
15 Mar 00:59:26 - error: [TypeError: Cannot read property 'length' of undefined]
15 Mar 00:59:26 - error: 'TypeError: Cannot read property \'length\' of undefined\n    at /home/Connectors/LastFM/lib.js:296:47\n    at Request._callback (/home/Connectors/LastFM/lib.js:101:45)\n    at Request.callback (/home/node_modules/request/main.js:108:22)\n    at Request.<anonymous> (/home/node_modules/request/main.js:468:18)\n    at Request.emit (events.js:67:17)\n    at IncomingMessage.<anonymous> (/home/node_modules/request/main.js:429:16)\n    at IncomingMessage.emit (events.js:88:20)\n    at HTTPParser.onMessageComplete (http.js:137:23)\n    at Socket.ondata (http.js:1147:24)\n    at TCP.onread (net.js:354:27)'

**Comment by othiym23** [comment]
This should be resolved by 5c281687056a5b1e68bcf7d936ad02a93e811dc6. But, you know, testing first.

**Comment by othiym23** [comment]
Yup. That, and the following 2 or 3 commits, fixed the issue. Deployed as part of build 695.
