### ISSUE TITLE
"SYNC GITHUB" button doesn't refresh app list if there's a new repo

### ISSUE THREAD

**Issue by beaugunderson** [LockerProject/Locker#935]
My GitHub account contained a repo that wasn't in my "YOUR APPS" list.

I clicked the "SYNC GITHUB" button and it went through the 'synching', 'synched' states, but the list didn't update.

I did a full page refresh and the list contained the new repository. It would be nice if it refreshed the app list after the sync process completed. :)

**Comment by kristjan** [comment]
Good call. The 4 second fix would be to just autorefresh the whole page.

On Sun, Mar 18, 2012 at 9:22 PM, Beau Gunderson <
reply@reply.github.com
