### ISSUE TITLE
Links to the developer documentation should redirect when a logged-out user visits

### ISSUE THREAD

**Issue by beaugunderson** [LockerProject/Locker#937]
Currently if you click a link to the dev docs and you're logged out this is all you get to see:

```
Cannot GET /dashboard/develop
```

It would be nice if there was a redirect to somewhere with more information. At present when people want dev docs on IRC that's the best place, and if they happen to be logged out they'll just see an error message.

**Comment by tylerstalder** [comment]
Yea, right now all the dev docs are being served out of the locker. I think we'll want to move some onto these pages https://singly.com/develop/start so they're link friendly, as well as not requiring login.
