### ISSUE TITLE
Add support for Static Apps

### ISSUE THREAD

**Issue by nym** [LockerProject/Locker#95]
Add a flag in the manifest that allows for apps to run just as static, allowing read only access to:

index.html
static/js/
static/css/
static/img/

This would allow frontend only developers to do quick apps that communicate with the collections solely via ajax, since not every app needs a server in order to be useful.

**Comment by smurthas** [comment]
There is a simple example of this in the Merged Contacts Viewer, the contacts.js file there could be made generic and used as part of lservicemanager

**Comment by ctide** [comment]
Resolved in: https://github.com/LockerProject/Locker/commit/3753ff18d3689d5b3b979a5a4c00b03e5907841a
