### ISSUE TITLE
run locker with node v6

### ISSUE THREAD

**Issue by clemsos** [LockerProject/Locker#957]
hi there ! 

I can't wait to test this awesome Locker project !
I have clone code from github and follow install instructions, but no way to make it work

Actually it is very similar to the issues described here :  https://github.com/LockerProject/Locker/pull/533

```
The "sys" module is now called "util". It should have a similar interface.
```

and

```
$ node runTests.js
Locker did not start correctly, got the error: Error: Cannot find module 'lutil'
```

here is the whole log error i got when accessing webpage from my browser
any suggestions/idea ?

``` javascript

[dashboardv3] The "sys" module is now called "util". It should have a similar interface.
[dashboardv3] <Buffer 65 78 65 63 76 70 28 29 3a 20 4e 6f 20 73 75 63 68 20 66 69 6c 65 20 6f 72 20 64 69 72 65 63 74 6f 72 79 0a>
[dashboardv3] 
[dashboardv3] node.js:201
[dashboardv3]         throw e; // process.nextTick error, or 'error' event on first tick
              ^
[dashboardv3] Error: Cannot find module 'connect-form'
    at Function._resolveFilename (module.js:334:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/home/clement/Locker/Apps/dashboardv3/dashboard-client.js:20:12)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)
24 Jun 13:07:55 - info: dashboardv3 exited with status 1, signal null
```

**Comment by bewest** [comment]
Me too.

**Comment by Laobei2012** [comment]
Me too

**Comment by kristjan** [comment]
Hi all!

"Official" development has moved from Locker to
https://github.com/Singly/hallway, so first I'd recommend you try running
that instead. It does very much the same thing, just provides more of an
API and slightly less of a Locker, but it is far more up to date.

But, if you'd like to continue on Locker (which is still definitely a great
project, just lacking a maintainer):
- Try running `make test` from the repository root. It does more setup.
- Run the Locker with `./locker`. It should tell you what configs you need
  and where.
- Make sure you have compatible libraries defined in `package.json`. NPM
  will happily install newer versions that may not be friendly with Node
  v0.6. If someone knows what versions were around to lock to in Feb 2012,
  those should work.
- In particular, `lutil` exists in `/Common/node`. Try starting up with
  NODE_PATH=./Common/node so it's in the search path, but that should be
  initialized by the run scripts.

Hope that's helpful; happy hacking!

**Comment by bewest** [comment]
Hmm.  Well, my pull request https://github.com/LockerProject/Locker/pull/961 fixes this issue, FWIW.  Will check out hallway.

**Comment by Laobei2012** [comment]
@bewest it does work, thanks

**Comment by kristjan** [comment]
Merged! Thanks, Ben

**Comment by clemsos** [comment]
Many thanks ! it works for me. I close this issue
