### ISSUE TITLE
Collections should always listen for events

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#99]
Since collections are always installed, they should always be listening for events, even if they have never been accessed by the locker owner in the current session or a previous one. Perhaps is could simply be specified in the manifest file.

**Comment by ctide** [comment]
Closed in https://github.com/LockerProject/Locker/commit/4d5add8a108bf59da6cb6a922335dac80a836e10 and https://github.com/LockerProject/Locker/commit/05412ca97f3337f836740ce162971944145bd5ee
